/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Normal.Closure

/-!
# The normal closure of a simple extension

Inside a normal extension, the normal closure of `F⟮x⟯` is generated by the roots of
`minpoly F x`. Thus it is a splitting field of that polynomial. This identifies the
field used to study a simple extension with the field used to define its polynomial
Galois group.
-/

/- The proof uses Mathlib's description of the normal closure as the supremum of the
conjugate fields and `minpoly.exists_algEquiv_of_root'`. -/

public section

namespace TauCeti

open IntermediateField Polynomial

variable {F E : Type*} [Field F] [Field E] [Algebra F E] [Normal F E]

/-- The normal closure of a simple extension is generated by all the conjugates of its
generator, equivalently by the roots of its minimal polynomial. -/
theorem normalClosure_adjoin_simple_eq_adjoin_rootSet (x : E) :
    normalClosure F F⟮x⟯ E = adjoin F ((minpoly F x).rootSet E) := by
  rw [normalClosure_def'']
  apply le_antisymm
  · refine iSup_le fun σ ↦ ?_
    rw [adjoin_map, Set.image_singleton]
    rw [adjoin_simple_le_iff]
    apply subset_adjoin
    rw [mem_rootSet_of_ne (minpoly.ne_zero (Algebra.IsIntegral.isIntegral x))]
    simp [aeval_algHom_apply]
  · refine adjoin_le_iff.mpr fun y hy ↦ ?_
    obtain ⟨σ, hσ⟩ := minpoly.exists_algEquiv_of_root'
      (Algebra.IsAlgebraic.isAlgebraic x) (mem_rootSet.mp hy).2
    apply le_iSup (fun σ : E ≃ₐ[F] E ↦ F⟮x⟯.map σ.toAlgHom) σ
    exact ⟨x, mem_adjoin_simple_self F x, hσ⟩

/-- The normal closure of a simple extension is a splitting field of the generator's
minimal polynomial. No separability hypothesis is needed. -/
theorem isSplittingField_normalClosure_adjoin_simple (x : E) :
    IsSplittingField F (normalClosure F F⟮x⟯ E) (minpoly F x) := by
  rw [normalClosure_adjoin_simple_eq_adjoin_rootSet]
  exact adjoin_rootSet_isSplittingField (Normal.splits (inferInstance : Normal F E) x)

end TauCeti
