/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Degree
public import TauCeti.NumberTheory.Multiquadratic.Galois.Relative

/-!
# The relative Galois group of the candidate genus field

For a squarefree integer `d`, the candidate genus field is abelian Galois over `ℚ`, with absolute
Galois group the sign vectors on the chosen prime-discriminant roots. It contains the embedded base
`candidateGenusFieldBase hd`, generated by a chosen square root of `d`. This file identifies
the relative Galois group over that base with the subspace of sign vectors whose automorphisms fix
the base.

More precisely, `candidateGenusFieldRelativeSignSubmodule hd` is the parity-zero subspace of sign
vectors. The product of all the prime-discriminant generators is a nonzero rational multiple of
`candidateGenusFieldBaseRoot hd`, so an automorphism fixes the embedded base exactly
when its sign vector has even parity. Restriction of scalars then gives

`Gal(candidateGenusField hd / candidateGenusFieldBase hd) ≃* Multiplicative U`.

This is the relative Galois-group side of the genus-field construction; the sign subspace found
here is matched with the genus characters of `ℚ(√d)`, hence with the maximal elementary-2 quotient
`Cl⁺(ℚ(√d)) / Cl⁺(ℚ(√d))²`, in
`TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.GenusCharacter`. When `d` is
nonsquare, its order is the predicted `2 ^ (t - 1)`, where `t` is the number of chosen prime
discriminants.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Provenance

The relative Galois equivalence and its action on generators specialize
`TauCeti.NumberTheory.Multiquadratic.Galois.Relative`, whose Layer-0 multiquadratic machinery is
migrated from [kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance conjecture.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldRelativeSignSubmodule`: the sign vectors fixing the
  embedded base.
* `TauCeti.Multiquadratic.galoisGroupEquivCandidateGenusFieldRelative`: the relative Galois group
  as that sign subspace.

## Main results

* `TauCeti.Multiquadratic.galoisGroupEquivCandidateGenusFieldRelative_apply`: the equivalence is
  given by the sign pattern of the restricted automorphism.
* `TauCeti.Multiquadratic.card_aut_candidateGenusField_over_base`: the relative Galois group has
  order `2 ^ (t - 1)` when `d` is nonsquare.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The product of the chosen prime-discriminant generators of the candidate genus field. -/
noncomputable def candidateGenusFieldProdRoot {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd :=
  ∏ P : {P // P ∈ genusPrimeDiscriminants hd}, candidateGenusFieldGen hd P

/-- The square of the product root is the product of the prime-discriminant radicands. -/
@[simp] theorem candidateGenusFieldProdRoot_sq {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldProdRoot hd ^ 2 =
      algebraMap ℚ (candidateGenusField hd)
        (∏ P : {P // P ∈ genusPrimeDiscriminants hd},
          ((primeDiscriminantRadicand P.val : ℤ) : ℚ)) := by
  rw [candidateGenusFieldProdRoot, ← Finset.prod_pow]
  simp

/-- The product of all prime-discriminant generators is a nonzero rational multiple of the chosen
base root. Thus the embedded base `candidateGenusFieldBase` is the subfield generated by this
concrete product root. -/
theorem exists_candidateGenusFieldProdRoot_eq_mul_baseRoot {d : ℤ} (hd : Squarefree d) :
    ∃ a : ℚ, a ≠ 0 ∧
      candidateGenusFieldProdRoot hd =
        algebraMap ℚ (candidateGenusField hd) a * candidateGenusFieldBaseRoot hd := by
  obtain ⟨a, ha, hrad⟩ := exists_prod_radicand_eq_sq_mul_of_prod_primeDiscriminant_eq
    (genusPrimeDiscriminants_spec hd).1 (genusPrimeDiscriminants_spec hd).2.2
  rw [← Finset.univ_eq_attach] at hrad
  have hsq : candidateGenusFieldProdRoot hd ^ 2 =
      (algebraMap ℚ (candidateGenusField hd) a * candidateGenusFieldBaseRoot hd) ^ 2 := by
    rw [candidateGenusFieldProdRoot_sq, hrad, map_mul, map_pow, mul_pow,
      candidateGenusFieldBaseRoot_sq]
  rcases (sq_eq_sq_iff_eq_or_eq_neg.mp hsq) with h | h
  · exact ⟨a, ha, h⟩
  · refine ⟨-a, neg_ne_zero.mpr ha, ?_⟩
    rw [map_neg, neg_mul]
    exact h

/-- The `𝔽₂`-subspace of even-parity sign patterns. These, independently of the Galois action,
are the functions whose coordinate sum is zero. -/
noncomputable def candidateGenusFieldRelativeSignSubmodule {d : ℤ} (hd : Squarefree d) :
    Submodule (ZMod 2) ({P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :=
  LinearMap.ker (Fintype.linearCombination (ZMod 2) (fun _ => (1 : ZMod 2)))

/-- A sign vector belongs to the relative sign subspace exactly when its coordinate sum vanishes. -/
@[simp] theorem mem_candidateGenusFieldRelativeSignSubmodule_iff {d : ℤ} (hd : Squarefree d)
    (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :
    v ∈ candidateGenusFieldRelativeSignSubmodule hd ↔ ∑ P, v P = 0 := by
  simp [candidateGenusFieldRelativeSignSubmodule, Fintype.linearCombination_apply]

private theorem candidateGenusFieldProdRoot_ne_zero {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldProdRoot hd ≠ 0 := by
  rw [candidateGenusFieldProdRoot]
  exact Finset.prod_ne_zero_iff.mpr fun P _ => candidateGenusFieldGen_ne_zero hd P

private theorem candidateGenusField_apply_gen {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    σ (candidateGenusFieldGen hd P) =
      (-1) ^ (candidateGenusFieldSignPattern hd σ P).val * candidateGenusFieldGen hd P := by
  have heq : (galoisGroupEquivCandidateGenusField hd).symm
      (Multiplicative.ofAdd (candidateGenusFieldSignPattern hd σ)) = σ := by
    rw [← galoisGroupEquivCandidateGenusField_apply hd σ]
    exact (galoisGroupEquivCandidateGenusField hd).symm_apply_apply σ
  calc
    σ (candidateGenusFieldGen hd P) =
        ((galoisGroupEquivCandidateGenusField hd).symm
          (Multiplicative.ofAdd (candidateGenusFieldSignPattern hd σ)))
            (candidateGenusFieldGen hd P) :=
      congrArg
        (fun τ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd =>
          τ (candidateGenusFieldGen hd P)) heq.symm
    _ = _ := galoisGroupEquivCandidateGenusField_symm_apply_gen hd
      (candidateGenusFieldSignPattern hd σ) P

private theorem candidateGenusField_apply_prodRoot {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ (candidateGenusFieldProdRoot hd) =
      (-1) ^ (∑ P, (candidateGenusFieldSignPattern hd σ P).val) *
        candidateGenusFieldProdRoot hd := by
  rw [candidateGenusFieldProdRoot, map_prod]
  simp_rw [candidateGenusField_apply_gen]
  rw [Finset.prod_mul_distrib, Finset.prod_pow_eq_pow_sum]

private theorem sum_zmod_eq_zero_iff_even_sum_val {ι : Type*} [Fintype ι] (v : ι → ZMod 2) :
    (∑ i, v i) = 0 ↔ Even (∑ i, (v i).val) := by
  have hcast : ((∑ i, (v i).val : ℕ) : ZMod 2) = ∑ i, v i := by
    rw [Nat.cast_sum]
    exact Finset.sum_congr rfl fun i _ => ZMod.natCast_zmod_val (v i)
  rw [← hcast, ZMod.natCast_eq_zero_iff_even]

private theorem candidateGenusField_fix_prodRoot_iff_sum_signPattern_eq_zero {d : ℤ}
    (hd : Squarefree d) (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ (candidateGenusFieldProdRoot hd) = candidateGenusFieldProdRoot hd ↔
      ∑ P, candidateGenusFieldSignPattern hd σ P = 0 := by
  rw [candidateGenusField_apply_prodRoot]
  constructor
  · intro hfix
    have hpow : (-1 : candidateGenusField hd) ^
        (∑ P, (candidateGenusFieldSignPattern hd σ P).val) = 1 := by
      apply mul_right_cancel₀ (candidateGenusFieldProdRoot_ne_zero hd)
      simpa using hfix
    apply (sum_zmod_eq_zero_iff_even_sum_val _).mpr
    exact (neg_one_pow_eq_one_iff_even (by norm_num)).mp hpow
  · intro hsum
    have heven : Even (∑ P, (candidateGenusFieldSignPattern hd σ P).val) :=
      (sum_zmod_eq_zero_iff_even_sum_val _).mp hsum
    rw [heven.neg_one_pow, one_mul]

private theorem candidateGenusField_mem_fixingSubgroup_iff_fix_prodRoot {d : ℤ}
    (hd : Squarefree d) (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ ∈ (candidateGenusFieldBase hd).fixingSubgroup ↔
      σ (candidateGenusFieldProdRoot hd) = candidateGenusFieldProdRoot hd := by
  obtain ⟨a, ha, hprod⟩ := exists_candidateGenusFieldProdRoot_eq_mul_baseRoot hd
  constructor
  · intro hσ
    rw [IntermediateField.mem_fixingSubgroup_iff] at hσ
    apply hσ
    rw [hprod]
    exact (candidateGenusFieldBase hd).mul_mem
      (IntermediateField.algebraMap_mem _ _) (candidateGenusFieldBaseRoot_mem hd)
  · intro hfix
    have hmap : algebraMap ℚ (candidateGenusField hd) a ≠ 0 :=
      by simpa using (algebraMap ℚ (candidateGenusField hd)).injective.ne ha
    have hroot : σ (candidateGenusFieldBaseRoot hd) = candidateGenusFieldBaseRoot hd := by
      apply mul_left_cancel₀ hmap
      calc
        algebraMap ℚ (candidateGenusField hd) a * σ (candidateGenusFieldBaseRoot hd) =
            σ (algebraMap ℚ (candidateGenusField hd) a *
              candidateGenusFieldBaseRoot hd) := by rw [map_mul, σ.commutes]
        _ = σ (candidateGenusFieldProdRoot hd) := by rw [hprod]
        _ = candidateGenusFieldProdRoot hd := hfix
        _ = algebraMap ℚ (candidateGenusField hd) a * candidateGenusFieldBaseRoot hd := hprod
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro x hx
    rw [candidateGenusFieldBase_def] at hx
    refine IntermediateField.adjoin_induction (F := ℚ)
      (s := {candidateGenusFieldBaseRoot hd}) (p := fun y _ => σ y = y)
      ?_ ?_ ?_ ?_ ?_ (x := x) (h := hx)
    · intro y hy
      simpa only [Set.mem_singleton_iff] using hy ▸ hroot
    · exact fun q => σ.commutes q
    · intro y z _ _ hy hz
      simp only [map_add, hy, hz]
    · intro y _ hy
      simp only [map_inv₀, hy]
    · intro y z _ _ hy hz
      simp only [map_mul, hy, hz]

private theorem candidateGenusField_mem_fixingSubgroup_iff_sum_signPattern_eq_zero {d : ℤ}
    (hd : Squarefree d) (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ ∈ (candidateGenusFieldBase hd).fixingSubgroup ↔
      ∑ P, candidateGenusFieldSignPattern hd σ P = 0 :=
  (candidateGenusField_mem_fixingSubgroup_iff_fix_prodRoot hd σ).trans
    (candidateGenusField_fix_prodRoot_iff_sum_signPattern_eq_zero hd σ)

private theorem candidateGenusFieldRoot_independent {d : ℤ} (hd : Squarefree d) :
    ∀ S : Finset {P // P ∈ genusPrimeDiscriminants hd}, S.Nonempty →
      ¬ IsSquare (∏ P ∈ S, ((primeDiscriminantRadicand P.val : ℤ) : ℚ)) := by
  obtain ⟨hprime, heven_unique, _⟩ := genusPrimeDiscriminants_spec hd
  exact not_isSquare_prod_primeDiscriminantRadicands_of_forall_isEvenPrimeDiscriminant_eq
    (fun P : {P // P ∈ genusPrimeDiscriminants hd} ↦ P.val)
    (fun P ↦ hprime P.val P.property) Subtype.val_injective
    (fun P Q hP hQ ↦ heven_unique P.val P.property Q.val Q.property hP hQ)

/-- The rational algebra structure inherited by the adjoin presentation of the candidate genus
field. -/
noncomputable local instance candidateGenusFieldAdjoinAlgebra {d : ℤ} (hd : Squarefree d) :
    Algebra ℚ (adjoin ℚ (Set.range (genusFieldRoot hd))) :=
  (adjoin ℚ (Set.range (genusFieldRoot hd))).algebra'

private noncomputable def candidateGenusFieldEquivAdjoinRelative {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd ≃ₐ[ℚ]
      @adjoin ℚ _ ℂ _ _ (Set.range (genusFieldRoot hd)) :=
  AlgEquiv.ofRingEquiv
    (f := (candidateGenusFieldEquivAdjoin hd).toRingEquiv) fun q ↦ by
    apply Subtype.ext
    exact congrArg Subtype.val ((candidateGenusFieldEquivAdjoin hd).commutes q)

@[simp] private theorem candidateGenusFieldEquivAdjoinRelative_apply_gen {d : ℤ}
    (hd : Squarefree d) (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldEquivAdjoinRelative hd (candidateGenusFieldGen hd P) =
      gen (genusFieldRoot hd) P := by
  exact candidateGenusFieldEquivAdjoin_apply_gen hd P

private theorem candidateGenusFieldSignPattern_eq_relativePresentation {d : ℤ}
    (hd : Squarefree d) (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    candidateGenusFieldSignPattern hd σ =
      signPattern (genusFieldRoot hd)
        (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd) σ) := by
  funext P
  rw [candidateGenusFieldSignPattern_apply]
  simp only [signPattern]
  congr 1
  rw [← candidateGenusFieldEquivAdjoinRelative_apply_gen]
  simp only [AlgEquiv.autCongr_apply, AlgEquiv.trans_apply, AlgEquiv.symm_apply_apply,
    (candidateGenusFieldEquivAdjoinRelative hd).injective.eq_iff]

private noncomputable def candidateGenusFieldBaseAdjoin {d : ℤ} (hd : Squarefree d) :
    @IntermediateField ℚ (adjoin ℚ (Set.range (genusFieldRoot hd))) _ _
      (adjoin ℚ (Set.range (genusFieldRoot hd))).algebra' :=
  (candidateGenusFieldBase hd).map (candidateGenusFieldEquivAdjoinRelative hd).toAlgHom

private theorem candidateGenusField_map_fixingSubgroup {d : ℤ} (hd : Squarefree d) :
    (candidateGenusFieldBase hd).fixingSubgroup.map
        (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)).toMonoidHom =
      (candidateGenusFieldBaseAdjoin hd).fixingSubgroup := by
  ext τ
  simp only [Subgroup.mem_map]
  constructor
  · rintro ⟨σ, hσ, rfl⟩
    rw [IntermediateField.mem_fixingSubgroup_iff] at hσ ⊢
    intro x hx
    rw [candidateGenusFieldBaseAdjoin, IntermediateField.mem_map] at hx
    obtain ⟨y, hy, rfl⟩ := hx
    -- `autCongr` is defined by conjugation, so exposing its action on a transported element
    -- requires this definitional reduction before the public `autCongr_apply` lemma applies.
    change (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd) σ)
      (candidateGenusFieldEquivAdjoinRelative hd y) =
        candidateGenusFieldEquivAdjoinRelative hd y
    rw [AlgEquiv.autCongr_apply]
    simp only [AlgEquiv.trans_apply, AlgEquiv.symm_apply_apply]
    rw [hσ y hy]
  · intro hτ
    rw [IntermediateField.mem_fixingSubgroup_iff] at hτ
    let σ := (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)).symm τ
    refine ⟨σ, ?_,
      (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)).apply_symm_apply τ⟩
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro x hx
    apply (candidateGenusFieldEquivAdjoinRelative hd).injective
    have hmap : candidateGenusFieldEquivAdjoinRelative hd x ∈
        candidateGenusFieldBaseAdjoin hd := by
      rw [candidateGenusFieldBaseAdjoin, IntermediateField.mem_map]
      exact ⟨x, hx, rfl⟩
    -- Unfold the inverse `autCongr` at the transported point; the following inverse-law rewrite
    -- then removes the presentation equivalence without unfolding any field definitions.
    change candidateGenusFieldEquivAdjoinRelative hd
      ((candidateGenusFieldEquivAdjoinRelative hd).symm
        (τ (candidateGenusFieldEquivAdjoinRelative hd x))) =
          candidateGenusFieldEquivAdjoinRelative hd x
    rw [(candidateGenusFieldEquivAdjoinRelative hd).apply_symm_apply, hτ _ hmap]

private noncomputable def candidateGenusFieldRelativeAutCongr {d : ℤ} (hd : Squarefree d) :
    (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) ≃*
      (adjoin ℚ (Set.range (genusFieldRoot hd))
        ≃ₐ[candidateGenusFieldBaseAdjoin hd] adjoin ℚ (Set.range (genusFieldRoot hd))) :=
  (IntermediateField.fixingSubgroupEquiv (candidateGenusFieldBase hd)).symm.trans
    (((AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)).subgroupMap
      (candidateGenusFieldBase hd).fixingSubgroup).trans
        ((MulEquiv.subgroupCongr (candidateGenusField_map_fixingSubgroup hd)).trans
          (IntermediateField.fixingSubgroupEquiv (candidateGenusFieldBaseAdjoin hd))))

@[simp] private theorem candidateGenusFieldRelativeAutCongr_apply {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd)
    (x : candidateGenusField hd) :
    candidateGenusFieldRelativeAutCongr hd σ
        (candidateGenusFieldEquivAdjoinRelative hd x) =
      candidateGenusFieldEquivAdjoinRelative hd (σ x) := by
  -- The subgroup equivalences only change the bundled scalar field. Their underlying map is
  -- `autCongr` applied to `σ.restrictScalars ℚ`, exposed here by definitional reduction.
  change (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)
    (σ.restrictScalars ℚ)) (candidateGenusFieldEquivAdjoinRelative hd x) = _
  simp only [AlgEquiv.autCongr_apply, AlgEquiv.trans_apply, AlgEquiv.symm_apply_apply]
  rfl

private theorem candidateGenusFieldRelativeSignSubmodule_eq_intermediateFieldSubmodule
    {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldRelativeSignSubmodule hd =
      (intermediateFieldEquivSubmodule (genusFieldRoot_sq_algebraMap hd)
        (candidateGenusFieldRoot_independent hd) (candidateGenusFieldBaseAdjoin hd)).ofDual := by
  ext v
  rw [mem_candidateGenusFieldRelativeSignSubmodule_iff,
    mem_intermediateFieldEquivSubmodule_apply_ofDual_iff]
  constructor
  · intro hv
    let σ := (galoisGroupEquiv (genusFieldRoot_sq_algebraMap hd)
      (candidateGenusFieldRoot_independent hd)).symm (Multiplicative.ofAdd v)
    let τ := (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)).symm σ
    have hsign : signPattern (genusFieldRoot hd) σ = v := by
      have h := (galoisGroupEquiv (genusFieldRoot_sq_algebraMap hd)
        (candidateGenusFieldRoot_independent hd)).apply_symm_apply (Multiplicative.ofAdd v)
      rw [galoisGroupEquiv_apply] at h
      exact Multiplicative.ofAdd.injective h
    refine ⟨σ, ?_, hsign⟩
    rw [← candidateGenusField_map_fixingSubgroup hd]
    refine ⟨τ, ?_, ?_⟩
    · apply (candidateGenusField_mem_fixingSubgroup_iff_sum_signPattern_eq_zero hd τ).mpr
      rw [candidateGenusFieldSignPattern_eq_relativePresentation]
      dsimp only [τ]
      rw [(AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)).apply_symm_apply,
        hsign]
      exact hv
    · exact
        (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoinRelative hd)).apply_symm_apply σ
  · rintro ⟨σ, hσ, rfl⟩
    rw [← candidateGenusField_map_fixingSubgroup hd] at hσ
    obtain ⟨τ, hτ, rfl⟩ := hσ
    have hsum :=
      (candidateGenusField_mem_fixingSubgroup_iff_sum_signPattern_eq_zero hd τ).mp hτ
    rwa [candidateGenusFieldSignPattern_eq_relativePresentation] at hsum

/-- The sign pattern of a relative automorphism, obtained by restricting it to an absolute
`ℚ`-automorphism of the candidate genus field. -/
noncomputable def candidateGenusFieldRelativeSignPattern {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2 :=
  candidateGenusFieldSignPattern hd (σ.restrictScalars ℚ)

/-- The relative sign recorded at `P` is zero exactly when the automorphism fixes the corresponding
chosen generator. -/
@[simp] theorem candidateGenusFieldRelativeSignPattern_apply {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldRelativeSignPattern hd σ P =
      if σ (candidateGenusFieldGen hd P) = candidateGenusFieldGen hd P then 0 else 1 := by
  exact candidateGenusFieldSignPattern_apply hd (σ.restrictScalars ℚ) P

private theorem candidateGenusFieldRelativeSignPattern_eq {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    candidateGenusFieldRelativeSignPattern hd σ =
      signPattern (genusFieldRoot hd)
        ((candidateGenusFieldRelativeAutCongr hd σ).restrictScalars ℚ) := by
  rw [candidateGenusFieldRelativeSignPattern,
    candidateGenusFieldSignPattern_eq_relativePresentation]
  congr 1

/-- The sign pattern of a relative automorphism lies in the relative sign subspace. -/
theorem candidateGenusFieldRelativeSignPattern_mem {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    candidateGenusFieldRelativeSignPattern hd σ ∈
    candidateGenusFieldRelativeSignSubmodule hd := by
  rw [candidateGenusFieldRelativeSignSubmodule_eq_intermediateFieldSubmodule,
    candidateGenusFieldRelativeSignPattern_eq]
  exact signPattern_restrictScalars_mem (genusFieldRoot_sq_algebraMap hd)
    (candidateGenusFieldRoot_independent hd) (candidateGenusFieldBaseAdjoin hd)
      (candidateGenusFieldRelativeAutCongr hd σ)

/-- **The relative Galois group of the candidate genus field is its base-fixing sign subspace.**
Restriction of a relative automorphism to `ℚ`, followed by the absolute sign-pattern equivalence,
identifies `Gal(candidateGenusField hd / candidateGenusFieldBase hd)` with the multiplicative form
of `candidateGenusFieldRelativeSignSubmodule hd`. -/
noncomputable def galoisGroupEquivCandidateGenusFieldRelative {d : ℤ} (hd : Squarefree d) :
    (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) ≃*
      Multiplicative ↥(candidateGenusFieldRelativeSignSubmodule hd) :=
  (candidateGenusFieldRelativeAutCongr hd).trans
    ((galoisGroupEquivIntermediateFieldSubmodule
      (genusFieldRoot_sq_algebraMap hd)
      (candidateGenusFieldRoot_independent hd) (candidateGenusFieldBaseAdjoin hd)).trans
      ((LinearEquiv.ofEq _ _
        (candidateGenusFieldRelativeSignSubmodule_eq_intermediateFieldSubmodule hd).symm).toAddEquiv
          |>.toMultiplicative))

/-- The relative Galois equivalence sends an automorphism to the sign pattern of its restriction
to an absolute `ℚ`-automorphism. -/
@[simp] theorem galoisGroupEquivCandidateGenusFieldRelative_apply {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    galoisGroupEquivCandidateGenusFieldRelative hd σ =
      Multiplicative.ofAdd
        ⟨candidateGenusFieldRelativeSignPattern hd σ,
          candidateGenusFieldRelativeSignPattern_mem hd σ⟩ := by
  rw [galoisGroupEquivCandidateGenusFieldRelative, MulEquiv.trans_apply,
    MulEquiv.trans_apply, galoisGroupEquivIntermediateFieldSubmodule_apply]
  apply Subtype.ext
  exact (candidateGenusFieldRelativeSignPattern_eq hd σ).symm

/-- The inverse relative Galois equivalence realizes a base-fixing sign vector by its prescribed
sign changes on the chosen prime-discriminant generators. -/
@[simp] theorem galoisGroupEquivCandidateGenusFieldRelative_symm_apply_gen {d : ℤ}
    (hd : Squarefree d) (v : candidateGenusFieldRelativeSignSubmodule hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    ((galoisGroupEquivCandidateGenusFieldRelative hd).symm (Multiplicative.ofAdd v))
        (candidateGenusFieldGen hd P) =
      (-1) ^ ((v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) P).val *
        candidateGenusFieldGen hd P := by
  let v' : (intermediateFieldEquivSubmodule (genusFieldRoot_sq_algebraMap hd)
      (candidateGenusFieldRoot_independent hd) (candidateGenusFieldBaseAdjoin hd)).ofDual :=
    ⟨v, by
      rw [← candidateGenusFieldRelativeSignSubmodule_eq_intermediateFieldSubmodule hd]
      exact v.property⟩
  let τ := (galoisGroupEquivIntermediateFieldSubmodule
    (genusFieldRoot_sq_algebraMap hd) (candidateGenusFieldRoot_independent hd)
      (candidateGenusFieldBaseAdjoin hd)).symm (Multiplicative.ofAdd v')
  let σ := (candidateGenusFieldRelativeAutCongr hd).symm τ
  -- Unfold the two local names and the inverse of the composed relative equivalence so that the
  -- goal states the action of the concrete relative automorphism `σ` on the chosen generator.
  change σ (candidateGenusFieldGen hd P) = _
  apply (candidateGenusFieldEquivAdjoinRelative hd).injective
  rw [← candidateGenusFieldRelativeAutCongr_apply hd σ,
    (candidateGenusFieldRelativeAutCongr hd).apply_symm_apply τ]
  simp only [candidateGenusFieldEquivAdjoinRelative_apply_gen, map_mul, map_pow, map_neg, map_one]
  exact galoisGroupEquivIntermediateFieldSubmodule_symm_apply_gen
    (genusFieldRoot_sq_algebraMap hd) (candidateGenusFieldRoot_independent hd)
      (candidateGenusFieldBaseAdjoin hd) v' P

/-- **Order of the relative candidate-genus-field Galois group.** If the squarefree integer `d`
is not a rational square, the relative group over its embedded quadratic base has order
`2 ^ (t - 1)`, where `t = (genusPrimeDiscriminants hd).card`. -/
theorem card_aut_candidateGenusField_over_base {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare (((d : ℤ) : ℚ))) :
    Nat.card
        (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) =
      2 ^ ((genusPrimeDiscriminants hd).card - 1) := by
  rw [IsGalois.card_aut_eq_finrank,
    finrank_candidateGenusField_over_candidateGenusFieldBase hd hnsq]

end TauCeti.Multiquadratic
