/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Real.FixedField
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.OrdinaryClassGroup
import TauCeti.Algebra.Module.ZMod.SpanSingleton
import TauCeti.GroupTheory.QuotientGroup.KerEquiv

/-!
# The real genus-field Galois group

For a positive squarefree nonsquare integer `d`, let `K = ℚ(√d)` be the quadratic subfield of
the prime-discriminant compositum and let `K_gen` be its maximal totally real subfield. This file
proves the ordinary real genus-field isomorphism

`Gal(K_gen / K) ≅ Cl(K) / Cl(K)²`.

Restriction from the full prime-discriminant compositum to `K_gen` is surjective. Its kernel is
generated by complex conjugation, whose sign vector is supported exactly at the negative prime
discriminants. On the class-group side, passing from narrow to ordinary classes kills exactly the
line generated by the same vector. The two quotient maps therefore have the same kernel, and the
first isomorphism theorem identifies their targets.

The description is classical; see F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*,
§2.2, and D. A. Cox, *Primes of the Form x² + ny²*, §6.A.

## Main definitions and results

* `candidateGenusFieldRestrictionToReal`: restriction from the full relative Galois group to the
  real candidate, computed by `coe_candidateGenusFieldRestrictionToReal_apply`.
* `candidateGenusFieldRealIsScalarTower` and
  `isAbelianGalois_candidateGenusFieldReal_over_base`: the scalar-tower and Galois instances for
  the real candidate over the embedded quadratic base.
* `ker_candidateGenusFieldRestrictionToReal`: its kernel is the sign-space line supported at the
  negative prime discriminants.
* `autCandidateGenusFieldRealEquivElementaryTwoQuotient`: the ordinary real genus-field
  isomorphism.
-/

public section

open IntermediateField NumberField

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- The algebra structure on the real candidate induced by the inclusion of the embedded
quadratic base. Positivity is exactly what puts that base inside the maximal real subfield. -/
@[instance_reducible]
noncomputable def candidateGenusFieldRealAlgebra (hd : Squarefree d)
    (hpos : 0 < d) : Algebra (candidateGenusFieldBase hd) (candidateGenusFieldReal hd) :=
  (IntermediateField.inclusion
    (candidateGenusFieldBase_le_candidateGenusFieldReal hd hpos)).toAlgebra

/-- The inclusions of the quadratic base into the real candidate and then into the full candidate
form a scalar tower. -/
noncomputable instance candidateGenusFieldRealIsScalarTower (hd : Squarefree d)
    (hpos : 0 < d) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    IsScalarTower (candidateGenusFieldBase hd) (candidateGenusFieldReal hd)
      (candidateGenusField hd) := by
  let _ := candidateGenusFieldRealAlgebra hd hpos
  exact IsScalarTower.of_algebraMap_eq fun _ => rfl

/-- The real candidate is abelian Galois over the embedded quadratic base. -/
noncomputable instance isAbelianGalois_candidateGenusFieldReal_over_base (hd : Squarefree d)
    (hpos : 0 < d) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    IsAbelianGalois (candidateGenusFieldBase hd) (candidateGenusFieldReal hd) := by
  let _ := candidateGenusFieldRealAlgebra hd hpos
  let _ := candidateGenusFieldRealIsScalarTower hd hpos
  exact IsAbelianGalois.tower_bot (candidateGenusFieldBase hd) (candidateGenusFieldReal hd)
    (candidateGenusField hd)

/-- Restriction from the full candidate genus field over its quadratic base to the maximal totally
real subfield. The latter contains the base when `d > 0`, and normality makes restriction
surjective. -/
noncomputable def candidateGenusFieldRestrictionToReal (hd : Squarefree d) (hpos : 0 < d) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) →*
      (candidateGenusFieldReal hd ≃ₐ[candidateGenusFieldBase hd]
        candidateGenusFieldReal hd) := by
  letI := candidateGenusFieldRealAlgebra hd hpos
  letI := candidateGenusFieldRealIsScalarTower hd hpos
  letI := isAbelianGalois_candidateGenusFieldReal_over_base hd hpos
  exact AlgEquiv.restrictNormalHom (F := candidateGenusFieldBase hd)
    (K₁ := candidateGenusField hd) (candidateGenusFieldReal hd)

/-- **Restriction to the real candidate acts by the ambient automorphism.** Read inside the full
candidate genus field, the restriction of `σ` sends `x` to `σ x`. -/
@[simp] theorem coe_candidateGenusFieldRestrictionToReal_apply (hd : Squarefree d) (hpos : 0 < d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd)
    (x : candidateGenusFieldReal hd) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    ((candidateGenusFieldRestrictionToReal hd hpos σ x : candidateGenusFieldReal hd) :
        candidateGenusField hd) = σ (x : candidateGenusField hd) := by
  let _ := candidateGenusFieldRealAlgebra hd hpos
  let _ := candidateGenusFieldRealIsScalarTower hd hpos
  let _ := isAbelianGalois_candidateGenusFieldReal_over_base hd hpos
  exact AlgEquiv.restrictNormal_commutes σ (candidateGenusFieldReal hd) x

/-- Restriction to the real candidate is surjective. -/
theorem candidateGenusFieldRestrictionToReal_surjective (hd : Squarefree d) (hpos : 0 < d) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    Function.Surjective (candidateGenusFieldRestrictionToReal hd hpos) := by
  let _ := candidateGenusFieldRealAlgebra hd hpos
  let _ := candidateGenusFieldRealIsScalarTower hd hpos
  let _ := isAbelianGalois_candidateGenusFieldReal_over_base hd hpos
  exact AlgEquiv.restrictNormalHom_surjective (F := candidateGenusFieldBase hd)
    (K₁ := candidateGenusFieldReal hd) (candidateGenusField hd)

private theorem candidateGenusFieldRestrictionToReal_eq_one_iff (hd : Squarefree d)
    (hpos : 0 < d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    candidateGenusFieldRestrictionToReal hd hpos σ = 1 ↔
      σ.restrictScalars ℚ ∈ Subgroup.zpowers (candidateGenusFieldConj hd) := by
  let _ := candidateGenusFieldRealAlgebra hd hpos
  rw [← fixingSubgroup_candidateGenusFieldReal hd,
    IntermediateField.mem_fixingSubgroup_iff]
  constructor
  · intro h x hx
    have hx' := DFunLike.congr_fun h (⟨x, hx⟩ : candidateGenusFieldReal hd)
    exact (coe_candidateGenusFieldRestrictionToReal_apply hd hpos σ ⟨x, hx⟩).symm.trans
      (congrArg Subtype.val hx')
  · intro h
    apply AlgEquiv.ext
    intro x
    apply Subtype.ext
    exact (coe_candidateGenusFieldRestrictionToReal_apply hd hpos σ x).trans (h x x.property)

private theorem candidateGenusFieldRelativeSignPattern_mem_negativeSpan_iff
    (hd : Squarefree d) (hpos : 0 < d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    (⟨candidateGenusFieldRelativeSignPattern hd σ,
        candidateGenusFieldRelativeSignPattern_mem hd σ⟩ :
      candidateGenusFieldRelativeSignSubmodule hd) ∈
        ZMod 2 ∙
          (⟨candidateGenusFieldNegativeSign hd,
            candidateGenusFieldNegativeSign_mem hd hpos⟩ :
              candidateGenusFieldRelativeSignSubmodule hd) ↔
      σ.restrictScalars ℚ ∈ Subgroup.zpowers (candidateGenusFieldConj hd) := by
  let e := galoisGroupEquivCandidateGenusField hd
  let v : candidateGenusFieldRelativeSignSubmodule hd :=
    ⟨candidateGenusFieldRelativeSignPattern hd σ,
      candidateGenusFieldRelativeSignPattern_mem hd σ⟩
  let z : candidateGenusFieldRelativeSignSubmodule hd :=
    ⟨candidateGenusFieldNegativeSign hd,
      candidateGenusFieldNegativeSign_mem hd hpos⟩
  have heσ : e (σ.restrictScalars ℚ) =
      Multiplicative.ofAdd (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) := by
    rw [galoisGroupEquivCandidateGenusField_apply]
    apply congrArg Multiplicative.ofAdd
    funext P
    simp only [v]
    rw [candidateGenusFieldSignPattern_apply,
      candidateGenusFieldRelativeSignPattern_apply,
      AlgEquiv.restrictScalars_apply]
  have hec : e (candidateGenusFieldConj hd) =
      Multiplicative.ofAdd (z : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) := by
    rw [galoisGroupEquivCandidateGenusField_apply]
    apply congrArg Multiplicative.ofAdd
    funext P
    simpa only [z, candidateGenusFieldNegativeSign_apply] using
      candidateGenusFieldSignPattern_conj_apply hd P
  -- Fold the proof-carrying sign vectors to compare their underlying coordinate functions.
  rw [show (⟨candidateGenusFieldRelativeSignPattern hd σ,
      candidateGenusFieldRelativeSignPattern_mem hd σ⟩ :
        candidateGenusFieldRelativeSignSubmodule hd) = v from rfl]
  rw [show (⟨candidateGenusFieldNegativeSign hd,
      candidateGenusFieldNegativeSign_mem hd hpos⟩ :
        candidateGenusFieldRelativeSignSubmodule hd) = z from rfl]
  have hvspan : v ∈ ZMod 2 ∙ z ↔
      (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) ∈
        ZMod 2 ∙ (z : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) := by
    simp only [Submodule.mem_span_singleton]
    constructor
    · rintro ⟨a, ha⟩
      exact ⟨a, congrArg Subtype.val ha⟩
    · rintro ⟨a, ha⟩
      exact ⟨a, Subtype.ext ha⟩
  rw [hvspan]
  -- The cyclic subgroup lives on the multiplicative form of the ambient coordinate space.
  change (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) ∈
      (ZMod 2 ∙ (z : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2)).toAddSubgroup ↔ _
  rw [← toAddSubgroup'_zpowers_ofAdd_eq_span (n := 2)
      (V := {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) (z : _ → ZMod 2),
    Subgroup.mem_toAddSubgroup', ← heσ, ← hec]
  simp only [Subgroup.mem_zpowers_iff]
  constructor
  · rintro ⟨n, hn⟩
    refine ⟨n, e.injective ?_⟩
    simpa only [map_zpow] using hn
  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa only [map_zpow] using congrArg e hn

/-- The homomorphism from the full relative Galois group to the ordinary elementary-`2`
class-group quotient. It sends the sign pattern of an automorphism through the ordinary
class-group sign map. -/
noncomputable def candidateGenusFieldOrdinaryClassGroupHom (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) →*
      Multiplicative
        (TauCeti.ClassGroup.ElementaryTwoQuotient (𝓞 (candidateGenusFieldBase hd))) :=
  (candidateGenusFieldOrdinaryClassGroupSignMap hd hnsq).toAddMonoidHom.toMultiplicative.comp
    (galoisGroupEquivCandidateGenusFieldRelative hd).toMonoidHom

/-- The ordinary class-group homomorphism sends an automorphism to the image of its sign
pattern. -/
@[simp] theorem candidateGenusFieldOrdinaryClassGroupHom_apply (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    candidateGenusFieldOrdinaryClassGroupHom hd hnsq σ =
      Multiplicative.ofAdd
        (candidateGenusFieldOrdinaryClassGroupSignMap hd hnsq
          ⟨candidateGenusFieldRelativeSignPattern hd σ,
            candidateGenusFieldRelativeSignPattern_mem hd σ⟩) := by
  rw [candidateGenusFieldOrdinaryClassGroupHom, MonoidHom.comp_apply,
    -- Expose the bundled equivalence as its underlying monoid homomorphism for rewriting.
    show (galoisGroupEquivCandidateGenusFieldRelative hd).toMonoidHom σ =
      galoisGroupEquivCandidateGenusFieldRelative hd σ from rfl,
    galoisGroupEquivCandidateGenusFieldRelative_apply]
  rfl

/-- The homomorphism from the full relative Galois group to the ordinary elementary-`2`
class-group quotient is surjective. -/
theorem candidateGenusFieldOrdinaryClassGroupHom_surjective (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    Function.Surjective (candidateGenusFieldOrdinaryClassGroupHom hd hnsq) :=
  (candidateGenusFieldOrdinaryClassGroupSignMap_surjective hd hnsq).comp
    (galoisGroupEquivCandidateGenusFieldRelative hd).surjective

/-- **The field-side and class-side quotient maps have the same kernel.** Restriction to the
maximal totally real subfield kills complex conjugation; in sign coordinates this is precisely
the line supported at the negative prime discriminants, which is also the kernel of the map from
narrow to ordinary ideal classes modulo squares. -/
theorem ker_candidateGenusFieldRestrictionToReal (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) (hpos : 0 < d) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    (candidateGenusFieldRestrictionToReal hd hpos).ker =
      (candidateGenusFieldOrdinaryClassGroupHom hd hnsq).ker := by
  let _ := candidateGenusFieldRealAlgebra hd hpos
  ext σ
  rw [MonoidHom.mem_ker, MonoidHom.mem_ker,
    candidateGenusFieldOrdinaryClassGroupHom_apply]
  -- Remove the multiplicative type tag so the linear-map kernel theorem applies.
  change candidateGenusFieldRestrictionToReal hd hpos σ = 1 ↔
    candidateGenusFieldOrdinaryClassGroupSignMap hd hnsq
      ⟨candidateGenusFieldRelativeSignPattern hd σ,
        candidateGenusFieldRelativeSignPattern_mem hd σ⟩ = 0
  rw [← LinearMap.mem_ker, ker_candidateGenusFieldOrdinaryClassGroupSignMap hd hnsq hpos,
    candidateGenusFieldRelativeSignPattern_mem_negativeSpan_iff hd hpos,
    candidateGenusFieldRestrictionToReal_eq_one_iff hd hpos]

/-- **The ordinary real genus-field isomorphism.** For positive squarefree nonsquare `d`, the
Galois group of the maximal totally real subfield of the prime-discriminant compositum over its
quadratic base is isomorphic to `Cl(ℚ(√d)) / Cl(ℚ(√d))²`.

The isomorphism is characterized by lifting an automorphism to the full candidate genus field,
reading its prime-discriminant sign vector, and applying the ordinary class-group sign map. -/
noncomputable def autCandidateGenusFieldRealEquivElementaryTwoQuotient
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) (hpos : 0 < d) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    (candidateGenusFieldReal hd ≃ₐ[candidateGenusFieldBase hd]
      candidateGenusFieldReal hd) ≃*
        Multiplicative
          (TauCeti.ClassGroup.ElementaryTwoQuotient
            (𝓞 (candidateGenusFieldBase hd))) := by
  letI := candidateGenusFieldRealAlgebra hd hpos
  exact
    (QuotientGroup.quotientKerEquivOfSurjective
      (candidateGenusFieldRestrictionToReal hd hpos)
      (candidateGenusFieldRestrictionToReal_surjective hd hpos)).symm |>.trans
    ((QuotientGroup.quotientMulEquivOfEq
      (ker_candidateGenusFieldRestrictionToReal hd hnsq hpos)).trans
    (QuotientGroup.quotientKerEquivOfSurjective
      (candidateGenusFieldOrdinaryClassGroupHom hd hnsq)
      (candidateGenusFieldOrdinaryClassGroupHom_surjective hd hnsq)))

/-- The ordinary real genus-field isomorphism carries a restricted automorphism to the ordinary
class-group image of its sign vector. This makes the isomorphism independent of the chosen lift. -/
@[simp] theorem autCandidateGenusFieldRealEquivElementaryTwoQuotient_apply_restrict
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) (hpos : 0 < d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    letI := candidateGenusFieldRealAlgebra hd hpos
    autCandidateGenusFieldRealEquivElementaryTwoQuotient hd hnsq hpos
        (candidateGenusFieldRestrictionToReal hd hpos σ) =
      candidateGenusFieldOrdinaryClassGroupHom hd hnsq σ := by
  let _ := candidateGenusFieldRealAlgebra hd hpos
  let e := QuotientGroup.quotientKerEquivOfSurjective
    (candidateGenusFieldRestrictionToReal hd hpos)
    (candidateGenusFieldRestrictionToReal_surjective hd hpos)
  have hfirst : e.symm (candidateGenusFieldRestrictionToReal hd hpos σ) =
      QuotientGroup.mk σ := by
    apply e.injective
    rw [e.apply_symm_apply]
    exact TauCeti.QuotientGroup.quotientKerEquivOfSurjective_apply_mk
      (candidateGenusFieldRestrictionToReal hd hpos)
      (candidateGenusFieldRestrictionToReal_surjective hd hpos) σ
  rw [autCandidateGenusFieldRealEquivElementaryTwoQuotient]
  simp only [MulEquiv.trans_apply]
  -- The first-isomorphism equivalence is opaque, so use the computation proved above.
  rw [show (QuotientGroup.quotientKerEquivOfSurjective
      (candidateGenusFieldRestrictionToReal hd hpos)
      (candidateGenusFieldRestrictionToReal_surjective hd hpos)).symm
        (candidateGenusFieldRestrictionToReal hd hpos σ) = QuotientGroup.mk σ from hfirst,
    QuotientGroup.quotientMulEquivOfEq_mk,
    TauCeti.QuotientGroup.quotientKerEquivOfSurjective_apply_mk]

end TauCeti.Multiquadratic
