/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Exponent
public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Order.Zorn

/-!
# The index-`p` subgroups of an abelian group of exponent `p` separate its points

An abelian group `G` all of whose elements satisfy `g ^ p = 1`, for a prime `p`, is an elementary
abelian `p`-group, that is an `𝔽_p`-vector space written multiplicatively. Its subgroups of index
`p` are the hyperplanes, and the point of this file is that they **separate points**: every
`σ ≠ 1` is avoided by some index-`p` subgroup, equivalently the intersection of all of them — the
Frattini subgroup — is trivial.

The proof avoids setting up the vector-space structure. By Zorn's lemma, take `H` maximal among
the subgroups not containing `σ`. For `b ∉ H` the subgroup `H ⊔ ⟨b⟩` is strictly larger, so by
maximality it contains `σ`; as `G` is commutative this reads `σ = h * b ^ n` with `h ∈ H`, so the
class of `σ` lies in the cyclic group generated by the class of `b` in `G ⧸ H`. That cyclic group
has prime order `p`, and in a group of prime order every nontrivial element is a generator, so the
class of `b` lies in turn in the group generated by the class of `σ`. Hence `G ⧸ H` is generated
by the class of `σ`, an element of order `p`, and `H` has index `p`.

Commutativity is a genuine hypothesis for odd `p` — a group of exponent `3` need not be abelian —
but for `p = 2` it is automatic (`Commute.of_orderOf_dvd_two`), which is how the exponent-two
corollary below drops it.

## Main results

* `TauCeti.zpowers_eq_zpowers_of_mem_zpowers`: a nontrivial element of the cyclic subgroup
  generated by an element of prime order generates that subgroup.
* `TauCeti.exists_index_eq_notMem_of_exponent_dvd`: in a commutative group of exponent dividing a
  prime `p`, every `σ ≠ 1` lies outside some subgroup of index `p`.
* `TauCeti.exists_index_eq_two_notMem_of_exponent_dvd_two`: the case `p = 2`, where commutativity
  is automatic.
-/

public section

namespace TauCeti

variable {G : Type*} [Group G] {p : ℕ}

/-- If `y ^ p = 1` for a prime `p`, then every nontrivial element `z` of the cyclic subgroup
generated by `y` generates that subgroup: `⟨y⟩` has order `p`, and a group of prime order is
generated by each of its nontrivial elements. -/
theorem zpowers_eq_zpowers_of_mem_zpowers (hp : p.Prime) {y z : G} (hpow : y ^ p = 1)
    (hz : z ≠ 1) (hzy : z ∈ Subgroup.zpowers y) :
    Subgroup.zpowers z = Subgroup.zpowers y := by
  have : Fact p.Prime := ⟨hp⟩
  have hy : y ≠ 1 := by
    rintro rfl
    rw [Subgroup.zpowers_one_eq_bot, Subgroup.mem_bot] at hzy
    exact hz hzy
  have hcard : Nat.card (Subgroup.zpowers y) = p := by
    rw [Nat.card_zpowers]
    exact orderOf_eq_prime hpow hy
  have hz' : (⟨z, hzy⟩ : Subgroup.zpowers y) ≠ 1 := by simpa [Subtype.ext_iff] using hz
  refine le_antisymm (Subgroup.zpowers_le.mpr hzy) (Subgroup.zpowers_le.mpr ?_)
  obtain ⟨n, hn⟩ := mem_zpowers_of_prime_card
    (g' := (⟨y, Subgroup.mem_zpowers y⟩ : Subgroup.zpowers y)) hcard hz'
  exact ⟨n, congrArg Subtype.val hn⟩

/-- **Index-`p` subgroups separate the points of an abelian group of exponent `p`.** In a
commutative group all of whose elements satisfy `g ^ p = 1`, for `p` prime, every `σ ≠ 1` lies
outside some subgroup of index `p`.

Equivalently: the intersection of the index-`p` subgroups — the Frattini subgroup of an elementary
abelian `p`-group — is trivial. -/
theorem exists_index_eq_notMem_of_exponent_dvd [IsMulCommutative G] (hp : p.Prime)
    (hexp : Monoid.exponent G ∣ p) {σ : G} (hσ : σ ≠ 1) :
    ∃ H : Subgroup G, H.index = p ∧ σ ∉ H := by
  classical
  have : Fact p.Prime := ⟨hp⟩
  have hpow : ∀ g : G, g ^ p = 1 := Monoid.exponent_dvd_iff_forall_pow_eq_one.mp hexp
  -- Choose a subgroup maximal among those avoiding `σ`; the trivial subgroup is one such.
  obtain ⟨H, hHσ, hmax⟩ :=
    zorn_le₀ {H : Subgroup G | σ ∉ H} fun c hcσ hchain => by
      refine ⟨sSup c, ?_, fun K hK => le_sSup hK⟩
      by_cases hc : c.Nonempty
      · intro hσsup
        obtain ⟨K, hKc, hσK⟩ :=
          (Subgroup.mem_sSup_of_directedOn hc hchain.directedOn).mp hσsup
        exact hcσ hKc hσK
      · rw [Set.not_nonempty_iff_eq_empty.mp hc, sSup_empty]
        simpa using hσ
  refine ⟨H, ?_, hHσ⟩
  set q : G →* G ⧸ H := QuotientGroup.mk' H
  have hσq : q σ ≠ 1 := fun h => hHσ ((QuotientGroup.eq_one_iff σ).mp h)
  have hpowq : ∀ x : G ⧸ H, x ^ p = 1 := by
    rintro x
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective H x
    rw [← map_pow, hpow g, map_one]
  -- The class of `σ` generates `G ⧸ H`, because a nontrivial cyclic group of exponent `p` is
  -- generated by each of its nontrivial elements.
  have htop : Subgroup.zpowers (q σ) = ⊤ := by
    refine eq_top_iff.mpr fun x _ => ?_
    obtain ⟨b, rfl⟩ := QuotientGroup.mk'_surjective H x
    by_cases hb : b ∈ H
    · have hb1 : q b = 1 := (QuotientGroup.eq_one_iff b).mpr hb
      rw [hb1]
      exact one_mem _
    -- `H ⊔ ⟨b⟩` is strictly bigger than `H`, hence contains `σ` by maximality.
    have hσmem : σ ∈ H ⊔ Subgroup.closure {b} := by
      have hlt : H < H ⊔ Subgroup.closure {b} :=
        lt_of_le_of_ne le_sup_left fun heq =>
          hb (heq ▸ Subgroup.mem_sup_right (Subgroup.subset_closure rfl))
      by_contra hcon
      exact absurd (hmax hcon le_sup_left) (not_le_of_gt hlt)
    -- Read off `σ = h * b ^ n`, so the class of `σ` lies in the cyclic group generated by `q b`.
    have hσzp : q σ ∈ Subgroup.zpowers (q b) := by
      rw [← SetLike.mem_coe, Subgroup.mul_normal, Set.mem_mul] at hσmem
      obtain ⟨h, hh, m, hm, hσeq⟩ := hσmem
      obtain ⟨n, rfl⟩ := Subgroup.mem_closure_singleton.mp hm
      have hh1 : q h = 1 := (QuotientGroup.eq_one_iff h).mpr hh
      exact ⟨n, by rw [← hσeq, map_mul, hh1, one_mul, map_zpow]⟩
    -- `⟨q b⟩` has prime order, so its nontrivial element `q σ` generates it, and `q b ∈ ⟨q σ⟩`.
    rw [zpowers_eq_zpowers_of_mem_zpowers hp (hpowq (q b)) hσq hσzp]
    exact Subgroup.mem_zpowers (q b)
  rw [Subgroup.index_eq_card, ← orderOf_eq_card_of_zpowers_eq_top htop]
  exact orderOf_eq_prime (hpowq _) hσq

/-- **Index-two subgroups separate the points of a group of exponent two.** In a group all of whose
elements square to `1`, every `σ ≠ 1` lies outside some subgroup of index `2`.

This is the case `p = 2` of `TauCeti.exists_index_eq_notMem_of_exponent_dvd`, where commutativity
is not an extra hypothesis: a group of exponent two is automatically abelian. -/
theorem exists_index_eq_two_notMem_of_exponent_dvd_two (hexp : Monoid.exponent G ∣ 2)
    {σ : G} (hσ : σ ≠ 1) :
    ∃ H : Subgroup G, H.index = 2 ∧ σ ∉ H :=
  have : IsMulCommutative G :=
    IsMulCommutative.of_comm <| Commute.of_orderOf_dvd_two fun g =>
      orderOf_dvd_of_pow_eq_one (Monoid.exponent_dvd_iff_forall_pow_eq_one.mp hexp g)
  exists_index_eq_notMem_of_exponent_dvd Nat.prime_two hexp hσ

end TauCeti
