/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.SetTheory.Cardinal.NatCard
public import TauCeti.GroupTheory.Perm.Partition
import Mathlib.Logic.Equiv.Option

/-!
# The number of orbits of a permutation

A permutation `σ` of a type `α` partitions `α` into the classes of `Equiv.Perm.SameCycle σ`.
This file counts them: `TauCeti.orbitCount σ` is the cardinality of that quotient. Unlike
`Equiv.Perm.cycleType`, which records only the cycles of length at least two, every fixed point
of `σ` contributes an orbit of its own here.

The file then proves how the count responds to three ways of changing a permutation: adjoining a
point, splicing a fixed point into another orbit, and merging two orbits. The first two compare a
permutation with one of a *different* type and are stated to allow that; the third compares two
permutations of the same type.

* `TauCeti.orbitCount_conj`: conjugation does not change the number of orbits.
* `Equiv.Perm.orbitQuotientEquivCycleFactorsSumFixedPoints`: on a finite type, the orbits are the
  nontrivial cycle factors of the permutation together with its fixed points.
* `Equiv.Perm.orbitCount_eq_card_parts_partition`: on a finite type, the orbit count is the number
  of parts in Mathlib's full, fixed-point-aware permutation partition.
* `TauCeti.orbitCount_eq_one_of_forall_sameCycle`: a transitive permutation of a nonempty type has
  orbit count one.
* `Equiv.Perm.orbitCount_le_card`: on a finite type, a permutation has at most as many orbits as
  the type has points, the orbits being the classes of a partition of it.
* `Equiv.Perm.sign_eq_neg_one_pow_card_sub_orbitCount`: the sign is determined by the parity of
  the number of points minus the number of orbits.
* `TauCeti.orbitCount_add_one_eq_of_semiconj`: if `σ : Equiv.Perm α` is carried by an injection
  `f : α → β` to `τ : Equiv.Perm β`, and `f` misses exactly one point `p` of `β`, then `τ` has one
  orbit more than `σ` — the extra orbit is the fixed point `p`.
* `TauCeti.orbitCount_mul_swap_add_one`: multiplying a permutation by a transposition that moves
  one of its fixed points splices that fixed point into another orbit, so the count drops by one.
* `TauCeti.orbitCount_add_one_of_merge`: if the orbits of `τ` are the orbits of `σ` with the orbit
  of one point and the orbit of another merged, then `τ` has one orbit fewer.

Composing `TauCeti.orbitCount_add_one_eq_of_semiconj` with `TauCeti.orbitCount_mul_swap_add_one`
says that adjoining a point to a permutation and immediately splicing it into an existing orbit
leaves the number of orbits unchanged. That composite is the reason this file exists: it is the
invariance of the number of components of a link under the stabilization move on braids, in
`TauCeti/KnotTheory/Markov.lean`.

## Implementation notes

`orbitCount` is `Nat.card` of a `Quotient`, so it is `0` when the permutation has infinitely many
orbits or no orbits at all. The three orbit-addition and orbit-removal results assume only that the
quotient of the relevant permutation by `Equiv.Perm.SameCycle` is finite; conjugation preserves
the count without any finiteness assumption.

The two cross-type results, `TauCeti.orbitCount_add_one_eq_of_semiconj` and
`TauCeti.orbitCount_mul_swap_add_one`, are deduced from one private lemma,
`orbitCount_add_one_eq_aux`, whose input is a map `F : α → β` carrying the orbits of `σ`
bijectively onto the orbits of `τ` other than a fixed point `p` of `τ`. Its `SameCycle` hypothesis
comes from Mathlib's `Equiv.Perm.sameCycle_extendDomain` for adjoining a point. For splicing a
point into an orbit, a one-step statement is propagated over all integer powers by the private
lemma `sameCycle_zpow_of_forall_sameCycle_apply`. `TauCeti.orbitCount_add_one_of_merge` does not
go through that lemma: it exhibits the orbits of `τ` as the orbits of `σ` with one class removed
and finishes through `Equiv.optionSubtypeNe`.
-/

public section

namespace TauCeti

open Equiv Equiv.Perm

variable {α β : Type*}

/-- The number of orbits of the cyclic group generated by a permutation `σ`, that is, the number
of classes of `Equiv.Perm.SameCycle σ`. Every fixed point of `σ` is an orbit, so on a finite type
this counts the cycles of `σ` *together with* its fixed points, whereas
`Equiv.Perm.cycleType` records only the former. Being a `Nat.card`, it is `0` when there are
infinitely many orbits. -/
noncomputable def orbitCount (σ : Equiv.Perm α) : ℕ :=
  Nat.card (Quotient (Equiv.Perm.SameCycle.setoid σ))

/-- The orbit count is the cardinality of the type of orbits. -/
theorem orbitCount_def (σ : Equiv.Perm α) :
    orbitCount σ = Nat.card (Quotient (Equiv.Perm.SameCycle.setoid σ)) := (rfl)

/-- Each point of `α` is its own orbit under the identity permutation. -/
@[simp]
theorem orbitCount_one : orbitCount (1 : Equiv.Perm α) = Nat.card α := by
  refine (Nat.card_congr (Equiv.ofBijective (Quotient.mk (SameCycle.setoid (1 : Perm α)))
    ⟨fun x y hxy ↦ ?_, Quotient.mk_surjective⟩)).symm
  exact sameCycle_one.mp (Quotient.eq.mp hxy)

/-- A permutation with a single orbit on a nonempty type has orbit count one. -/
theorem orbitCount_eq_one_of_forall_sameCycle [Nonempty α] {σ : Equiv.Perm α}
    (h : ∀ x y, σ.SameCycle x y) : orbitCount σ = 1 := by
  let _ : Nonempty (Quotient (SameCycle.setoid σ)) :=
    ⟨Quotient.mk _ (Classical.choice (inferInstance : Nonempty α))⟩
  let _ : Subsingleton (Quotient (SameCycle.setoid σ)) :=
    ⟨fun q r => Quotient.inductionOn q fun x => Quotient.inductionOn r fun y =>
      Quotient.sound (h x y)⟩
  exact Nat.card_unique

/-- A permutation of a finite type has at most as many orbits as there are points. -/
theorem _root_.Equiv.Perm.orbitCount_le_card [Finite α] (σ : Equiv.Perm α) :
    orbitCount σ ≤ Nat.card α :=
  Nat.card_le_card_of_surjective (Quotient.mk (SameCycle.setoid σ)) Quotient.mk_surjective

/-- Conjugate permutations have the same number of orbits: conjugation by `g` relabels the points
by `g`, hence relabels the orbits. -/
@[simp]
theorem orbitCount_conj (g σ : Equiv.Perm α) : orbitCount (g * σ * g⁻¹) = orbitCount σ := by
  refine (Nat.card_congr (Quotient.congr (ra := SameCycle.setoid σ)
    (rb := SameCycle.setoid (g * σ * g⁻¹)) g fun x y ↦ ?_)).symm
  have h : SameCycle (g * σ * g⁻¹) (g x) (g y) ↔ SameCycle σ x y := by
    rw [sameCycle_conj]
    simp
  exact h.symm

/-- Inverting a permutation does not change its number of orbits. -/
@[simp]
theorem _root_.Equiv.Perm.orbitCount_inv (σ : Equiv.Perm α) : orbitCount σ⁻¹ = orbitCount σ := by
  exact Nat.card_congr (Quotient.congr (ra := SameCycle.setoid σ⁻¹)
    (rb := SameCycle.setoid σ) (Equiv.refl α) fun _ _ ↦ sameCycle_inv)

/-- Transporting a permutation along an equivalence of its underlying type does not change its
number of orbits. -/
@[simp]
theorem _root_.Equiv.orbitCount_permCongr (e : α ≃ β) (σ : Equiv.Perm α) :
    orbitCount (e.permCongr σ) = orbitCount σ := by
  refine (Nat.card_congr (Quotient.congr (ra := SameCycle.setoid σ)
    (rb := SameCycle.setoid (e.permCongr σ)) e fun x y ↦ ?_)).symm
  constructor
  · rintro ⟨i, hi⟩
    refine ⟨i, ?_⟩
    have hz : e.permCongr (σ ^ i) = (e.permCongr σ) ^ i := by
      simpa only [Equiv.permCongrHom_coe] using map_zpow e.permCongrHom σ i
    rw [← hz, Equiv.permCongr_apply, Equiv.symm_apply_apply, hi]
  · rintro ⟨i, hi⟩
    refine ⟨i, e.injective ?_⟩
    have hz : e.permCongr (σ ^ i) = (e.permCongr σ) ^ i := by
      simpa only [Equiv.permCongrHom_coe] using map_zpow e.permCongrHom σ i
    rw [← hz, Equiv.permCongr_apply, Equiv.symm_apply_apply] at hi
    exact hi

section Finite

variable [Fintype α] [DecidableEq α]

/-- The orbits of a permutation are its nontrivial cycle factors together with its fixed points.
This is the set-level decomposition underlying the full cycle partition: a nontrivial orbit is
sent to the unique member of `cycleFactorsFinset`, while a singleton orbit is sent to its fixed
point. -/
noncomputable def _root_.Equiv.Perm.orbitQuotientEquivCycleFactorsSumFixedPoints
    (σ : Equiv.Perm α) :
    Quotient (Equiv.Perm.SameCycle.setoid σ) ≃
      σ.cycleFactorsFinset ⊕ {x : α // σ x = x} := by
  classical
  let toCycleOrFixed (x : α) : σ.cycleFactorsFinset ⊕ {x : α // σ x = x} :=
    if hx : σ x = x then Sum.inr ⟨x, hx⟩
    else Sum.inl ⟨σ.cycleOf x, Equiv.Perm.cycleOf_mem_cycleFactorsFinset_iff.mpr
      (Equiv.Perm.mem_support.mpr hx)⟩
  let forward : Quotient (Equiv.Perm.SameCycle.setoid σ) →
      σ.cycleFactorsFinset ⊕ {x : α // σ x = x} :=
    Quotient.lift toCycleOrFixed fun x y hxy ↦ by
      have hfixed : σ x = x ↔ σ y = y :=
        Equiv.Perm.SameCycle.apply_eq_self_iff hxy
      by_cases hx : σ x = x
      · have hy : σ y = y := hfixed.mp hx
        simp only [toCycleOrFixed, hx, hy, ↓reduceDIte]
        exact congrArg Sum.inr (Subtype.ext (hxy.eq_of_left hx))
      · have hy : σ y ≠ y := mt hfixed.mpr hx
        simp only [toCycleOrFixed, hx, hy, ↓reduceDIte]
        exact congrArg Sum.inl (Subtype.ext hxy.cycleOf_eq)
  let backward : σ.cycleFactorsFinset ⊕ {x : α // σ x = x} →
      Quotient (Equiv.Perm.SameCycle.setoid σ)
    | Sum.inl c => Quotient.mk _ (Classical.choose
        (Equiv.Perm.IsCycle.nonempty_support
          (Equiv.Perm.mem_cycleFactorsFinset_iff.mp c.property).1))
    | Sum.inr x => Quotient.mk _ x.1
  refine
    { toFun := forward
      invFun := backward
      left_inv := ?_
      right_inv := ?_ }
  · intro q
    induction q using Quotient.ind with
    | _ x =>
      simp only [forward, Quotient.lift_mk, backward, toCycleOrFixed]
      split_ifs with hx
      · rfl
      · apply Quotient.sound
        exact ((Equiv.Perm.mem_support_cycleOf_iff' hx).mp
          (Classical.choose_spec (Equiv.Perm.IsCycle.nonempty_support
            (Equiv.Perm.mem_cycleFactorsFinset_iff.mp
              (Equiv.Perm.cycleOf_mem_cycleFactorsFinset_iff.mpr
                (Equiv.Perm.mem_support.mpr hx))).1))).symm
  · rintro (c | x)
    · simp only [backward, forward, Quotient.lift_mk, toCycleOrFixed]
      have hc := Classical.choose_spec (Equiv.Perm.IsCycle.nonempty_support
        (Equiv.Perm.mem_cycleFactorsFinset_iff.mp c.property).1)
      have hne : σ (Classical.choose (Equiv.Perm.IsCycle.nonempty_support
          (Equiv.Perm.mem_cycleFactorsFinset_iff.mp c.property).1)) ≠
          Classical.choose (Equiv.Perm.IsCycle.nonempty_support
            (Equiv.Perm.mem_cycleFactorsFinset_iff.mp c.property).1) :=
        Equiv.Perm.mem_support.mp
          (Equiv.Perm.mem_cycleFactorsFinset_support_le c.property hc)
      simp only [hne, ↓reduceDIte]
      exact congrArg Sum.inl (Subtype.ext
        (Equiv.Perm.cycle_is_cycleOf hc c.property).symm)
    · simp only [backward, forward, Quotient.lift_mk, toCycleOrFixed]
      simp only [x.property, ↓reduceDIte]

/-- The number of permutation orbits is the number of parts in its full cycle partition. This
identifies `orbitCount`, defined from `SameCycle`, with Mathlib's fixed-point-aware cycle data. -/
theorem _root_.Equiv.Perm.orbitCount_eq_card_parts_partition (σ : Equiv.Perm α) :
    orbitCount σ = σ.partition.parts.card := by
  classical
  rw [orbitCount, Nat.card_eq_fintype_card,
    Fintype.card_congr σ.orbitQuotientEquivCycleFactorsSumFixedPoints, Fintype.card_sum,
    Fintype.card_coe]
  have hfixed : Fintype.card {x : α // σ x = x} = Fintype.card α - σ.support.card := by
    have hp : (fun x : α ↦ σ x = x) = (fun x ↦ x ∈ σ.supportᶜ) := by
      funext x
      simp [Equiv.Perm.mem_support]
    calc
      _ = Fintype.card {x : α // x ∈ σ.supportᶜ} :=
        Fintype.card_congr (Equiv.subtypeEquivProp hp)
      _ = σ.supportᶜ.card := Fintype.card_coe _
      _ = Fintype.card α - σ.support.card := Finset.card_compl (s := σ.support)
  rw [hfixed, Equiv.Perm.card_parts_partition, Equiv.Perm.cycleType_def]
  simp

/-- The sign of a finite permutation is the parity of the number of points minus the number of
orbits. Fixed points contribute once to both numbers and hence do not affect the sign. -/
theorem _root_.Equiv.Perm.sign_eq_neg_one_pow_card_sub_orbitCount (σ : Equiv.Perm α) :
    Equiv.Perm.sign σ = (-1 : ℤˣ) ^ (Fintype.card α - orbitCount σ) := by
  rw [Equiv.Perm.sign_of_parts_partition, ← orbitCount_eq_card_parts_partition]
  have hle := σ.orbitCount_le_card.trans_eq Nat.card_eq_fintype_card
  have h : Fintype.card α + orbitCount σ =
      (Fintype.card α - orbitCount σ) + 2 * orbitCount σ := by
    omega
  rw [h, pow_add, pow_mul]
  simp

end Finite

/-- Propagate a one-step comparison over all integer powers: if every point `x` of `β` lies in the
same `π`-cycle as its image `g x` does after one step of `σ`, then it lies in the same `π`-cycle
as its image after any number of steps, forwards or backwards. -/
private theorem sameCycle_zpow_of_forall_sameCycle_apply {π : Equiv.Perm α}
    {σ : Equiv.Perm β} {g : β → α}
    (h : ∀ x, SameCycle π (g x) (g (σ x))) (i : ℤ) (x : β) :
    SameCycle π (g x) (g ((σ ^ i) x)) := by
  have hinv : ∀ x, SameCycle π (g x) (g (σ⁻¹ x)) := fun x ↦ by
    have hx : σ (σ⁻¹ x) = x := by simp
    have hstep := h (σ⁻¹ x)
    rw [hx] at hstep
    exact hstep.symm
  have hneg : (σ : Equiv.Perm β) ^ (-1 : ℤ) = σ⁻¹ := by simp
  induction i using Int.induction_on generalizing x with
  | zero => simpa using SameCycle.refl π (g x)
  | succ k ih =>
    rw [zpow_add, zpow_one, Equiv.Perm.mul_apply]
    exact (h x).trans (ih (σ x))
  | pred k ih =>
    rw [sub_eq_add_neg, zpow_add, hneg, Equiv.Perm.mul_apply]
    exact (hinv x).trans (ih (σ⁻¹ x))

/-- The counting step shared by the two results below. A map `F : α → β` whose fibrewise behaviour
identifies the `σ`-orbits with the `τ`-orbits, and whose image is exactly the complement of a
fixed point `p` of `τ`, exhibits `τ` as having one orbit more than `σ`. -/
private theorem orbitCount_add_one_eq_aux {σ : Equiv.Perm α} {τ : Equiv.Perm β}
    [Finite (Quotient (SameCycle.setoid τ))]
    {F : α → β} {p : β} (hiff : ∀ x y, SameCycle σ x y ↔ SameCycle τ (F x) (F y))
    (hne : ∀ x, F x ≠ p) (hp : τ p = p) (hsurj : ∀ y, y ≠ p → ∃ x, F x = y) :
    orbitCount σ + 1 = orbitCount τ := by
  classical
  -- The orbits of `σ` are exactly the orbits of `τ` other than the singleton `{p}`.
  have key : Quotient (SameCycle.setoid σ) ≃
      { c : Quotient (SameCycle.setoid τ) // c ≠ Quotient.mk _ p } := by
    refine Equiv.ofBijective
      (fun c ↦ ⟨Quotient.map F (fun x y hxy ↦ (hiff x y).mp hxy) c, ?_⟩) ⟨?_, ?_⟩
    · induction c using Quotient.ind with
      | _ x =>
        refine fun hx ↦ hne x ?_
        exact (Quotient.eq.mp hx).eq_of_right (by simpa [Function.IsFixedPt] using hp)
    · refine fun c d hcd ↦ ?_
      induction c using Quotient.ind with
      | _ x =>
        induction d using Quotient.ind with
        | _ y =>
          exact Quotient.sound ((hiff x y).mpr (Quotient.eq.mp (congrArg Subtype.val hcd)))
    · rintro ⟨c, hc⟩
      induction c using Quotient.ind with
      | _ y =>
        obtain ⟨x, rfl⟩ := hsurj y fun hy ↦ hc (congrArg _ hy)
        exact ⟨Quotient.mk _ x, rfl⟩
  unfold orbitCount
  rw [Nat.card_congr key,
    ← Finite.card_option (α := { c : Quotient (SameCycle.setoid τ) // c ≠ Quotient.mk _ p })]
  exact Nat.card_congr (Equiv.optionSubtypeNe (Quotient.mk (SameCycle.setoid τ) p))

/-- **Adjoining a fixed point adds one orbit.** If an injection `f : α → β` intertwines
`σ : Equiv.Perm α` with `τ : Equiv.Perm β` and its image is the complement of a single point `p`,
then `p` is a fixed point of `τ` and is the only orbit of `τ` that is not an orbit of `σ`. -/
theorem orbitCount_add_one_eq_of_semiconj {f : α → β} {p : β} {σ : Equiv.Perm α}
    {τ : Equiv.Perm β} [Finite (Quotient (SameCycle.setoid τ))]
    (hf : Function.Injective f) (hfp : ∀ x, f x ≠ p)
    (hsurj : ∀ y, y ≠ p → ∃ x, f x = y) (hcomm : Function.Semiconj f σ τ) :
    orbitCount σ + 1 = orbitCount τ := by
  -- The point `p` is missed by `f`, and `τ` preserves the image of `f`, so `τ` fixes `p`.
  have hp : τ p = p := by
    by_contra hcon
    obtain ⟨x, hx⟩ := hsurj (τ p) hcon
    refine hfp (σ⁻¹ x) (τ.injective ?_)
    rw [← hcomm (σ⁻¹ x)]
    simp [hx]
  classical
  let e : α ≃ {y : β // y ≠ p} := Equiv.ofBijective (fun x ↦ ⟨f x, hfp x⟩) ⟨
    fun x y hxy ↦ hf (Subtype.ext_iff.mp hxy), fun ⟨y, hy⟩ ↦ by
      obtain ⟨x, rfl⟩ := hsurj y hy
      exact ⟨x, rfl⟩⟩
  have hτ : τ = σ.extendDomain e := by
    ext y
    by_cases hy : y = p
    · subst y
      rw [Equiv.Perm.extendDomain_apply_not_subtype]
      · exact hp
      · exact fun h ↦ h rfl
    · obtain ⟨x, rfl⟩ := hsurj y hy
      have he : (e x : β) = f x := rfl
      rw [← he, Equiv.Perm.extendDomain_apply_image]
      exact (hcomm x).symm
  refine orbitCount_add_one_eq_aux (F := f) (fun x y ↦ ?_) hfp hp hsurj
  rw [hτ]
  exact (Equiv.Perm.sameCycle_extendDomain (g := σ) (f := e)).symm

/-- **Splicing a fixed point into another orbit removes one orbit.** If `τ` fixes `p` and `a ≠ p`,
then in `τ * Equiv.swap a p` the point `p` has joined the orbit of `a`, and no other orbit has
changed. -/
theorem orbitCount_mul_swap_add_one [DecidableEq β] {τ : Equiv.Perm β}
    [Finite (Quotient (SameCycle.setoid τ))] {p a : β}
    (hp : τ p = p) (hne : a ≠ p) :
    orbitCount (τ * Equiv.swap a p) + 1 = orbitCount τ := by
  classical
  set σ : Equiv.Perm β := τ * Equiv.swap a p with hσdef
  -- The three values of `σ` that differ from those of `τ`.
  have hσp : σ p = τ a := by rw [hσdef, Equiv.Perm.mul_apply, Equiv.swap_apply_right]
  have hσa : σ a = p := by rw [hσdef, Equiv.Perm.mul_apply, Equiv.swap_apply_left, hp]
  have hσx : ∀ x, x ≠ a → x ≠ p → σ x = τ x := fun x hxa hxp ↦ by
    rw [hσdef, Equiv.Perm.mul_apply, Equiv.swap_apply_of_ne_of_ne hxa hxp]
  have hτne : ∀ x, x ≠ p → τ x ≠ p := fun x hx h ↦ hx (τ.injective (h.trans hp.symm))
  -- `F` collapses `p` onto `a`, matching the `σ`-orbits with the `τ`-orbits other than `{p}`.
  set F : β → β := fun x ↦ if x = p then a else x with hFdef
  have hFp : F p = a := by simp [hFdef]
  have hFx : ∀ x, x ≠ p → F x = x := fun x hx ↦ by simp [hFdef, hx]
  have hFne : ∀ x, F x ≠ p := fun x ↦ by
    rcases eq_or_ne x p with rfl | hx
    · rw [hFp]; exact hne
    · rw [hFx x hx]; exact hx
  -- One step of `σ` keeps `F` inside a single `τ`-orbit.
  have hstep : ∀ x, SameCycle τ (F x) (F (σ x)) := by
    intro x
    rcases eq_or_ne x p with rfl | hxp
    · rw [hFp, hσp, hFx _ (hτne a hne)]
      exact sameCycle_apply_right.mpr (SameCycle.refl τ a)
    rcases eq_or_ne x a with rfl | hxa
    · rw [hFx _ hxp, hσa, hFp]
    · rw [hFx _ hxp, hσx x hxa hxp, hFx _ (hτne x hxp)]
      exact sameCycle_apply_right.mpr (SameCycle.refl τ x)
  -- One step of `τ` keeps a point inside a single `σ`-orbit.
  have hback : ∀ x, SameCycle σ x (τ x) := by
    intro x
    rcases eq_or_ne x p with rfl | hxp
    · exact ⟨0, by simp [hp]⟩
    rcases eq_or_ne x a with rfl | hxa
    · have h1 : SameCycle σ x p := ⟨1, by simpa using hσa⟩
      have h2 : SameCycle σ p (τ x) := ⟨1, by simpa using hσp⟩
      exact h1.trans h2
    · exact ⟨1, by simpa using hσx x hxa hxp⟩
  -- Every point lies in the same `σ`-orbit as its image under `F`.
  have hFsame : ∀ x, SameCycle σ x (F x) := by
    intro x
    rcases eq_or_ne x p with rfl | hx
    · rw [hFp]
      have h1 : SameCycle σ a x := ⟨1, by simpa using hσa⟩
      exact h1.symm
    · rw [hFx x hx]
  refine orbitCount_add_one_eq_aux (F := F) (fun x y ↦ ⟨?_, ?_⟩) hFne hp fun y hy ↦ ⟨y, hFx y hy⟩
  · rintro ⟨i, rfl⟩
    exact sameCycle_zpow_of_forall_sameCycle_apply hstep i x
  · rintro ⟨i, hi⟩
    have hxy : SameCycle σ (F x) (F y) := by
      refine (sameCycle_zpow_of_forall_sameCycle_apply (π := σ) (σ := τ) (g := id) hback i
        (F x)).trans ?_
      rw [id, hi]
    exact ((hFsame x).trans hxy).trans (hFsame y).symm

/-- **Merging two orbits removes one orbit.** If every orbit of `σ` is contained in an orbit of
`τ`, if two points `a` and `b` lying in different orbits of `σ` lie in one orbit of `τ`, and if no
orbit of `τ` merges more than those two, then `τ` has exactly one orbit fewer than `σ`. The last
hypothesis is the honest content: without it nothing stops `τ` from gluing the orbits of `σ`
wholesale. -/
theorem orbitCount_add_one_of_merge {σ τ : Equiv.Perm α}
    [Finite (Quotient (SameCycle.setoid σ))] {a b : α}
    (hle : ∀ {u v : α}, SameCycle σ u v → SameCycle τ u v)
    (hmerge : ∀ {u v : α}, SameCycle τ u v → SameCycle σ u v ∨
      ((SameCycle σ u a ∨ SameCycle σ u b) ∧ (SameCycle σ v a ∨ SameCycle σ v b)))
    (hab : SameCycle τ a b) (hnab : ¬ SameCycle σ a b) :
    orbitCount τ + 1 = orbitCount σ := by
  classical
  -- The orbits of `τ` are the orbits of `σ` other than the orbit of `b`, which has been absorbed
  -- into the orbit of `a`.
  have key : {c : Quotient (SameCycle.setoid σ) // c ≠ Quotient.mk _ b} ≃
      Quotient (SameCycle.setoid τ) := by
    refine Equiv.ofBijective (fun c ↦ Quotient.map id (fun _ _ h ↦ hle h) c.val) ⟨?_, ?_⟩
    · rintro ⟨c, hc⟩ ⟨d, hd⟩ hcd
      obtain ⟨u, rfl⟩ := Quotient.exists_rep c
      obtain ⟨v, rfl⟩ := Quotient.exists_rep d
      have hub : ¬ SameCycle σ u b := fun h ↦ hc (Quotient.sound h)
      have hvb : ¬ SameCycle σ v b := fun h ↦ hd (Quotient.sound h)
      refine Subtype.ext (Quotient.sound ?_)
      rcases hmerge (Quotient.exact hcd) with huv | ⟨hu, hv⟩
      · exact huv
      · exact (hu.resolve_right hub).trans (hv.resolve_right hvb).symm
    · intro c
      obtain ⟨z, rfl⟩ := Quotient.exists_rep c
      by_cases hzb : SameCycle σ z b
      · exact ⟨⟨Quotient.mk _ a, fun h ↦ hnab (Quotient.exact h)⟩,
          Quotient.sound (hab.trans (hle hzb).symm)⟩
      · exact ⟨⟨Quotient.mk _ z, fun h ↦ hzb (Quotient.exact h)⟩, rfl⟩
  unfold orbitCount
  rw [← Nat.card_congr key, ← Finite.card_option]
  exact Nat.card_congr (Equiv.optionSubtypeNe (Quotient.mk (SameCycle.setoid σ) b))

end TauCeti
