/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Form
public import TauCeti.RepresentationTheory.Spin.Polarization.TypeB.Representation
import TauCeti.LinearAlgebra.Eigenspace.Binomial
import TauCeti.RingTheory.DividedPowers.Associative

/-!
# The type-B spinor lattice is stable under the simple-generator Kostant form

This file proves that, over `ℚ`, the coordinate spinor lattice of the type-`B` spin
representation `TauCeti.SpinPolarizationData.typeBSpinRep` of an odd polarization is stable
under the simple-generator Kostant integral form: the subring
`TauCeti.UniversalEnvelopingAlgebra.kostantForm` generated by the divided powers of the
Bourbaki-numbered simple-root family `TauCeti.typeBSimpleRootGeneratorFamily`, in both signs, and
the binomial coefficients in the simple coroots. As in
`TauCeti/LinearAlgebra/RootSystem/SimplyConnectedRootDatum/KostantForm.lean`, identifying that
subring with the canonical all-root Kostant `ℤ`-form is a separate theorem and is not claimed
here; it would first need root vectors for the roots `εᵢ + εⱼ`, which the library does not yet
have, since `TauCeti.typeBLongRootGenerator` covers only `εᵢ - εⱼ` and
`TauCeti.typeBShortRootGenerator` only `εᵢ`.

The positive and negative simple-root vectors act through square-zero Clifford bivectors, so
their divided powers preserve the lattice. The simple coroots act diagonally on the exterior
basis with integral eigenvalues: adjacent differences of half-integral spin weights away from
the terminal node, and twice the terminal half-weight at the short node. Their binomial
coefficients therefore preserve the same lattice. These are precisely the two generator inputs
consumed by `kostantForm_apply_mem`, so the whole subring they generate preserves the lattice.

The nilpotence and eigenvalue computations are stated over an arbitrary field in which `2` is
invertible, which is all the underlying Clifford comparison needs; only the lattice statements
are specific to `ℚ`, where the coordinate lattice lives.

This is a step towards the admissible lattice for the full-weight simply connected type-`B`
Chevalley carrier in Layer 9 of the ReductiveGroups roadmap. That carrier is consumed by the
`B_n(q)` branch of milestone L0 in the CFSGStatement roadmap.

## Main declarations

* `TauCeti.SpinPolarizationData.typeBSpinRep_simpleRootGenerator_sq`: the represented
  simple-root operators are square-zero.
* `TauCeti.SpinPolarizationData.typeBSpinCorootWeight`, with its values
  `TauCeti.SpinPolarizationData.typeBSpinCorootWeight_last` and
  `TauCeti.SpinPolarizationData.typeBSpinCorootWeight_castSucc`, and
  `TauCeti.SpinPolarizationData.spinAction_typeBQuadraticEquiv_typeBSimpleCorootGenerator_basis`:
  the integral eigenvalues of the numbered simple coroots on the exterior basis.
* `TauCeti.SpinPolarizationData.typeBSpinRep_kostantForm_apply_mem_integralLattice`: the
  simple-generator type-`B` Kostant form preserves the coordinate spinor lattice.

## References

* C. Chevalley, *The Algebraic Theory of Spinors*, Chapter II.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §§25--27.
* N. Bourbaki, *Groupes et algèbres de Lie*, Chapters 4--6, Planche II.
-/

public section

open CliffordAlgebra

namespace TauCeti

universe u v

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance] TauCeti.moduleNNRat

namespace SpinPolarizationData

section Quadratic

variable {K : Type u} [Field K] {V : Type v} [AddCommGroup V] [Module K V]
  {Q : QuadraticForm K V} (P : SpinPolarizationData Q) {n : ℕ}
  (b : Module.Basis (Fin (n + 1)) K P.W) (z : P.line) (hz : Q (z : V) = 1)
  [Invertible (2 : K)]

/-! ## Root operators -/

private theorem typeBQuadraticEquiv_typeBSimpleRootGenerator_mul_self
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz (typeBSimpleRootGenerator i) : CliffordAlgebra Q) ^ 2 = 0 := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleRootGenerator_last, pow_two]
    exact P.typeBQuadraticEquiv_typeBShortRootGenerator_mul_self b z hz (Fin.last n)
  · rw [typeBSimpleRootGenerator_castSucc, pow_two]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mul_self b z hz
      j.castSucc j.succ (ne_of_lt j.castSucc_lt_succ)

private theorem typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mul_self
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz
      (typeBSimpleNegativeRootGenerator i) : CliffordAlgebra Q) ^ 2 = 0 := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleNegativeRootGenerator_last, pow_two]
    exact P.typeBQuadraticEquiv_typeBShortNegativeRootGenerator_mul_self b z hz (Fin.last n)
  · rw [typeBSimpleNegativeRootGenerator_castSucc, pow_two]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mul_self b z hz
      j.succ j.castSucc (ne_of_gt j.castSucc_lt_succ)

/-- Every represented positive or negative simple-root vector is square-zero. -/
theorem typeBSpinRep_simpleRootGenerator_sq (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι K (typeBSimpleRootGeneratorFamily k)) ^ 2 = 0 := by
  rw [_root_.UniversalEnvelopingAlgebra.ι_apply, P.typeBSpinRep_ι b z hz, pow_two, ← map_mul]
  cases k with
  | inl i =>
      rw [typeBSimpleRootGeneratorFamily_inl, ← pow_two,
        P.typeBQuadraticEquiv_typeBSimpleRootGenerator_mul_self b z hz i, map_zero]
  | inr i =>
      rw [typeBSimpleRootGeneratorFamily_inr, ← pow_two,
        P.typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mul_self b z hz i, map_zero]

private theorem typeBSpinRep_longRootGenerator_apply (i j : Fin (n + 1)) (hij : i ≠ j)
    (x : ExteriorAlgebra K P.W) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι K (typeBLongRootGenerator i j hij)) x =
      ExteriorAlgebra.ι K (b i) *
        CliffordAlgebra.contractLeft (b.coord j) x := by
  rw [_root_.UniversalEnvelopingAlgebra.ι_apply, P.typeBSpinRep_ι b z hz,
    P.typeBQuadraticEquiv_typeBLongRootGenerator b z hz,
    bivector_eq_ι_mul_ι_of_isOrtho Q (P.isOrtho_basis_dualVector b hij), map_mul,
    Module.End.mul_apply, spinAction_ι_wedge, spinAction_ι_contract,
    P.pairingEquiv_dualVector]

/-- A nonterminal positive simple-root operator moves the next exterior singleton one coordinate
to the left. -/
theorem typeBSpinRep_simpleRootGenerator_castSucc_exteriorBasis_singleton (j : Fin n) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι K
          (typeBSimpleRootGeneratorFamily (.inl j.castSucc)))
        (b.ExteriorAlgebra {j.succ}) =
      b.ExteriorAlgebra {j.castSucc} := by
  rw [typeBSimpleRootGeneratorFamily_inl, typeBSimpleRootGenerator_castSucc,
    P.typeBSpinRep_longRootGenerator_apply b z hz,
    TauCeti.ExteriorAlgebra.basis_singleton, CliffordAlgebra.contractLeft_ι]
  simp [TauCeti.ExteriorAlgebra.basis_singleton]

/-- A nonterminal negative simple-root operator moves an exterior singleton one coordinate to the
right. -/
theorem typeBSpinRep_simpleNegativeRootGenerator_castSucc_exteriorBasis_singleton (j : Fin n) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι K
          (typeBSimpleRootGeneratorFamily (.inr j.castSucc)))
        (b.ExteriorAlgebra {j.castSucc}) =
      b.ExteriorAlgebra {j.succ} := by
  rw [typeBSimpleRootGeneratorFamily_inr, typeBSimpleNegativeRootGenerator_castSucc,
    P.typeBSpinRep_longRootGenerator_apply b z hz,
    TauCeti.ExteriorAlgebra.basis_singleton, CliffordAlgebra.contractLeft_ι]
  simp [TauCeti.ExteriorAlgebra.basis_singleton]

/-! ## The weights of the simple coroots -/

/-- The integral eigenvalue of a numbered simple coroot on an exterior-basis vector. -/
def typeBSpinCorootWeight (s : Finset (Fin (n + 1))) (i : Fin (n + 1)) : ℤ :=
  Fin.lastCases (if Fin.last n ∈ s then 1 else -1)
    (fun j ↦ (if j.castSucc ∈ s then 1 else 0) - if j.succ ∈ s then 1 else 0) i

/-- At the terminal short node the coroot weight is `1` or `-1` according to whether that node is
occupied. -/
@[simp]
theorem typeBSpinCorootWeight_last (s : Finset (Fin (n + 1))) :
    typeBSpinCorootWeight s (Fin.last n) = if Fin.last n ∈ s then 1 else -1 := by
  rw [typeBSpinCorootWeight, Fin.lastCases_last]

/-- Away from the terminal node the coroot weight is the adjacent difference of occupation
numbers. -/
@[simp]
theorem typeBSpinCorootWeight_castSucc (s : Finset (Fin (n + 1))) (j : Fin n) :
    typeBSpinCorootWeight s j.castSucc =
      (if j.castSucc ∈ s then 1 else 0) - if j.succ ∈ s then 1 else 0 := by
  rw [typeBSpinCorootWeight, Fin.lastCases_castSucc]

/-- A difference of two spin weights is the corresponding difference of occupation numbers: the
halves cancel. -/
private theorem spinWeight_sub_spinWeight {ι : Type*} [DecidableEq ι] (s : Finset ι) (a c : ι) :
    spinWeight K s a - spinWeight K s c =
      (((if a ∈ s then 1 else 0) - if c ∈ s then 1 else 0 : ℤ) : K) := by
  have hhalf : (⅟(2 : K)) + ⅟(2 : K) = 1 := invOf_two_add_invOf_two
  by_cases ha : a ∈ s <;> by_cases hc : c ∈ s
  · rw [spinWeight_of_mem ha, spinWeight_of_mem hc, sub_self]
    simp [ha, hc]
  · rw [spinWeight_of_mem ha, spinWeight_of_notMem hc, sub_neg_eq_add, hhalf]
    simp [ha, hc]
  · rw [spinWeight_of_notMem ha, spinWeight_of_mem hc, sub_eq_add_neg, ← neg_add, hhalf]
    simp [ha, hc]
  · rw [spinWeight_of_notMem ha, spinWeight_of_notMem hc, sub_neg_eq_add, neg_add_cancel]
    simp [ha, hc]

/-- A numbered simple coroot acts diagonally on the exterior basis, with integral eigenvalue
`typeBSpinCorootWeight`. -/
@[simp]
theorem spinAction_typeBQuadraticEquiv_typeBSimpleCorootGenerator_basis
    (i : Fin (n + 1)) (s : Finset (Fin (n + 1))) :
    spinAction Q P
        (P.typeBQuadraticEquiv b z hz (typeBSimpleCorootGenerator i) : CliffordAlgebra Q)
        (b.ExteriorAlgebra s) =
      (typeBSpinCorootWeight s i : K) • b.ExteriorAlgebra s := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleCorootGenerator_last,
      P.spinAction_typeBQuadraticEquiv_typeBShortCorootGenerator_basis b z hz]
    by_cases hlast : Fin.last n ∈ s <;> simp [hlast]
  · rw [typeBSimpleCorootGenerator_castSucc,
      P.spinAction_typeBQuadraticEquiv_typeBLongCorootGenerator_basis b z hz,
      spinWeight_sub_spinWeight]
    simp

end Quadratic

/-! ## Stability of the coordinate spinor lattice -/

section Integral

variable {V : Type v} [AddCommGroup V] [Module ℚ V] {Q : QuadraticForm ℚ V}
  (P : SpinPolarizationData Q) {n : ℕ} (b : Module.Basis (Fin (n + 1)) ℚ P.W)
  (z : P.line) (hz : Q (z : V) = 1)

private theorem typeBQuadraticEquiv_typeBSimpleRootGenerator_mem_integralSpinActionSubring
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz (typeBSimpleRootGenerator i) : CliffordAlgebra Q) ∈
      P.integralSpinActionSubring b := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleRootGenerator_last]
    exact P.typeBQuadraticEquiv_typeBShortRootGenerator_mem_integralSpinActionSubring
      b z hz (Fin.last n)
  · rw [typeBSimpleRootGenerator_castSucc]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mem_integralSpinActionSubring
      b z hz j.castSucc j.succ (ne_of_lt j.castSucc_lt_succ)

private theorem
    typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mem_integralSpinActionSubring
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz
      (typeBSimpleNegativeRootGenerator i) : CliffordAlgebra Q) ∈
      P.integralSpinActionSubring b := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleNegativeRootGenerator_last]
    exact P.typeBQuadraticEquiv_typeBShortNegativeRootGenerator_mem_integralSpinActionSubring
      b z hz (Fin.last n)
  · rw [typeBSimpleNegativeRootGenerator_castSucc]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mem_integralSpinActionSubring
      b z hz j.succ j.castSucc (ne_of_gt j.castSucc_lt_succ)

/-- Every represented positive or negative simple-root vector preserves the coordinate spinor
lattice. -/
theorem typeBSpinRep_simpleRootGenerator_apply_mem_integralLattice
    (k : Fin (n + 1) ⊕ Fin (n + 1)) {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι ℚ (typeBSimpleRootGeneratorFamily k)) v ∈
      TauCeti.ExteriorAlgebra.integralLattice b := by
  rw [_root_.UniversalEnvelopingAlgebra.ι_apply, P.typeBSpinRep_ι b z hz]
  cases k with
  | inl i =>
      rw [typeBSimpleRootGeneratorFamily_inl]
      exact (P.mem_integralSpinActionSubring b).mp
        (P.typeBQuadraticEquiv_typeBSimpleRootGenerator_mem_integralSpinActionSubring
          b z hz i) hv
  | inr i =>
      rw [typeBSimpleRootGeneratorFamily_inr]
      exact (P.mem_integralSpinActionSubring b).mp
        (P.typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mem_integralSpinActionSubring
          b z hz i) hv

/-- Every binomial coefficient in a represented simple coroot preserves the coordinate spinor
lattice: the exterior basis consists of eigenvectors with integral eigenvalues. -/
theorem typeBSpinRep_ringChoose_coroot_apply_mem_integralLattice
    (i : Fin (n + 1)) (m : ℕ) {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz
        (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ
          (typeBSimpleCorootGenerator i)) m) v ∈
      TauCeti.ExteriorAlgebra.integralLattice b := by
  rw [TauCeti.ExteriorAlgebra.integralLattice_eq_span] at hv
  rw [Ring.map_choose, TauCeti.ExteriorAlgebra.integralLattice_eq_span]
  simp only [_root_.UniversalEnvelopingAlgebra.ι_apply]
  refine TauCeti.ringChoose_end_apply_mem_span_of_apply_eq_intCast_smul
    (weight := fun s ↦ typeBSpinCorootWeight s i) (fun s ↦ ?_) m hv
  rw [P.typeBSpinRep_ι b z hz]
  exact P.spinAction_typeBQuadraticEquiv_typeBSimpleCorootGenerator_basis b z hz i s

/-- **The coordinate spinor lattice is stable under the simple-generator type-`B` Kostant
form**: under the subring generated by the divided powers of the simple-root family
`typeBSimpleRootGeneratorFamily` and the binomial coefficients in `typeBSimpleCorootGenerator`.
No comparison with the all-root Kostant `ℤ`-form of type `B` is claimed. -/
theorem typeBSpinRep_kostantForm_apply_mem_integralLattice
    {u : _root_.UniversalEnvelopingAlgebra ℚ
      (LieAlgebra.Orthogonal.typeB (Fin (n + 1)) ℚ)}
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm
      (typeBSimpleRootGeneratorFamily (K := ℚ)) (typeBSimpleCorootGenerator (K := ℚ)))
    {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz u v ∈ TauCeti.ExteriorAlgebra.integralLattice b := by
  exact TauCeti.UniversalEnvelopingAlgebra.kostantForm_apply_mem
    (typeBSimpleRootGeneratorFamily (K := ℚ)) (typeBSimpleCorootGenerator (K := ℚ))
    (P.typeBSpinRep b z hz) (TauCeti.ExteriorAlgebra.integralLattice b)
    (fun k m _ hw ↦ by
      rw [Associative.map_dividedPower]
      exact Associative.dividedPower_apply_mem_of_pow_two_eq_zero _
        (TauCeti.ExteriorAlgebra.integralLattice b).toAddSubgroup
        (P.typeBSpinRep_simpleRootGenerator_sq b z hz k)
        (fun hw' ↦ P.typeBSpinRep_simpleRootGenerator_apply_mem_integralLattice b z hz k hw') m hw)
    (fun i m _ hw ↦ P.typeBSpinRep_ringChoose_coroot_apply_mem_integralLattice
      b z hz i m hw) u hu hv

end Integral

end SpinPolarizationData

end TauCeti
