/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Matrix.Rank
public import TauCeti.InformationTheory.Coding.Basic

import Mathlib.LinearAlgebra.Basis.Submodule

/-!
# Matrix presentations of linear codes

A matrix presents a linear code in either of two complementary ways. A generator matrix presents
the span of its rows, implemented as the range of `Matrix.vecMulLinear`; a parity-check matrix
presents the kernel of `Matrix.mulVecLin`. This file defines both constructions and the predicates
saying that a matrix presents a specified code.

The API identifies membership with coefficient vectors or vanishing syndromes, computes both
dimensions from matrix rank, and characterizes compatibility of a generator and a parity-check
matrix by the matrix equation `H * Gᵀ = 0`. These facts are the linear-algebra interface used by
systematic presentations, dual codes, and exact verification of named finite codes.

## Main definitions

* `Matrix.generatedBy` is the row code of a matrix.
* `Matrix.checkedBy` is the code with vanishing syndrome for a matrix.
* `TauCeti.LinearCode.IsGeneratorMatrix` and `TauCeti.LinearCode.IsParityCheckMatrix` record that
  either presentation gives a specified code.
-/

public section

noncomputable section

open Matrix Set

namespace TauCeti

variable {F ι ρ σ : Type*} [Field F]

/-- The linear code generated by the rows of `G`. A coefficient vector `a` represents the
codeword `a ᵥ* G`. -/
def _root_.Matrix.generatedBy [Fintype ρ] (G : Matrix ρ ι F) : LinearCode F ι :=
  LinearMap.range G.vecMulLinear

/-- The linear code checked by `H`: its words are exactly those with zero syndrome `H *ᵥ x`. -/
def _root_.Matrix.checkedBy [Fintype ι] (H : Matrix ρ ι F) : LinearCode F ι :=
  LinearMap.ker H.mulVecLin

/-- The code generated by `G` is the range of vector-matrix multiplication by `G`. -/
theorem _root_.Matrix.generatedBy_def [Fintype ρ] (G : Matrix ρ ι F) :
    G.generatedBy = LinearMap.range G.vecMulLinear := (rfl)

/-- The code checked by `H` is the kernel of matrix-vector multiplication by `H`. -/
theorem _root_.Matrix.checkedBy_def [Fintype ι] (H : Matrix ρ ι F) :
    H.checkedBy = LinearMap.ker H.mulVecLin := (rfl)

namespace LinearCode

/-- A matrix is a generator matrix for `C` when its rows span `C`. -/
def IsGeneratorMatrix [Fintype ρ] (C : LinearCode F ι) (G : Matrix ρ ι F) : Prop :=
  G.generatedBy = C

/-- A matrix is a parity-check matrix for `C` when `C` is its kernel. -/
def IsParityCheckMatrix [Fintype ι] (C : LinearCode F ι) (H : Matrix ρ ι F) : Prop :=
  H.checkedBy = C

/-- `G` is a generator matrix for `C` exactly when the code generated by `G` is `C`. -/
theorem isGeneratorMatrix_def [Fintype ρ] (C : LinearCode F ι) (G : Matrix ρ ι F) :
    C.IsGeneratorMatrix G ↔ G.generatedBy = C := Iff.rfl

/-- `H` is a parity-check matrix for `C` exactly when the code checked by `H` is `C`. -/
theorem isParityCheckMatrix_def [Fintype ι] (C : LinearCode F ι) (H : Matrix ρ ι F) :
    C.IsParityCheckMatrix H ↔ H.checkedBy = C := Iff.rfl

end LinearCode

/-- The generated code is the span of the rows. -/
theorem _root_.Matrix.generatedBy_eq_span_rows [Fintype ρ] (G : Matrix ρ ι F) :
    G.generatedBy = Submodule.span F (Set.range G.row) := by
  rw [generatedBy_def, range_vecMulLinear]

/-- A word belongs to the code generated by `G` exactly when it is a linear combination of the
rows, expressed as right multiplication by `G`. -/
@[simp]
theorem _root_.Matrix.mem_generatedBy_iff [Fintype ρ] {G : Matrix ρ ι F} {x : ι → F} :
    x ∈ G.generatedBy ↔ ∃ a : ρ → F, a ᵥ* G = x := by
  simp only [generatedBy_def, LinearMap.mem_range, Matrix.vecMulLinear_apply]

/-- Every row of a matrix belongs to its generated code. -/
theorem _root_.Matrix.row_mem_generatedBy [Fintype ρ] (G : Matrix ρ ι F) (r : ρ) :
    G.row r ∈ G.generatedBy := by
  rw [generatedBy_eq_span_rows]
  exact Submodule.subset_span (Set.mem_range_self r)

/-- The row code of `G` lies in `C` exactly when every row of `G` lies in `C`. -/
theorem _root_.Matrix.generatedBy_le_iff [Fintype ρ] {G : Matrix ρ ι F} {C : LinearCode F ι} :
    G.generatedBy ≤ C ↔ ∀ r, G.row r ∈ C := by
  rw [generatedBy_eq_span_rows, Submodule.span_le]
  exact Set.range_subset_iff

/-- A word belongs to the code checked by `H` exactly when its syndrome vanishes. -/
@[simp]
theorem _root_.Matrix.mem_checkedBy_iff [Fintype ι] {H : Matrix ρ ι F} {x : ι → F} :
    x ∈ H.checkedBy ↔ H *ᵥ x = 0 := by
  rw [checkedBy_def, LinearMap.mem_ker, Matrix.mulVecLin_apply]

/-- A code lies in the code checked by `H` exactly when `H` kills each of its words. -/
theorem _root_.Matrix.le_checkedBy_iff [Fintype ι] {C : LinearCode F ι} {H : Matrix ρ ι F} :
    C ≤ H.checkedBy ↔ ∀ x ∈ C, H *ᵥ x = 0 := by
  simp only [SetLike.le_def, mem_checkedBy_iff]

/-- Every matrix is a generator matrix for its generated code. -/
theorem _root_.Matrix.isGeneratorMatrix_generatedBy [Fintype ρ] (G : Matrix ρ ι F) :
    G.generatedBy.IsGeneratorMatrix G := by
  rw [LinearCode.isGeneratorMatrix_def]

/-- Every matrix is a parity-check matrix for its checked code. -/
theorem _root_.Matrix.isParityCheckMatrix_checkedBy [Fintype ι] (H : Matrix ρ ι F) :
    H.checkedBy.IsParityCheckMatrix H := by
  rw [LinearCode.isParityCheckMatrix_def]

/-- The dimension of the code generated by a matrix is the rank of that matrix. -/
@[simp]
theorem _root_.Matrix.finrank_generatedBy [Fintype ρ] [Fintype ι] (G : Matrix ρ ι F) :
    Module.finrank F G.generatedBy = G.rank := by
  rw [generatedBy_eq_span_rows, G.rank_eq_finrank_span_row]

/-- The dimension of the code checked by a matrix is the number of coordinates minus the rank of
that matrix. -/
@[simp]
theorem _root_.Matrix.finrank_checkedBy [Fintype ι] (H : Matrix ρ ι F) :
    Module.finrank F H.checkedBy = Fintype.card ι - H.rank := by
  rw [checkedBy_def, Matrix.rank]
  have h := H.mulVecLin.finrank_range_add_finrank_ker
  rw [Module.finrank_fintype_fun_eq_card] at h
  omega

/-- The rows of `G` satisfy all checks in `H` exactly when `H * Gᵀ = 0`. -/
theorem _root_.Matrix.generatedBy_le_checkedBy_iff [Fintype ρ] [Fintype ι]
    {G : Matrix ρ ι F} {H : Matrix σ ι F} :
    G.generatedBy ≤ H.checkedBy ↔ H * G.transpose = 0 := by
  classical
  rw [generatedBy_def, checkedBy_def, LinearMap.range_le_ker_iff, ← Matrix.mulVecLin_transpose,
    ← Matrix.mulVecLin_mul, ← Matrix.toLin'_apply', ← Matrix.toLin'.map_zero,
    Matrix.toLin'.injective.eq_iff]

namespace LinearCode

/-- A matrix generates `C` exactly when every word of `C` has a coefficient vector and every
represented word belongs to `C`. -/
theorem isGeneratorMatrix_iff_forall [Fintype ρ] {C : LinearCode F ι}
    {G : Matrix ρ ι F} :
    C.IsGeneratorMatrix G ↔
      (∀ x ∈ C, ∃ a : ρ → F, a ᵥ* G = x) ∧ (∀ a : ρ → F, a ᵥ* G ∈ C) := by
  rw [isGeneratorMatrix_def]
  constructor
  · rintro rfl
    exact ⟨fun x hx ↦ (mem_generatedBy_iff.mp hx),
      fun a ↦ mem_generatedBy_iff.mpr ⟨a, rfl⟩⟩
  · rintro ⟨honto, hinto⟩
    ext x
    constructor
    · rintro hx
      obtain ⟨a, rfl⟩ := mem_generatedBy_iff.mp hx
      exact hinto a
    · exact fun hx ↦ mem_generatedBy_iff.mpr (honto x hx)

/-- A matrix is a parity-check matrix for `C` exactly when vanishing of the syndrome
characterizes membership in `C`. -/
theorem isParityCheckMatrix_iff_mem [Fintype ι] {C : LinearCode F ι}
    {H : Matrix ρ ι F} :
    C.IsParityCheckMatrix H ↔ ∀ x, x ∈ C ↔ H *ᵥ x = 0 := by
  rw [isParityCheckMatrix_def]
  constructor
  · rintro rfl x
    exact mem_checkedBy_iff
  · intro h
    ext x
    exact mem_checkedBy_iff.trans (h x).symm

/-- A full-row-rank generator matrix for `C` has one row per dimension of `C`. -/
theorem card_eq_finrank_of_isGeneratorMatrix_of_linearIndependent [Fintype ρ] [Finite ι]
    {C : LinearCode F ι} {G : Matrix ρ ι F} (hG : C.IsGeneratorMatrix G)
    (hli : LinearIndependent F G.row) :
    Fintype.card ρ = Module.finrank F C := by
  let _ := Fintype.ofFinite ι
  rw [isGeneratorMatrix_def] at hG
  rw [← hG, finrank_generatedBy, hli.rank_matrix]

/-- Every finite-length linear code has a generator matrix with one row per dimension, and those
rows are linearly independent. -/
theorem exists_isGeneratorMatrix [Finite ι] (C : LinearCode F ι) :
    ∃ G : Matrix (Fin (Module.finrank F C)) ι F,
      C.IsGeneratorMatrix G ∧ LinearIndependent F G.row := by
  let _ := Fintype.ofFinite ι
  let b := Module.finBasis F C
  let G : Matrix (Fin (Module.finrank F C)) ι F := fun r i ↦ (b r : ι → F) i
  have hrow : G.row = fun r ↦ (b r : ι → F) := by
    funext r i
    rfl
  refine ⟨G, ?_, ?_⟩
  · rw [isGeneratorMatrix_def, generatedBy_eq_span_rows, hrow]
    calc
      Submodule.span F (Set.range fun r ↦ (b r : ι → F)) =
          Submodule.map C.subtype (Submodule.span F (Set.range b)) := by
        rw [Submodule.map_span, ← Set.range_comp]
        rfl
      _ = C := by rw [b.span_eq, Submodule.map_top, C.range_subtype]
  · rw [hrow]
    exact b.linearIndependent.map' C.subtype (Submodule.ker_subtype C)

/-- A full-row-rank parity-check matrix for `C` has `length - dim C` rows. -/
theorem card_eq_card_sub_finrank_of_isParityCheckMatrix_of_linearIndependent
    [Fintype ρ] [Fintype ι] {C : LinearCode F ι} {H : Matrix ρ ι F}
    (hH : C.IsParityCheckMatrix H) (hli : LinearIndependent F H.row) :
    Fintype.card ρ = Fintype.card ι - Module.finrank F C := by
  rw [isParityCheckMatrix_def] at hH
  have hdim := finrank_checkedBy H
  rw [hH, hli.rank_matrix] at hdim
  have hrank := Matrix.rank_le_card_width H
  rw [hli.rank_matrix] at hrank
  omega

/-- A generator matrix and a parity-check matrix for the same code satisfy `H * Gᵀ = 0`. -/
theorem IsGeneratorMatrix.mul_transpose_eq_zero [Fintype ρ] [Fintype ι]
    {C : LinearCode F ι} {G : Matrix ρ ι F} {H : Matrix σ ι F}
    (hG : C.IsGeneratorMatrix G) (hH : C.IsParityCheckMatrix H) :
    H * G.transpose = 0 := by
  rw [← generatedBy_le_checkedBy_iff, hG, hH]

end LinearCode

end TauCeti
