/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.Cyclotomic.Basic
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
public import Mathlib.NumberTheory.NumberField.Ideal.KummerDedekind
public import TauCeti.NumberTheory.NumberField.Index.Basic
public import TauCeti.NumberTheory.NumberField.Quadratic.RingOfIntegers

/-!
# Monogenic number fields

A number field `K` is *monogenic* when its ring of integers admits a power integral basis, that
is `𝓞 K = ℤ[θ]` for a single algebraic integer `θ`. This file defines the predicate, gives the
two standard criteria for it — one in terms of the conductor exponent, one in terms of the index
`[𝓞 K : ℤ[θ]]` — and records the classical monogenic families.

The predicate lives in the `TauCeti.NumberField` namespace rather than the root namespace, where
a bare `IsMonogenic` would collide with the ring-theoretic notion of a monogenic algebra.

## Main definitions

* `TauCeti.NumberField.IsMonogenic`: the ring of integers is generated by a single element as a
  `ℤ`-algebra.

## Main results

* `TauCeti.NumberField.isMonogenic_def`: the defining condition, for introduction and
  elimination.
* `TauCeti.NumberField.isMonogenic_iff_exists_exponent_eq_one`: monogenicity in terms of the
  conductor exponent.
* `TauCeti.NumberField.isMonogenic_iff_exists_index_eq_one`: monogenicity in terms of the index
  `[𝓞 K : ℤ[θ]]`.
* `TauCeti.NumberField.isMonogenic_of_isCyclotomicExtension`: cyclotomic fields are monogenic.
* `TauCeti.NumberField.isMonogenic_cyclotomicField_four`: `ℚ(i)` is monogenic, with
  `𝓞 ℚ(i) = ℤ[i]`.
* `TauCeti.NumberField.isMonogenic_of_quadratic`: quadratic fields are monogenic, unconditionally
  in the class of `d` modulo `4`.
* `TauCeti.NumberField.isMonogenic_rat`: `ℚ` is monogenic.

Dedekind's cubic field, the standard example of a field that is *not* monogenic, is not treated
here: its non-monogenicity is witnessed by a common index divisor, a prime dividing the index of
every generator.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter I, §2.
-/

public section

open scoped NumberField
open Polynomial RingOfIntegers

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

/-- A field `K` is **monogenic** when its ring of integers is generated by a single algebraic
integer as a `ℤ`-algebra, that is `𝓞 K = ℤ[θ]`.

Only `[Field K]` is assumed, because `𝓞 K` needs no more than that; the intended case, and the
one every result below is about, is a number field. -/
def IsMonogenic (K : Type*) [Field K] : Prop :=
  ∃ θ : 𝓞 K, Algebra.adjoin ℤ {θ} = ⊤

omit [NumberField K] in
/-- **The defining condition of monogenicity**, for introducing and eliminating the predicate. -/
theorem isMonogenic_def : IsMonogenic K ↔ ∃ θ : 𝓞 K, Algebra.adjoin ℤ {θ} = ⊤ :=
  Iff.rfl

omit [NumberField K] in
/-- **Monogenicity via the conductor exponent.** `K` is monogenic exactly when some algebraic
integer of `K` has conductor exponent `1`. -/
theorem isMonogenic_iff_exists_exponent_eq_one :
    IsMonogenic K ↔ ∃ θ : 𝓞 K, exponent θ = 1 := by
  simp_rw [IsMonogenic, exponent_eq_one_iff]

/-- **Monogenicity via the index.** `K` is monogenic exactly when some integral primitive element
has index `1`, so the two ways of saying `𝓞 K = ℤ[θ]` agree. -/
theorem isMonogenic_iff_exists_index_eq_one :
    IsMonogenic K ↔ ∃ θ : IntegralPrimitiveElement K, θ.index = 1 := by
  constructor
  · rintro ⟨θ, hθ⟩
    exact ⟨IntegralPrimitiveElement.ofAdjoinEqTop hθ,
      IntegralPrimitiveElement.index_ofAdjoinEqTop hθ⟩
  · rintro ⟨θ, hθ⟩
    refine ⟨θ.1, ?_⟩
    rw [← IntegralPrimitiveElement.adjoin_def]
    exact (IntegralPrimitiveElement.index_eq_one_iff θ).mp hθ

omit [NumberField K] in
/-- **Cyclotomic fields are monogenic**: a primitive `n`-th root of unity generates the ring of
integers, `𝓞 K = ℤ[ζ]`. The root is produced internally, so no generator need be supplied. -/
theorem isMonogenic_of_isCyclotomicExtension [CharZero K] (n : ℕ) [NeZero n]
    [IsCyclotomicExtension {n} ℚ K] : IsMonogenic K :=
  ⟨(IsCyclotomicExtension.zeta_spec n ℚ K).toInteger,
    IsCyclotomicExtension.Rat.adjoin_singleton_eq_top (IsCyclotomicExtension.zeta_spec n ℚ K)⟩

/-- **`ℚ(i)` is monogenic**: the fourth cyclotomic field has `𝓞 ℚ(i) = ℤ[i]`, generated by a
primitive fourth root of unity. -/
theorem isMonogenic_cyclotomicField_four : IsMonogenic (CyclotomicField 4 ℚ) := by
  have : IsCyclotomicExtension {4} ℚ (CyclotomicField 4 ℚ) :=
    CyclotomicField.isCyclotomicExtension 4 ℚ
  exact isMonogenic_of_isCyclotomicExtension 4

/-- **Quadratic fields with `d % 4 ≠ 1` are monogenic**, generated by `θ` itself. -/
theorem isMonogenic_of_mod_four_ne_one {θ : 𝓞 K} {d : ℤ} (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) (hd4 : d % 4 ≠ 1) :
    IsMonogenic K :=
  ⟨θ, _root_.NumberField.adjoin_gen_eq_top_of_mod_four_ne_one hmin hgen hsf hd4⟩

/-- **Quadratic fields with `d % 4 = 1` are monogenic**, generated by `(1 + θ) / 2`. -/
theorem isMonogenic_of_mod_four_eq_one {θ : 𝓞 K} {d : ℤ} (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) (hd4 : d % 4 = 1) :
    IsMonogenic K :=
  ⟨_root_.NumberField.halfGen hmin hd4,
    _root_.NumberField.adjoin_halfGen_eq_top_of_mod_four_eq_one hmin hgen hsf hd4⟩

/-- **Quadratic fields are monogenic.** Either `θ` or `(1 + θ) / 2` generates the ring of
integers, according to the class of `d` modulo `4`. -/
theorem isMonogenic_of_quadratic {θ : 𝓞 K} {d : ℤ} (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) : IsMonogenic K := by
  by_cases hd4 : d % 4 = 1
  · exact isMonogenic_of_mod_four_eq_one hmin hgen hsf hd4
  · exact isMonogenic_of_mod_four_ne_one hmin hgen hsf hd4

/-- **`ℚ` is monogenic**: its ring of integers is `ℤ`, generated by `1`. -/
@[simp]
theorem isMonogenic_rat : IsMonogenic ℚ := by
  refine ⟨1, ?_⟩
  rw [eq_top_iff]
  rintro x -
  obtain ⟨n, rfl⟩ := Rat.ringOfIntegersEquiv.symm.surjective x
  have hn : Rat.ringOfIntegersEquiv.symm n = algebraMap ℤ (𝓞 ℚ) n := by
    apply _root_.NumberField.RingOfIntegers.ext
    rw [Rat.ringOfIntegersEquiv_symm_apply_coe]
    simp
  rw [hn]
  exact Subalgebra.algebraMap_mem _ n

end TauCeti.NumberField
