/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Real.Basic
import Mathlib.Analysis.Complex.Order
import Mathlib.FieldTheory.Galois.Basic

/-!
# The real candidate genus field as a fixed field

The candidate genus field is an abelian Galois subfield of `ℂ`. Complex conjugation preserves
it: each chosen generator has rational square, so its conjugate is that generator or its negative.
This gives an automorphism `candidateGenusFieldConj hd` of the candidate field.

The automorphism negates exactly the roots belonging to negative prime discriminants. Its fixed
field is the maximal totally real subfield `candidateGenusFieldReal hd`. This description is the
field-theoretic input for comparing the ordinary genus field of a real quadratic field with the
ordinary elementary-`2` class-group quotient.

The fixed-field description is classical; see F. Lemmermeyer, *Reciprocity Laws: From Euler to
Eisenstein*, Section 2.2, and D. A. Cox, *Primes of the Form x² + ny²*, Section 6.A.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldConj`: complex conjugation restricted to the
  candidate genus field.

## Main results

* `TauCeti.Multiquadratic.candidateGenusFieldConj_apply_gen`: conjugation negates precisely the
  generators indexed by negative prime discriminants.
* `TauCeti.Multiquadratic.candidateGenusFieldConj_apply_eq_self_iff`: an element is fixed by
  conjugation exactly when it belongs to the real candidate.
* `TauCeti.Multiquadratic.fixedField_zpowers_candidateGenusFieldConj`: the fixed field of complex
  conjugation is `candidateGenusFieldReal hd`.
* `TauCeti.Multiquadratic.fixingSubgroup_candidateGenusFieldReal`: the subgroup fixing the real
  candidate is generated by complex conjugation.
-/

public section

open IntermediateField
open scoped CharZero ComplexOrder IsMulCommutative

namespace TauCeti.Multiquadratic

variable {d : ℤ}

private theorem conj_genusFieldRoot_mem_candidateGenusField (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    star (genusFieldRoot hd P) ∈ candidateGenusField hd := by
  have hsq : (star (genusFieldRoot hd P)) ^ 2 = genusFieldRoot hd P ^ 2 := by
    calc
      (starRingEnd ℂ (genusFieldRoot hd P)) ^ 2 =
          starRingEnd ℂ (genusFieldRoot hd P ^ 2) := by rw [map_pow]
      _ = genusFieldRoot hd P ^ 2 := by rw [genusFieldRoot_sq]; simp
  rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h | h
  · rw [h]
    exact genusFieldRoot_mem_candidateGenusField hd P
  · rw [h]
    exact neg_mem (genusFieldRoot_mem_candidateGenusField hd P)

private theorem map_candidateGenusField_conj (hd : Squarefree d) :
    (candidateGenusField hd).map (Complex.conjAe.restrictScalars ℚ).toAlgHom =
      candidateGenusField hd := by
  apply le_antisymm
  · rw [candidateGenusField_def, IntermediateField.adjoin_map, adjoin_le_iff]
    rintro z ⟨_, ⟨P, rfl⟩, rfl⟩
    rw [← candidateGenusField_def]
    -- The coercion of the scalar-restricted equivalence is definitionally conjugation, but it
    -- remains hidden behind the image-set coercion after `adjoin_map`.
    change star (genusFieldRoot hd P) ∈ candidateGenusField hd
    exact conj_genusFieldRoot_mem_candidateGenusField hd P
  · rw [candidateGenusField_le_iff]
    intro P
    rw [IntermediateField.mem_map]
    refine ⟨star (genusFieldRoot hd P), conj_genusFieldRoot_mem_candidateGenusField hd P, ?_⟩
    simp

/-- **Complex conjugation on the candidate genus field.** The compositum of the chosen square
roots of prime-discriminant radicands is stable under complex conjugation, because the conjugate
of each root is either that root or its negative. -/
noncomputable def candidateGenusFieldConj (hd : Squarefree d) :
    candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd :=
  ((candidateGenusField hd).equivMap (Complex.conjAe.restrictScalars ℚ).toAlgHom).trans
    (IntermediateField.equivOfEq (map_candidateGenusField_conj hd))

/-- The restriction of complex conjugation has the expected value in the ambient field `ℂ`. -/
@[simp] theorem coe_candidateGenusFieldConj_apply (hd : Squarefree d)
    (x : candidateGenusField hd) :
    ((candidateGenusFieldConj hd x : candidateGenusField hd) : ℂ) = star (x : ℂ) := by
  rfl

/-- **Complex conjugation negates exactly the negative prime-discriminant generators.** -/
@[simp] theorem candidateGenusFieldConj_apply_gen (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldConj hd (candidateGenusFieldGen hd P) =
      if P.val < 0 then -candidateGenusFieldGen hd P else candidateGenusFieldGen hd P := by
  apply Subtype.ext
  simp only [coe_candidateGenusFieldConj_apply, candidateGenusFieldGen_val]
  split_ifs with hneg
  · have hrad : primeDiscriminantRadicand P.val < 0 :=
      (primeDiscriminantRadicand_neg_iff
        ((genusPrimeDiscriminants_spec hd).1 P.val P.property)).2 hneg
    have hsquare : genusFieldRoot hd P ^ 2 ≤ 0 := by
      rw [genusFieldRoot_sq]
      exact_mod_cast hrad.le
    have hre : (genusFieldRoot hd P).re = 0 := Complex.sq_nonpos_iff.mp hsquare
    apply Complex.ext
    · simp [hre]
    · simp
  · have hrad : 0 ≤ primeDiscriminantRadicand P.val := by
      have : ¬ primeDiscriminantRadicand P.val < 0 := fun hr => hneg <|
        (primeDiscriminantRadicand_neg_iff
          ((genusPrimeDiscriminants_spec hd).1 P.val P.property)).1 hr
      omega
    have hsquare : 0 ≤ genusFieldRoot hd P ^ 2 := by
      rw [genusFieldRoot_sq]
      exact_mod_cast hrad
    simpa only [candidateGenusFieldGen_val, Complex.star_def] using
      Complex.conj_eq_iff_im.mpr (Complex.sq_nonneg_iff.mp hsquare)

/-- The sign pattern of complex conjugation is supported exactly on the negative prime
discriminants. This is the coordinate form used by the relative Galois-group quotient.

This is not a simp lemma because its left-hand side already reduces through the coordinate and
generator-action simp lemmas. -/
theorem candidateGenusFieldSignPattern_conj_apply (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldSignPattern hd (candidateGenusFieldConj hd) P =
      if P.val < 0 then 1 else 0 := by
  by_cases hneg : P.val < 0
  · simp [candidateGenusFieldSignPattern_apply, hneg]
  · simp [candidateGenusFieldSignPattern_apply, hneg]

private theorem mem_fixedField_zpowers_candidateGenusFieldConj_iff (hd : Squarefree d)
    (x : candidateGenusField hd) :
    x ∈ IntermediateField.fixedField (Subgroup.zpowers (candidateGenusFieldConj hd)) ↔
      candidateGenusFieldConj hd x = x := by
  rw [IntermediateField.mem_fixedField_iff, Subgroup.forall_mem_zpowers]
  constructor
  · intro h
    simpa using h 1
  · intro h n
    have hx : x ∈ MulAction.fixedBy (candidateGenusField hd) (candidateGenusFieldConj hd) := by
      simpa only [MulAction.mem_fixedBy, AlgEquiv.smul_def] using h
    simpa only [MulAction.mem_fixedBy, AlgEquiv.smul_def] using
      MulAction.mem_fixedBy_zpow hx n

/-- An element of the candidate genus field is fixed by complex conjugation exactly when it lies
in the maximal totally real subfield. -/
theorem candidateGenusFieldConj_apply_eq_self_iff (hd : Squarefree d)
    (x : candidateGenusField hd) :
    candidateGenusFieldConj hd x = x ↔ x ∈ candidateGenusFieldReal hd := by
  rw [mem_candidateGenusFieldReal_iff]
  constructor
  · intro hx φ
    let τ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd :=
      AlgHom.restrictNormal' φ.toRatAlgHom (candidateGenusField hd)
    have hτ (y : candidateGenusField hd) : ((τ y : candidateGenusField hd) : ℂ) = φ y :=
      calc
        ((τ y : candidateGenusField hd) : ℂ) =
            φ.toRatAlgHom (algebraMap (candidateGenusField hd) (candidateGenusField hd) y) := by
          exact AlgHom.restrictNormal_commutes φ.toRatAlgHom (candidateGenusField hd) y
        _ = φ y := by rw [Algebra.algebraMap_self_apply]; rfl
    calc
      star (φ x) = star ((τ x : candidateGenusField hd) : ℂ) := congrArg star (hτ x).symm
      _ = ((candidateGenusFieldConj hd (τ x) : candidateGenusField hd) : ℂ) :=
        (coe_candidateGenusFieldConj_apply hd (τ x)).symm
      _ = ((τ (candidateGenusFieldConj hd x) : candidateGenusField hd) : ℂ) := by
        exact congrArg Subtype.val
          (DFunLike.congr_fun (mul_comm (candidateGenusFieldConj hd) τ) x)
      _ = ((τ x : candidateGenusField hd) : ℂ) := by rw [hx]
      _ = φ x := hτ x
  · intro hx
    apply Subtype.ext
    rw [coe_candidateGenusFieldConj_apply]
    exact hx (candidateGenusField hd).val

/-- **The maximal totally real subfield is the fixed field of complex conjugation.** Equivalently,
the ordinary real candidate is obtained from the full prime-discriminant compositum by fixing the
cyclic subgroup generated by the automorphism that negates its negative-radicand roots. -/
theorem fixedField_zpowers_candidateGenusFieldConj (hd : Squarefree d) :
    IntermediateField.fixedField (Subgroup.zpowers (candidateGenusFieldConj hd)) =
      candidateGenusFieldReal hd := by
  ext x
  exact (mem_fixedField_zpowers_candidateGenusFieldConj_iff hd x).trans
    (candidateGenusFieldConj_apply_eq_self_iff hd x)

/-- **The subgroup fixing the real candidate is generated by complex conjugation.** This is the
kernel subgroup in the Galois correspondence, including the totally real case where conjugation is
the identity and the subgroup is trivial. -/
theorem fixingSubgroup_candidateGenusFieldReal (hd : Squarefree d) :
    (candidateGenusFieldReal hd).fixingSubgroup =
      Subgroup.zpowers (candidateGenusFieldConj hd) := by
  rw [← fixedField_zpowers_candidateGenusFieldConj hd,
    IntermediateField.fixingSubgroup_fixedField]

end TauCeti.Multiquadratic
