/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
public import Mathlib.LinearAlgebra.FreeModule.Finite.Quotient
public import Mathlib.NumberTheory.NumberField.Basic
public import Mathlib.RingTheory.Ideal.Norm.AbsNorm
import TauCeti.NumberTheory.NumberField.Minpoly

/-!
# The index of an integral primitive element

An integral primitive element `θ` of a number field `K` generates a full-rank subring
`ℤ[θ]` of the ring of integers `𝓞 K`. Its *index* is the finite cardinality

`[𝓞 K : ℤ[θ]] = #(𝓞 K / ℤ[θ])`.

This file defines integral primitive elements and their index, proves that the defining
quotient is finite (and hence that the index is positive), and establishes the exact
invariances under translating the generator by an integer and negating it.

## Main definitions

* `TauCeti.NumberField.IntegralPrimitiveElement K`: integral elements generating `K` over `ℚ`.
* `TauCeti.NumberField.IntegralPrimitiveElement.index`: the index of `ℤ[θ]` in `𝓞 K`.
* `TauCeti.NumberField.IntegralPrimitiveElement.ofAdjoinEqTop`: an element generating `𝓞 K` as a
  `ℤ`-algebra, as an integral primitive element.

## Main results

* `TauCeti.NumberField.IntegralPrimitiveElement.finrank_adjoin`: `ℤ[θ]` has full rank in `𝓞 K`.
* `TauCeti.NumberField.IntegralPrimitiveElement.index_pos`: the index is positive.
* `TauCeti.NumberField.IntegralPrimitiveElement.index_eq_one_iff`: the index is `1` exactly when
  `ℤ[θ]` is all of `𝓞 K`.
* `TauCeti.NumberField.adjoin_rat_eq_top_of_adjoin_int_eq_top`: an element generating `𝓞 K` over
  `ℤ` generates `K` over `ℚ`.
* `TauCeti.NumberField.IntegralPrimitiveElement.index_addIntCast`: integer translation preserves
  the index.
* `TauCeti.NumberField.IntegralPrimitiveElement.index_neg`: negation preserves the index.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter I, §2.
-/

public section

open scoped NumberField

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

-- The carrier and index API shape follow the human-authored specification in
-- `TauCetiRoadmap/NumberFieldArithmetic/Suggested.lean`.
/-- An integral primitive element of a number field `K`: an element of `𝓞 K` whose image in
`K` generates `K` as a `ℚ`-algebra. -/
@[expose]
def IntegralPrimitiveElement (K : Type*) [Field K] [NumberField K] : Type _ :=
  {θ : 𝓞 K // Algebra.adjoin ℚ {(θ : K)} = ⊤}

/-- An element whose order `ℤ[θ]` is all of `𝓞 K` generates `K` over `ℚ`. -/
theorem adjoin_rat_eq_top_of_adjoin_int_eq_top {θ : 𝓞 K}
    (h : Algebra.adjoin ℤ {θ} = (⊤ : Subalgebra ℤ (𝓞 K))) :
    Algebra.adjoin ℚ {(θ : K)} = ⊤ := by
  have key : ∀ c : 𝓞 K, algebraMap (𝓞 K) K c ∈ IntermediateField.adjoin ℚ {(θ : K)} := by
    intro c
    have hc : c ∈ Algebra.adjoin ℤ ({θ} : Set (𝓞 K)) := h ▸ Algebra.mem_top
    induction hc using Algebra.adjoin_induction with
    | mem y hy =>
        rw [Set.mem_singleton_iff] at hy
        subst hy
        exact IntermediateField.mem_adjoin_simple_self ℚ _
    | algebraMap n =>
        have hn : algebraMap (𝓞 K) K (algebraMap ℤ (𝓞 K) n) = (n : K) := by
          rw [← IsScalarTower.algebraMap_apply ℤ (𝓞 K) K]
          simp
        rw [hn]
        exact intCast_mem _ n
    | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
    | mul x y _ _ hx hy => rw [map_mul]; exact mul_mem hx hy
  rw [← IntermediateField.adjoin_eq_top_iff_of_isAlgebraic
    (fun x _ ↦ IsAlgebraic.of_finite ℚ x), eq_top_iff]
  intro x _
  obtain ⟨a, b, _, rfl⟩ := IsFractionRing.div_surjective (𝓞 K) x
  exact div_mem (key a) (key b)

namespace IntegralPrimitiveElement

instance : Coe (IntegralPrimitiveElement K) (𝓞 K) :=
  ⟨Subtype.val⟩

/-- The `ℤ`-subalgebra of `𝓞 K` generated by an integral primitive element. -/
def adjoin (θ : IntegralPrimitiveElement K) : Subalgebra ℤ (𝓞 K) :=
  Algebra.adjoin ℤ {θ.1}

/-- The generated order is the `ℤ`-subalgebra generated by the underlying ring integer. -/
theorem adjoin_def (θ : IntegralPrimitiveElement K) :
    θ.adjoin = Algebra.adjoin ℤ {θ.1} :=
  (rfl)

/-- The additive quotient of `𝓞 K` by the order `ℤ[θ]`. -/
abbrev Quotient (θ : IntegralPrimitiveElement K) :=
  𝓞 K ⧸ θ.adjoin.toSubmodule

/-- The index `[𝓞 K : ℤ[θ]]`, defined as the cardinality of the additive quotient. -/
noncomputable def index (θ : IntegralPrimitiveElement K) : ℕ :=
  θ.adjoin.toSubmodule.cardQuot

/-- The index is the cardinality of the additive quotient by the generated order. -/
theorem index_def (θ : IntegralPrimitiveElement K) :
    θ.index = Nat.card (𝓞 K ⧸ θ.adjoin.toSubmodule) :=
  Submodule.cardQuot_apply θ.adjoin.toSubmodule

/-- A multiple `n • b` vanishes in the quotient `𝓞 K / ℤ[θ]` exactly when `n * b` lies in the
order `ℤ[θ]`. -/
theorem nsmul_mkQ_eq_zero_iff (θ : IntegralPrimitiveElement K) (n : ℕ) (b : 𝓞 K) :
    (n • θ.adjoin.toSubmodule.mkQ b : θ.Quotient) = 0 ↔ (n : 𝓞 K) * b ∈ θ.adjoin := by
  rw [← map_nsmul, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, Subalgebra.mem_toSubmodule,
    nsmul_eq_mul]

/-- The order `ℤ[θ]` generated by an integral primitive element has full rank in `𝓞 K`. -/
theorem finrank_adjoin (θ : IntegralPrimitiveElement K) :
    Module.finrank ℤ θ.adjoin = Module.finrank ℤ (𝓞 K) := by
  have hθ : IntermediateField.adjoin ℚ {(θ.1 : K)} = ⊤ := by
    apply (IntermediateField.adjoin_eq_top_iff_of_isAlgebraic ?_).mpr θ.2
    exact fun x _ ↦ IsAlgebraic.of_finite ℚ x
  calc
    Module.finrank ℤ θ.adjoin = (minpoly ℤ θ.1).natDegree := by
      exact (Algebra.adjoin.powerBasis' θ.1.isIntegral).finrank
    _ = (minpoly ℚ (θ.1 : K)).natDegree := by
      rw [_root_.NumberField.RingOfIntegers.minpoly_rat_coe,
        (minpoly.monic θ.1.isIntegral).natDegree_map]
    _ = Module.finrank ℚ K :=
      (Field.primitive_element_iff_minpoly_natDegree_eq ℚ (θ.1 : K)).mp hθ
    _ = Module.finrank ℤ (𝓞 K) := (_root_.NumberField.RingOfIntegers.rank K).symm

/-- The quotient `𝓞 K / ℤ[θ]` is finite. -/
instance finite_quotient (θ : IntegralPrimitiveElement K) : Finite θ.Quotient :=
  Submodule.finiteQuotientOfFreeOfRankEq θ.adjoin.toSubmodule θ.finrank_adjoin

/-- The index of an integral primitive element is positive. -/
theorem index_pos (θ : IntegralPrimitiveElement K) : 0 < θ.index := by
  rw [index, Submodule.cardQuot_apply]
  exact Nat.card_pos

/-- The index of an integral primitive element `θ` is `1` exactly when the order `ℤ[θ]` is all of
`𝓞 K`. -/
@[simp]
theorem index_eq_one_iff (θ : IntegralPrimitiveElement K) : θ.index = 1 ↔ θ.adjoin = ⊤ := by
  rw [index, Submodule.cardQuot_eq_one_iff, Algebra.toSubmodule_eq_top]

/-- An element generating `𝓞 K` as a `ℤ`-algebra, as an integral primitive element. -/
def ofAdjoinEqTop {θ : 𝓞 K} (h : Algebra.adjoin ℤ {θ} = (⊤ : Subalgebra ℤ (𝓞 K))) :
    IntegralPrimitiveElement K :=
  ⟨θ, adjoin_rat_eq_top_of_adjoin_int_eq_top h⟩

@[simp]
theorem coe_ofAdjoinEqTop {θ : 𝓞 K} (h : Algebra.adjoin ℤ {θ} = (⊤ : Subalgebra ℤ (𝓞 K))) :
    (ofAdjoinEqTop h : 𝓞 K) = θ :=
  (rfl)

/-- The order generated by `ofAdjoinEqTop h` is all of `𝓞 K`, by construction. -/
@[simp]
theorem adjoin_ofAdjoinEqTop {θ : 𝓞 K} (h : Algebra.adjoin ℤ {θ} = (⊤ : Subalgebra ℤ (𝓞 K))) :
    (ofAdjoinEqTop h).adjoin = ⊤ :=
  h

/-- An element generating `𝓞 K` as a `ℤ`-algebra has index `1`. -/
@[simp]
theorem index_ofAdjoinEqTop {θ : 𝓞 K} (h : Algebra.adjoin ℤ {θ} = (⊤ : Subalgebra ℤ (𝓞 K))) :
    (ofAdjoinEqTop h).index = 1 :=
  (index_eq_one_iff _).mpr (adjoin_ofAdjoinEqTop h)

/-! ### Changing the generator -/

/-- Translating an integral primitive element by an integer gives another integral primitive
element. -/
def addIntCast (θ : IntegralPrimitiveElement K) (n : ℤ) : IntegralPrimitiveElement K :=
  ⟨θ.1 + algebraMap ℤ (𝓞 K) n, by
    have h : Algebra.adjoin ℚ {(θ.1 : K) + (n : K)} =
        Algebra.adjoin ℚ {(θ.1 : K)} := by
      have hn : ((n : K)) = algebraMap ℚ K (n : ℚ) := (map_intCast (algebraMap ℚ K) n).symm
      rw [hn, ← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
          (IsAlgebraic.of_finite ℚ ((θ.1 : K) + algebraMap ℚ K (n : ℚ))),
        IntermediateField.adjoin_simple_add_algebraMap,
        IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
          (IsAlgebraic.of_finite ℚ (θ.1 : K))]
    have hcoe : ((θ.1 + algebraMap ℤ (𝓞 K) n : 𝓞 K) : K) =
        (θ.1 : K) + (n : K) := by
      calc
        _ = algebraMap (𝓞 K) K θ.1 +
            algebraMap (𝓞 K) K (algebraMap ℤ (𝓞 K) n) :=
          map_add (algebraMap (𝓞 K) K) _ _
        _ = (θ.1 : K) + (n : K) := by
          rw [← IsScalarTower.algebraMap_apply ℤ (𝓞 K) K]
          rw [_root_.NumberField.RingOfIntegers.coe_eq_algebraMap]
          rfl
    rw [hcoe]
    exact h.trans θ.2⟩

@[simp]
theorem coe_addIntCast (θ : IntegralPrimitiveElement K) (n : ℤ) :
    (θ.addIntCast n : 𝓞 K) = θ.1 + algebraMap ℤ (𝓞 K) n :=
  (rfl)

/-- Integer translation does not change the generated `ℤ`-subalgebra. -/
@[simp]
theorem adjoin_addIntCast (θ : IntegralPrimitiveElement K) (n : ℤ) :
    (θ.addIntCast n).adjoin = θ.adjoin := by
  simp only [adjoin_def, coe_addIntCast]
  apply le_antisymm
  · rw [Algebra.adjoin_le_iff, Set.singleton_subset_iff]
    exact (Algebra.adjoin ℤ {θ.1}).add_mem
      (Algebra.subset_adjoin (Set.mem_singleton θ.1))
      ((Algebra.adjoin ℤ {θ.1}).algebraMap_mem n)
  · rw [Algebra.adjoin_le_iff, Set.singleton_subset_iff]
    simpa using (Algebra.adjoin ℤ {θ.1 + algebraMap ℤ (𝓞 K) n}).sub_mem
      (Algebra.subset_adjoin (Set.mem_singleton (θ.1 + algebraMap ℤ (𝓞 K) n)))
      ((Algebra.adjoin ℤ {θ.1 + algebraMap ℤ (𝓞 K) n}).algebraMap_mem n)

/-- Translating an integral primitive element by an integer preserves its index. -/
@[simp]
theorem index_addIntCast (θ : IntegralPrimitiveElement K) (n : ℤ) :
    (θ.addIntCast n).index = θ.index := by
  rw [index, index, adjoin_addIntCast]

/-- Negating an integral primitive element gives another integral primitive element. -/
protected def neg (θ : IntegralPrimitiveElement K) : IntegralPrimitiveElement K :=
  ⟨-θ.1, by
    have h : Algebra.adjoin ℚ {-((θ.1 : K))} = Algebra.adjoin ℚ {(θ.1 : K)} := by
      have hmul : -((θ.1 : K)) = (θ.1 : K) * algebraMap ℚ K (-1 : ℚ) := by
        rw [map_neg, map_one, mul_neg_one]
      rw [hmul, ← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
          (IsAlgebraic.of_finite ℚ ((θ.1 : K) * algebraMap ℚ K (-1 : ℚ))),
        IntermediateField.adjoin_simple_mul_algebraMap _ _ (neg_ne_zero.mpr one_ne_zero),
        IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
          (IsAlgebraic.of_finite ℚ (θ.1 : K))]
    have hcoe : ((-θ.1 : 𝓞 K) : K) = -(θ.1 : K) := by
      exact map_neg (algebraMap (𝓞 K) K) θ.1
    rw [hcoe]
    exact h.trans θ.2⟩

instance : Neg (IntegralPrimitiveElement K) :=
  ⟨IntegralPrimitiveElement.neg⟩

@[simp]
theorem coe_neg (θ : IntegralPrimitiveElement K) :
    ((-θ : IntegralPrimitiveElement K) : 𝓞 K) = -θ.1 :=
  (rfl)

/-- Negation does not change the generated `ℤ`-subalgebra. -/
@[simp]
theorem adjoin_neg (θ : IntegralPrimitiveElement K) : (-θ).adjoin = θ.adjoin := by
  simp only [adjoin_def, coe_neg]
  apply le_antisymm
  · rw [Algebra.adjoin_le_iff, Set.singleton_subset_iff]
    exact (Algebra.adjoin ℤ {θ.1}).neg_mem
      (Algebra.subset_adjoin (Set.mem_singleton θ.1))
  · rw [Algebra.adjoin_le_iff, Set.singleton_subset_iff]
    simpa using (Algebra.adjoin ℤ {-θ.1}).neg_mem
      (Algebra.subset_adjoin (Set.mem_singleton (-θ.1)))

/-- Negating an integral primitive element preserves its index. -/
@[simp]
theorem index_neg (θ : IntegralPrimitiveElement K) : (-θ).index = θ.index := by
  rw [index, index, adjoin_neg]

end IntegralPrimitiveElement

end TauCeti.NumberField
