/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Index.Exponent
public import TauCeti.RingTheory.Polynomial.Monic.Irreducible

/-!
# Common index divisors

A prime `p` is a *common index divisor* of a number field `K` when it divides the index
`[𝓞 K : ℤ[θ]]` of **every** integral primitive element `θ`. Such a prime obstructs monogenicity:
`𝓞 K = ℤ[θ]` would force `index θ = 1`.

The obstruction is a counting argument. Kummer–Dedekind puts the primes of `𝓞 K` above `p` in
bijection with the distinct monic irreducible factors of `minpoly ℤ θ` modulo `p`, matching the
residue degree of a prime with the degree of its factor — but only for a `θ` whose conductor
exponent is prime to `p`. So if `p` has more primes of residue degree `d` than there are monic
irreducible polynomials of degree `d` available over `𝔽_p`, no `θ` can satisfy that hypothesis,
and then `p` divides `exponent θ`, hence `index θ`.

## Main definitions

* `TauCeti.NumberField.IsCommonIndexDivisor`: `p` divides the index of every integral primitive
  element.
* `TauCeti.NumberField.primesOverOfInertiaDeg`: the primes above `p` of a fixed residue degree.

## Main results

* `TauCeti.NumberField.IsCommonIndexDivisor.dvd_index`: the elimination form, extracting the
  divisibility at a given integral primitive element.
* `TauCeti.NumberField.IsCommonIndexDivisor.not_exists_index_eq_one`: a common index divisor
  rules out an element of index `1`, so it obstructs monogenicity.
* `TauCeti.NumberField.IsCommonIndexDivisor.adjoin_ne_top`: equivalently, no order `ℤ[θ]` is all
  of `𝓞 K`.
* `TauCeti.NumberField.inertiaDeg_eq_natDegree_primesOverSpanEquivMonicFactorsMod`: the
  Kummer–Dedekind bijection matches residue degree with the degree of the factor.
* `TauCeti.NumberField.ncard_primesOverOfInertiaDeg_le`: the Kummer–Dedekind counting bound.
* `TauCeti.NumberField.card_filter_monicFactorsMod_le`: the factors of `minpoly ℤ θ` of degree
  `d` are among the degree-`d` monic irreducibles over `𝔽_p`.
* `TauCeti.NumberField.isCommonIndexDivisor_of_ncard_lt_ncard`: the counting obstruction.

The converse is Hensel's criterion — the common index divisors are exactly the primes whose
splitting type is not realizable modulo `p` — and is deliberately not proved here.

## References

* [J. Neukirch, *Algebraic number theory*][neukirch1999], III §2 Exercise 1.
-/

public section

open scoped NumberField
open Ideal Polynomial RingOfIntegers NumberField.Ideal

namespace TauCeti.NumberField

variable {K : Type*} [Field K] [NumberField K]

/-- `p` is a **common index divisor** of `K` when it divides the index `[𝓞 K : ℤ[θ]]` of every
integral primitive element `θ` of `K`.

A common index divisor obstructs monogenicity. If `K` admits no integral primitive element the
condition holds vacuously, so the predicate carries content only when such a `θ` exists. -/
def IsCommonIndexDivisor (p : ℕ) (K : Type*) [Field K] [NumberField K] : Prop :=
  ∀ θ : IntegralPrimitiveElement K, p ∣ θ.index

/-- **Being a common index divisor is exactly divisibility of every index.** The body of
`IsCommonIndexDivisor` is not exposed across module boundaries, so this is the characterisation
downstream code uses to prove the predicate or to extract a divisibility from it. -/
theorem isCommonIndexDivisor_iff {p : ℕ} :
    IsCommonIndexDivisor p K ↔ ∀ θ : IntegralPrimitiveElement K, p ∣ θ.index :=
  Iff.rfl

namespace IsCommonIndexDivisor

variable {p : ℕ}

/-- **A common index divisor divides every index.** The elimination form of the predicate: it
extracts the divisibility at a given integral primitive element, so a consumer never has to
unfold a definition whose body is not exposed across module boundaries. -/
theorem dvd_index (h : IsCommonIndexDivisor p K) (θ : IntegralPrimitiveElement K) :
    p ∣ θ.index :=
  isCommonIndexDivisor_iff.mp h θ

/-- **A common index divisor obstructs monogenicity.** No integral primitive element has index
`1`, since `p` divides every index and `p ≠ 1`.

Primality is not needed: any `p ≠ 1` dividing every index gives the same obstruction. -/
theorem not_exists_index_eq_one (hp : p ≠ 1) (h : IsCommonIndexDivisor p K) :
    ¬ ∃ θ : IntegralPrimitiveElement K, θ.index = 1 := by
  rintro ⟨θ, hθ⟩
  exact hp (Nat.dvd_one.mp (hθ ▸ h θ))

/-- The same obstruction stated on orders: no `ℤ[θ]` generated by an integral primitive element
is all of `𝓞 K`. -/
theorem adjoin_ne_top (hp : p ≠ 1) (h : IsCommonIndexDivisor p K)
    (θ : IntegralPrimitiveElement K) : θ.adjoin ≠ ⊤ := fun hadj =>
  h.not_exists_index_eq_one hp ⟨θ, (IntegralPrimitiveElement.index_eq_one_iff θ).mpr hadj⟩

end IsCommonIndexDivisor

section Prime

variable (p : ℕ) [Fact p.Prime]

variable (K) in
/-- The primes of `𝓞 K` above `p` whose residue degree over `ℤ` is `d`. -/
def primesOverOfInertiaDeg (d : ℕ) : Set ((span {(p : ℤ)}).primesOver (𝓞 K)) :=
  {Q | (Q : Ideal (𝓞 K)).inertiaDeg ℤ = d}

omit [NumberField K] [Fact (Nat.Prime p)] in
/-- Membership in `primesOverOfInertiaDeg` is the residue-degree condition defining it. -/
@[simp]
theorem mem_primesOverOfInertiaDeg_iff {d : ℕ}
    {Q : (span {(p : ℤ)}).primesOver (𝓞 K)} :
    Q ∈ primesOverOfInertiaDeg K p d ↔ (Q : Ideal (𝓞 K)).inertiaDeg ℤ = d :=
  Iff.rfl

/-- **The Kummer–Dedekind bijection preserves degree.** For a `θ` whose conductor exponent is
prime to `p`, the residue degree of a prime above `p` equals the degree of the monic irreducible
factor of `minpoly ℤ θ` modulo `p` that the bijection assigns to it. -/
theorem inertiaDeg_eq_natDegree_primesOverSpanEquivMonicFactorsMod {θ : 𝓞 K}
    (hp : ¬ p ∣ exponent θ) (Q : (span {(p : ℤ)}).primesOver (𝓞 K)) :
    (Q : Ideal (𝓞 K)).inertiaDeg ℤ =
      (primesOverSpanEquivMonicFactorsMod hp Q : (ZMod p)[X]).natDegree := by
  -- The degree lemma is stated at `.symm`; rewrite `Q` as `.symm (e Q)` to apply it.
  have h := inertiaDeg_primesOverSpanEquivMonicFactorsMod_symm_apply' hp
    (primesOverSpanEquivMonicFactorsMod hp Q).2
  rwa [Subtype.coe_eta, Equiv.symm_apply_apply] at h

omit [NumberField K] in
/-- The degree-`d` monic irreducible factors of `minpoly ℤ θ` modulo `p` are among the degree-`d`
monic irreducibles over `𝔽_p`, so they are no more numerous. -/
theorem card_filter_monicFactorsMod_le {θ : 𝓞 K} (d : ℕ) :
    ((monicFactorsMod θ p).filter fun Q => Q.natDegree = d).card ≤
      (monicIrreduciblesOfDegree (ZMod p) d).ncard := by
  classical
  have h₀ : Polynomial.map (Int.castRingHom (ZMod p)) (minpoly ℤ θ) ≠ 0 :=
    Polynomial.map_monic_ne_zero (minpoly.monic θ.isIntegral)
  have hsub : ↑((monicFactorsMod θ p).filter fun Q => Q.natDegree = d) ⊆
      monicIrreduciblesOfDegree (ZMod p) d := by
    intro g hg
    rw [Finset.mem_coe, Finset.mem_filter] at hg
    obtain ⟨hmem, hdeg⟩ := hg
    rw [Multiset.mem_toFinset] at hmem
    obtain ⟨hirr, hmon, -⟩ := (Polynomial.mem_normalizedFactors_iff h₀).mp hmem
    -- `monicIrreduciblesOfDegree` lives in another module, so its body is not exposed here:
    -- go through the membership lemma rather than the anonymous constructor.
    exact (mem_monicIrreduciblesOfDegree_iff (ZMod p)).mpr ⟨hmon, hirr, hdeg⟩
  rw [← Set.ncard_coe_finset]
  exact Set.ncard_le_ncard hsub (finite_monicIrreduciblesOfDegree (ZMod p) d)

/-- A prime above `p` of residue degree `d` is sent to a degree-`d` factor. Plumbing for the
counting bound. -/
private theorem mem_filter_monicFactorsMod_of_mem_primesOverOfInertiaDeg {θ : 𝓞 K}
    (hp : ¬ p ∣ exponent θ) {d : ℕ}
    (Q : (span {(p : ℤ)}).primesOver (𝓞 K))
    (hQ : Q ∈ primesOverOfInertiaDeg K p d) :
    ((primesOverSpanEquivMonicFactorsMod hp Q : (ZMod p)[X])) ∈
      (monicFactorsMod θ p).filter fun R => R.natDegree = d := by
  classical
  refine Finset.mem_filter.mpr ⟨(primesOverSpanEquivMonicFactorsMod hp Q).2, ?_⟩
  exact (inertiaDeg_eq_natDegree_primesOverSpanEquivMonicFactorsMod p hp Q) ▸ hQ

/-- **The Kummer–Dedekind counting bound.** For a `θ` whose conductor exponent is prime to `p`,
the primes of `𝓞 K` above `p` with residue degree `d` are no more numerous than the degree-`d`
monic irreducible factors of `minpoly ℤ θ` modulo `p`. -/
theorem ncard_primesOverOfInertiaDeg_le {θ : 𝓞 K} (hp : ¬ p ∣ exponent θ) (d : ℕ) :
    (primesOverOfInertiaDeg K p d).ncard ≤
      ((monicFactorsMod θ p).filter fun Q => Q.natDegree = d).card := by
  classical
  have hinj : Set.InjOn
      (fun Q => (primesOverSpanEquivMonicFactorsMod hp Q : (ZMod p)[X]))
      (primesOverOfInertiaDeg K p d) := fun _ _ _ _ h =>
    (primesOverSpanEquivMonicFactorsMod hp).injective (Subtype.ext h)
  rw [← Set.ncard_coe_finset ((monicFactorsMod θ p).filter fun Q => Q.natDegree = d)]
  exact Set.ncard_le_ncard_of_injOn _
    (mem_filter_monicFactorsMod_of_mem_primesOverOfInertiaDeg p hp) hinj
    (Finset.finite_toSet _)

/-- **The counting obstruction.** If `p` has more primes of residue degree `d` than there are
monic irreducible polynomials of degree `d` over `𝔽_p`, then `p` divides the index of every
integral primitive element.

Both counts are intrinsic to `p`, `d` and `K`: no bound is assumed, because the degree-`d` monic
irreducibles over `𝔽_p` are a fixed finite set independent of any generator. -/
theorem isCommonIndexDivisor_of_ncard_lt_ncard {d : ℕ}
    (hlt : (monicIrreduciblesOfDegree (ZMod p) d).ncard <
      (primesOverOfInertiaDeg K p d).ncard) :
    IsCommonIndexDivisor p K := by
  intro θ
  by_contra hdvd
  -- A `θ` escaping `p` in the index also escapes it in the conductor exponent.
  have hexp : ¬ p ∣ exponent (θ : 𝓞 K) := fun h =>
    hdvd ((IntegralPrimitiveElement.dvd_index_iff_dvd_exponent θ).mpr h)
  have hle : (primesOverOfInertiaDeg K p d).ncard ≤
      (monicIrreduciblesOfDegree (ZMod p) d).ncard :=
    (ncard_primesOverOfInertiaDeg_le p hexp d).trans (card_filter_monicFactorsMod_le p d)
  exact absurd (hlt.trans_le hle) (lt_irrefl _)

end Prime

end TauCeti.NumberField
