/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Geometry.Convex.Cone.Dual
public import TauCeti.Geometry.Toric.Algebraic.Lattice

/-!
# Dual semigroups of toric cones

An integral character of a lattice extends uniquely to a real-linear functional on the ambient
real vector space (`TauCeti.Toric.IsIntegralLattice.realCharacter`). The dual semigroup of a cone
consists of the integral characters whose real extensions are nonnegative on the cone. When the
cone is rational polyhedral, this is the additive monoid whose semigroup algebra is the
coordinate ring of the corresponding affine toric variety; the definition itself imposes no
finiteness hypothesis on the cone.

The construction is expressed as the inverse image of Mathlib's `PointedCone.dual`, so its order
reversal and its behavior on cone hulls come directly from the convex-geometric duality API.
Maps of lattices carrying one cone into another induce contravariant maps of dual semigroups.

## Main declarations

* `TauCeti.Toric.dualSemigroup`: integral characters nonnegative on a cone.
* `TauCeti.Toric.dualSemigroupMap`: the contravariant map induced by a compatible map of
  lattices and cones.

## References

The construction follows §1.2 of W. Fulton, *Introduction to Toric Varieties*, and §1.2 of
D. Cox, J. Little and H. Schenck, *Toric Varieties*.
-/

public section

namespace TauCeti.Toric

variable {N N' N'' V V' V'' : Type*}
  [AddCommGroup N] [AddCommGroup N'] [AddCommGroup N'']
  [AddCommGroup V] [AddCommGroup V'] [AddCommGroup V'']
  [Module ℝ V] [Module ℝ V'] [Module ℝ V'']
  {i : N →+ V} {i' : N' →+ V'} {i'' : N'' →+ V''}
  {σ : PointedCone ℝ V} {τ : PointedCone ℝ V'} {υ : PointedCone ℝ V''}

/-! ### The dual semigroup -/

/-- The dual semigroup of a cone consists of the integral characters whose real-linear
extensions are nonnegative on the cone. -/
-- Interface source: `TauCetiRoadmap/AnalyticToricGeometry/Suggested.lean`.
noncomputable def dualSemigroup (hi : IsIntegralLattice i) (σ : PointedCone ℝ V) :
    AddSubmonoid (N →+ ℤ) :=
  (PointedCone.dual (Module.Dual.eval ℝ V) σ).toAddSubmonoid.comap hi.realCharacter

/-- The dual semigroup is the inverse image of Mathlib's dual cone under real extension of
integral characters. -/
theorem dualSemigroup_def (hi : IsIntegralLattice i) (σ : PointedCone ℝ V) :
    dualSemigroup hi σ =
      (PointedCone.dual (Module.Dual.eval ℝ V) σ).toAddSubmonoid.comap hi.realCharacter :=
  -- The parentheses matter: `(rfl)` elaborates against the definition, whereas a bare `rfl` in
  -- an exported theorem would require `dualSemigroup` to be `@[expose]`d.
  (rfl)

/-- An integral character belongs to the dual semigroup exactly when its real extension is
nonnegative at every point of the cone. -/
@[simp]
theorem mem_dualSemigroup (hi : IsIntegralLattice i) (m : N →+ ℤ) :
    m ∈ dualSemigroup hi σ ↔ ∀ ⦃x⦄, x ∈ σ → 0 ≤ hi.realCharacter m x :=
  Iff.rfl

/-- Enlarging a cone shrinks its dual semigroup. -/
@[gcongr]
theorem dualSemigroup_anti (hi : IsIntegralLattice i) {σ τ : PointedCone ℝ V} (h : σ ≤ τ) :
    dualSemigroup hi τ ≤ dualSemigroup hi σ := by
  intro m hm x hx
  exact hm (h hx)

/-- Taking the dual semigroup reverses the order on pointed cones. -/
theorem dualSemigroup_antitone (hi : IsIntegralLattice i) :
    Antitone (dualSemigroup hi) := fun _ _ h ↦ dualSemigroup_anti hi h

/-- The dual semigroup of the zero cone is the full character group. -/
@[simp]
theorem dualSemigroup_bot (hi : IsIntegralLattice i) :
    dualSemigroup hi (⊥ : PointedCone ℝ V) = ⊤ := by
  ext m
  simp

/-- The dual semigroup of a join is the intersection of the two dual semigroups. -/
@[simp]
theorem dualSemigroup_sup (hi : IsIntegralLattice i) (σ τ : PointedCone ℝ V) :
    dualSemigroup hi (σ ⊔ τ) = dualSemigroup hi σ ⊓ dualSemigroup hi τ := by
  simp only [dualSemigroup_def, PointedCone.dual_sup, PointedCone.dual_union]
  ext m
  simp [AddSubmonoid.mem_inf]

/-- On a cone generated by a set of lattice vectors, membership in the dual semigroup is
equivalent to the corresponding family of integral inequalities. -/
theorem mem_dualSemigroup_hull_image (hi : IsIntegralLattice i) (s : Set N)
    (m : N →+ ℤ) :
    m ∈ dualSemigroup hi (PointedCone.hull ℝ (i '' s)) ↔
      ∀ n ∈ s, 0 ≤ m n := by
  rw [dualSemigroup_def, AddSubmonoid.mem_comap, PointedCone.dual_hull]
  simp

/-! ### Functoriality -/

/-- A compatible map of lattices carrying a source cone into a target cone induces the
contravariant map on dual semigroups by precomposition of characters. -/
noncomputable def dualSemigroupMap (hi : IsIntegralLattice i) (hi' : IsIntegralLattice i')
    (f : N →+ N') (g : V →ₗ[ℝ] V') (hfg : ∀ n, g (i n) = i' (f n))
    (hστ : Set.MapsTo g σ τ) : dualSemigroup hi' τ →+ dualSemigroup hi σ :=
  (AddMonoidHom.compHom' f).restrict fun m hm ↦ by
    have hcomp : AddMonoidHom.compHom' f m = m.comp f := by
      ext n
      simp
    rw [SetLike.mem_coe, hcomp, mem_dualSemigroup, hi.realCharacter_comp hi' f g hfg]
    intro x hx
    exact (mem_dualSemigroup hi' m).1 hm (hστ hx)

/-- The map on dual semigroups is precomposition by the underlying map of lattices. -/
@[simp]
theorem dualSemigroupMap_apply (hi : IsIntegralLattice i) (hi' : IsIntegralLattice i')
    (f : N →+ N') (g : V →ₗ[ℝ] V') (hfg : ∀ n, g (i n) = i' (f n))
    (hστ : Set.MapsTo g σ τ) (m : dualSemigroup hi' τ) (n : N) :
    (dualSemigroupMap hi hi' f g hfg hστ m : N →+ ℤ) n = (m : N' →+ ℤ) (f n) :=
  by simp [dualSemigroupMap, AddMonoidHom.restrict]

/-- The identity map of a lattice induces the identity map of its dual semigroup. -/
@[simp]
theorem dualSemigroupMap_id (hi : IsIntegralLattice i) (σ : PointedCone ℝ V) :
    dualSemigroupMap hi hi (AddMonoidHom.id N) LinearMap.id (fun _ ↦ rfl)
      (Set.mapsTo_id _) = AddMonoidHom.id (dualSemigroup hi σ) := by
  ext m n
  simp only [dualSemigroupMap_apply, AddMonoidHom.id_apply]

/-- Contravariant dual-semigroup maps turn a composite of compatible cone maps into the
composite of the induced maps. -/
theorem dualSemigroupMap_comp (hi : IsIntegralLattice i) (hi' : IsIntegralLattice i')
    (hi'' : IsIntegralLattice i'') (f : N →+ N') (f' : N' →+ N'')
    (g : V →ₗ[ℝ] V') (g' : V' →ₗ[ℝ] V'')
    (hfg : ∀ n, g (i n) = i' (f n)) (hf'g' : ∀ n, g' (i' n) = i'' (f' n))
    (hστ : Set.MapsTo g σ τ) (hτυ : Set.MapsTo g' τ υ) :
    dualSemigroupMap hi hi'' (f'.comp f) (g'.comp g)
        (fun n ↦ by simp [hfg, hf'g']) (hτυ.comp hστ) =
      (dualSemigroupMap hi hi' f g hfg hστ).comp
        (dualSemigroupMap hi' hi'' f' g' hf'g' hτυ) := by
  ext m n
  simp only [dualSemigroupMap_apply, AddMonoidHom.comp_apply]

end TauCeti.Toric
