/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Finite.MinpolyOrbit
public import TauCeti.FieldTheory.GaloisGroups.Orbits

/-!
# Factor degrees over a finite field are Frobenius orbit sizes

Let `g` be a polynomial over a finite field `F` with `q` elements and let `E` be an algebraic
extension of `F` in which `g` splits.  Two groups act on the roots of `g` in `E`: the Galois
group `Polynomial.Gal g`, whose orbits are matched with the monic irreducible factors of `g` in
`TauCeti/FieldTheory/GaloisGroups/Orbits.lean`, and the group generated by the `q`-th power map,
whose orbits are computed in `TauCeti/FieldTheory/Finite/MinpolyOrbit.lean`.  Over a finite base
field the two agree, because both orbits of a root are the root set of its minimal polynomial.

Consequently the monic irreducible factors of `g` correspond to the orbits of the `q`-th power
map on the roots of `g`, the degree of a factor being the number of elements of the matching
orbit.  This is the form in which the factorization of a polynomial over a finite field is
compared with the cycle type of a permutation of the roots.

## Main results

* `TauCeti.FiniteField.image_val_orbit_gal_eq_orbit`: over a finite base field the Galois orbit
  of a root is its Frobenius orbit.
* `TauCeti.FiniteField.natCard_orbit_eq_natDegree_factor`: along the bijection between orbits and
  monic irreducible factors, the size of an orbit is the degree of the factor.
* `TauCeti.FiniteField.exists_orbit_eq_rootSet_factor`: every monic irreducible factor of `g` is
  the minimal polynomial of a root, its root set is a single Frobenius orbit, and that orbit has
  as many elements as the degree of the factor.

## References

* [S. Lang, *Algebra*][lang2002], Chapter V, §5.
-/

public section

open Polynomial MulAction

namespace TauCeti

namespace FiniteField

variable {F : Type*} [Field F] [Fintype F] {g : F[X]} (E : Type*) [Field E] [Algebra F E]
  [Algebra.IsAlgebraic F E] [Fact ((g.map (algebraMap F E)).Splits)]

/-- **Over a finite base field the Galois orbit of a root is its Frobenius orbit**: both consist
of the roots of its minimal polynomial. -/
theorem image_val_orbit_gal_eq_orbit (x : g.rootSet E) :
    Subtype.val '' orbit g.Gal x
      = orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) (x : E) := by
  rw [image_val_orbit_eq_rootSet_minpoly E x, orbit_eq_rootSet_minpoly F (x : E)]

/-- **The size of a Frobenius orbit on the roots of `g` is the degree of the matching monic
irreducible factor of `g`**, along the bijection `TauCeti.orbitQuotientEquivFactors` between
orbits and factors. -/
theorem natCard_orbit_eq_natDegree_factor (x : g.rootSet E) :
    Nat.card (orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E))
        (x : E))
      = ((orbitQuotientEquivFactors g E (ne_zero_of_mem_rootSet x.2)
        (Quotient.mk _ x) : g.Factors) : F[X]).natDegree := by
  rw [orbitQuotientEquivFactors_apply_mk, natCard_orbit_eq_natDegree_minpoly]

/-- **Every monic irreducible factor of `g` has a root in `E`, whose Frobenius orbit is the root
set of that factor and has as many elements as its degree.** -/
theorem exists_orbit_eq_rootSet_factor (hg : g ≠ 0) (q : g.Factors) :
    ∃ x : g.rootSet E,
      orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) (x : E)
          = (q : F[X]).rootSet E ∧
        Nat.card (orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E))
          (x : E)) = (q : F[X]).natDegree := by
  obtain ⟨x, hx⟩ := exists_mem_rootSet_minpoly_eq E hg q
  exact ⟨x, by rw [orbit_eq_rootSet_minpoly, hx], by rw [natCard_orbit_eq_natDegree_minpoly, hx]⟩

end FiniteField

end TauCeti
