/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Normal.Closure
public import TauCeti.FieldTheory.GaloisGroups.Stabilizer

/-!
# Polynomial Galois groups and normal closures

For an element `x` in a normal extension `E / F`, the splitting field of `minpoly F x`
is isomorphic to the normal closure of `F⟮x⟯` inside `E`. Conjugation by that field
isomorphism identifies the polynomial Galois group with the automorphism group of
the normal closure.

The comparison respects the intrinsic action on roots: a point stabilizer maps to
the subgroup fixing the field generated by the corresponding root. For a separable
minimal polynomial, this subgroup has index `[F(x) : F]`. Thus the group together
with a point stabilizer recovers the simple extension inside its normal closure.

No ordering of roots is chosen.
-/

/- The field isomorphism uses Mathlib's `Polynomial.IsSplittingField.algEquiv`; the
group isomorphism is induced by `AlgEquiv.autCongr`. -/

public section

namespace TauCeti

open IntermediateField Polynomial MulAction

variable {F E : Type*} [Field F] [Field E] [Algebra F E] [Normal F E]

/-- The splitting field of the minimal polynomial of `x` is isomorphic to the normal
closure of the simple extension generated by `x`. -/
noncomputable def splittingFieldEquivNormalClosure (x : E) :
    (minpoly F x).SplittingField ≃ₐ[F] normalClosure F F⟮x⟯ E := by
  letI := isSplittingField_normalClosure_adjoin_simple (F := F) x
  exact (IsSplittingField.algEquiv _ (minpoly F x)).symm

/-- The Galois group of a minimal polynomial is the automorphism group of the normal
closure of the simple extension, via conjugation by the field comparison. -/
noncomputable def galEquivNormalClosure (x : E) :
    (minpoly F x).Gal ≃*
      (normalClosure F F⟮x⟯ E ≃ₐ[F] normalClosure F F⟮x⟯ E) :=
  (splittingFieldEquivNormalClosure (F := F) x).autCongr

/-- The group comparison intertwines evaluation with the field comparison. -/
@[simp]
theorem galEquivNormalClosure_apply (x : E) (σ : (minpoly F x).Gal)
    (y : (minpoly F x).SplittingField) :
    galEquivNormalClosure x σ (splittingFieldEquivNormalClosure (F := F) x y) =
      splittingFieldEquivNormalClosure (F := F) x (σ y) := by
  exact congrArg (fun z ↦ splittingFieldEquivNormalClosure (F := F) x (σ z))
    ((splittingFieldEquivNormalClosure (F := F) x).symm_apply_apply y)

/-- A point stabilizer corresponds to the subgroup fixing the simple field generated
by the corresponding root in the normal closure. The action on the source is the
intrinsic action on the roots in the splitting field. -/
theorem map_stabilizer_galEquivNormalClosure (x : E)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField) :
    (stabilizer (minpoly F x).Gal y).map (galEquivNormalClosure x).toMonoidHom =
      F⟮splittingFieldEquivNormalClosure x (y : (minpoly F x).SplittingField)⟯.fixingSubgroup := by
  ext σ
  rw [Subgroup.mem_map_equiv, mem_stabilizer_iff, Subtype.ext_iff,
    Polynomial.Gal.coe_smul, fixingSubgroup_adjoin_simple, mem_stabilizer_iff]
  have h := galEquivNormalClosure_apply x ((galEquivNormalClosure x).symm σ)
    (y : (minpoly F x).SplittingField)
  rw [MulEquiv.apply_symm_apply] at h
  rw [← (splittingFieldEquivNormalClosure (F := F) x).injective.eq_iff, ← h]
  rfl

/-- There is a root corresponding to the original generator `x`, and its stabilizer
maps to the subgroup fixing the original simple extension inside its normal closure.
In particular, the comparison identifies this field, rather than only an unspecified
conjugate of it. -/
theorem exists_root_map_stabilizer_eq_fixingSubgroup (x : E) :
    ∃ y : (minpoly F x).rootSet (minpoly F x).SplittingField,
      (splittingFieldEquivNormalClosure (F := F) x y : E) = x ∧
      (stabilizer (minpoly F x).Gal y).map (galEquivNormalClosure x).toMonoidHom =
        (F⟮x⟯.restrict (le_normalClosure F⟮x⟯)).fixingSubgroup := by
  let N := normalClosure F F⟮x⟯ E
  let a : N := ⟨x, le_normalClosure F⟮x⟯ (mem_adjoin_simple_self F x)⟩
  have ha : a ∈ (minpoly F x).rootSet N := by
    rw [mem_rootSet_of_ne (minpoly.ne_zero (Algebra.IsIntegral.isIntegral x))]
    apply N.val.injective
    rw [AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
      ← aeval_algHom_apply N.val, map_zero]
    exact minpoly.aeval F x
  let e := splittingFieldEquivNormalClosure (F := F) x
  let y : (minpoly F x).rootSet (minpoly F x).SplittingField :=
    ⟨e.symm a, rootSet_mapsTo e.symm.toAlgHom ha⟩
  refine ⟨y, ?_, ?_⟩
  · exact congrArg Subtype.val (e.apply_symm_apply a)
  · rw [map_stabilizer_galEquivNormalClosure]
    have he : splittingFieldEquivNormalClosure (F := F) x y = a := e.apply_symm_apply a
    rw [he]
    congr 1
    apply lift_injective N
    rw [lift_adjoin_simple, lift_restrict]

/-- When the minimal polynomial is separable, the image of a point stabilizer has
index equal to the degree of the original simple extension. -/
theorem index_map_stabilizer_galEquivNormalClosure (x : E)
    (hsep : (minpoly F x).Separable)
    (y : (minpoly F x).rootSet (minpoly F x).SplittingField) :
    ((stabilizer (minpoly F x).Gal y).map
      (galEquivNormalClosure x).toMonoidHom).index = Module.finrank F F⟮x⟯ := by
  rw [MulEquiv.toMonoidHom_eq_coe, Subgroup.index_map_equiv,
    index_stabilizer_eq_natDegree (minpoly.irreducible (Algebra.IsIntegral.isIntegral x)) hsep,
    adjoin.finrank (Algebra.IsIntegral.isIntegral x)]

end TauCeti
