/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.GroupAction.Quotient
public import Mathlib.GroupTheory.Perm.Cycle.Basic
import Mathlib.GroupTheory.GroupAction.Transitive
import TauCeti.Algebra.Group.Subgroup.Map
import TauCeti.GroupTheory.GroupAction.Burnside

/-!
# Finite bipartite ribbon graphs

A finite bipartite ribbon graph consists of a finite set of edges, finite sets of black and white
vertices, an endpoint of each colour for every edge, and a cyclic order on the edges incident to
each vertex.  The cyclic orders are encoded by two permutations of the common edge set.  Requiring
each incidence fibre to be a single cycle excludes isolated vertices and makes the encoding
extensional: there is no unused cyclic-order data away from the incident edges.

The product of the two vertex rotations determines the face permutation.  Its orbits are the
faces of the associated oriented combinatorial surface, so the Euler characteristic is
`|B| + |W| - |E| + |F|`.  This file also provides morphisms, isomorphisms, automorphisms,
connected components, vertex degrees, and the two incidence degree-sum formulas.

## References

* S. K. Lando, A. K. Zvonkin, *Graphs on Surfaces and Their Applications*, Encyclopaedia of
  Mathematical Sciences 141, Springer, 2004, Chapter 1.
-/

open Equiv

-- The signatures and proof outlines below follow the formal prototype `Suggested.lean` of the
-- Tau Ceti `BelyiMaps` roadmap.

public section

namespace TauCeti

universe u

/-- A finite bipartite ribbon graph, encoded by its two endpoint maps and the cyclic rotations of
the common edge set around black and white vertices. -/
structure BipartiteRibbonGraph : Type (u + 1) where
  /-- The finite type of edges. -/
  E : Type u
  /-- The finite type of black vertices. -/
  B : Type u
  /-- The finite type of white vertices. -/
  W : Type u
  /-- Finiteness of the edge set. -/
  fintypeE : Fintype E
  /-- Finiteness of the black vertex set. -/
  fintypeB : Fintype B
  /-- Finiteness of the white vertex set. -/
  fintypeW : Fintype W
  /-- Decidable equality on edges. -/
  decidableEqE : DecidableEq E
  /-- Decidable equality on black vertices. -/
  decidableEqB : DecidableEq B
  /-- Decidable equality on white vertices. -/
  decidableEqW : DecidableEq W
  /-- The black endpoint of an edge. -/
  blackEnd : E → B
  /-- The white endpoint of an edge. -/
  whiteEnd : E → W
  /-- The cyclic rotation of edges around their black endpoints. -/
  rotB : Equiv.Perm E
  /-- The cyclic rotation of edges around their white endpoints. -/
  rotW : Equiv.Perm E
  /-- Every black vertex is incident to an edge. -/
  blackEnd_surjective : Function.Surjective blackEnd
  /-- Every white vertex is incident to an edge. -/
  whiteEnd_surjective : Function.Surjective whiteEnd
  /-- The black rotation is a single cycle on every black incidence fibre. -/
  isCycleOn_rotB : ∀ b, rotB.IsCycleOn (blackEnd ⁻¹' {b})
  /-- The white rotation is a single cycle on every white incidence fibre. -/
  isCycleOn_rotW : ∀ w, rotW.IsCycleOn (whiteEnd ⁻¹' {w})

namespace BipartiteRibbonGraph

attribute [instance] fintypeE fintypeB fintypeW decidableEqE decidableEqB decidableEqW

variable (Γ : BipartiteRibbonGraph.{u})

/-- The black rotation preserves black endpoints. -/
@[simp]
theorem blackEnd_rotB (e : Γ.E) : Γ.blackEnd (Γ.rotB e) = Γ.blackEnd e := by
  simpa using (Γ.isCycleOn_rotB (Γ.blackEnd e)).apply_mem_iff (x := e)

/-- The white rotation preserves white endpoints. -/
@[simp]
theorem whiteEnd_rotW (e : Γ.E) : Γ.whiteEnd (Γ.rotW e) = Γ.whiteEnd e := by
  simpa using (Γ.isCycleOn_rotW (Γ.whiteEnd e)).apply_mem_iff (x := e)

/-! ### Permutations, faces, and connected components -/

/-- The face permutation of a bipartite ribbon graph.  The inverse matches the product-one
convention `facePerm * rotW * rotB = 1`. -/
def facePerm : Equiv.Perm Γ.E :=
  (Γ.rotW * Γ.rotB)⁻¹

/-- The face permutation is the inverse of the product of the two vertex rotations. -/
theorem facePerm_def : Γ.facePerm = (Γ.rotW * Γ.rotB)⁻¹ := (rfl)

/-- The face permutation follows the product-one convention `facePerm * rotW * rotB = 1`. -/
@[simp]
theorem facePerm_mul : Γ.facePerm * Γ.rotW * Γ.rotB = 1 := by
  simp [facePerm, mul_assoc]

/-- A face is an orbit of the face permutation on edges. -/
abbrev Face : Type u :=
  Quotient (Equiv.Perm.SameCycle.setoid Γ.facePerm)

noncomputable instance : Fintype Γ.Face := Fintype.ofFinite _

/-- The subgroup of edge permutations generated by the two vertex rotations. -/
def rotationGroup : Subgroup (Equiv.Perm Γ.E) :=
  Subgroup.closure {Γ.rotB, Γ.rotW}

/-- The rotation group is generated by the two vertex rotations. -/
theorem closure_pair_eq_rotationGroup :
    Subgroup.closure {Γ.rotB, Γ.rotW} = Γ.rotationGroup := (rfl)

@[simp] theorem rotB_mem_rotationGroup : Γ.rotB ∈ Γ.rotationGroup :=
  Subgroup.subset_closure (by simp)

@[simp] theorem rotW_mem_rotationGroup : Γ.rotW ∈ Γ.rotationGroup :=
  Subgroup.subset_closure (by simp)

/-- A connected component is an orbit of the group generated by the two vertex rotations. -/
abbrev ConnectedComponent : Type u :=
  MulAction.orbitRel.Quotient Γ.rotationGroup Γ.E

noncomputable instance : Fintype Γ.ConnectedComponent := Fintype.ofFinite _

/-- A bipartite ribbon graph is connected when it has an edge and its two rotations act jointly
transitively on the edge set. -/
def IsConnected : Prop :=
  Nonempty Γ.E ∧ MulAction.IsPretransitive Γ.rotationGroup Γ.E

/-- Connectedness of a bipartite ribbon graph: it has an edge, and the two rotations act
jointly transitively on the edges. -/
theorem isConnected_def :
    Γ.IsConnected ↔ Nonempty Γ.E ∧ MulAction.IsPretransitive Γ.rotationGroup Γ.E := Iff.rfl

/-- A ribbon graph is connected exactly when it has one connected component. -/
@[simp]
theorem isConnected_iff_card_connectedComponent_eq_one :
    Γ.IsConnected ↔ Fintype.card Γ.ConnectedComponent = 1 := by
  constructor
  · intro hΓ
    let _ : Nonempty Γ.E := hΓ.1
    let _ : MulAction.IsPretransitive Γ.rotationGroup Γ.E := hΓ.2
    rw [← Nat.card_eq_fintype_card]
    exact card_orbitQuotient_eq_one (G := Γ.rotationGroup) (X := Γ.E)
  · intro hcard
    have hcardPos : 0 < Fintype.card Γ.ConnectedComponent := hcard ▸ Nat.zero_lt_one
    have hE : Nonempty Γ.E :=
      (nonempty_quotient_iff _).mp (Fintype.card_pos_iff.mp hcardPos)
    exact ⟨hE, (MulAction.pretransitive_iff_subsingleton_quotient Γ.rotationGroup Γ.E).mpr
      (Fintype.card_le_one_iff_subsingleton.mp hcard.le)⟩

/-! ### Degrees and Euler characteristic -/

/-- The degree of a black vertex is the number of incident edges. -/
def blackDegree (b : Γ.B) : ℕ :=
  Fintype.card {e : Γ.E // Γ.blackEnd e = b}

/-- The degree of a white vertex is the number of incident edges. -/
def whiteDegree (w : Γ.W) : ℕ :=
  Fintype.card {e : Γ.E // Γ.whiteEnd e = w}

/-- Every black vertex has positive degree. -/
theorem blackDegree_pos (b : Γ.B) : 0 < Γ.blackDegree b := by
  obtain ⟨e, he⟩ := Γ.blackEnd_surjective b
  exact Fintype.card_pos_iff.mpr ⟨⟨e, he⟩⟩

/-- Every white vertex has positive degree. -/
theorem whiteDegree_pos (w : Γ.W) : 0 < Γ.whiteDegree w := by
  obtain ⟨e, he⟩ := Γ.whiteEnd_surjective w
  exact Fintype.card_pos_iff.mpr ⟨⟨e, he⟩⟩

/-- The sum of the black vertex degrees is the number of edges. -/
theorem sum_blackDegree : ∑ b, Γ.blackDegree b = Fintype.card Γ.E := by
  simp only [blackDegree]
  rw [← Fintype.card_sigma]
  exact Fintype.card_congr (Equiv.sigmaFiberEquiv Γ.blackEnd)

/-- The sum of the white vertex degrees is the number of edges. -/
theorem sum_whiteDegree : ∑ w, Γ.whiteDegree w = Fintype.card Γ.E := by
  simp only [whiteDegree]
  rw [← Fintype.card_sigma]
  exact Fintype.card_congr (Equiv.sigmaFiberEquiv Γ.whiteEnd)

/-- The number of faces, counting every orbit of the face permutation. -/
noncomputable def faceCount : ℕ :=
  Fintype.card Γ.Face

/-- The number of faces is the number of orbits of the face permutation. -/
theorem faceCount_def : Γ.faceCount = Fintype.card Γ.Face := (rfl)

/-- The Euler characteristic of the oriented combinatorial surface carried by the ribbon graph. -/
noncomputable def eulerChar : ℤ :=
  Fintype.card Γ.B + Fintype.card Γ.W + Γ.faceCount - Fintype.card Γ.E

/-- The Euler characteristic counts vertices of both colours and faces against edges. -/
theorem eulerChar_def :
    Γ.eulerChar = Fintype.card Γ.B + Fintype.card Γ.W + Γ.faceCount - Fintype.card Γ.E := (rfl)

/-! ### Morphisms and isomorphisms -/

/-- A morphism of bipartite ribbon graphs maps edges and both colours of vertices, preserving
incidences and intertwining both rotations. -/
structure Hom (Δ : BipartiteRibbonGraph) where
  /-- The map on edges. -/
  edge : Γ.E → Δ.E
  /-- The map on black vertices. -/
  black : Γ.B → Δ.B
  /-- The map on white vertices. -/
  white : Γ.W → Δ.W
  /-- Black incidence is preserved. -/
  map_blackEnd : ∀ e, Δ.blackEnd (edge e) = black (Γ.blackEnd e)
  /-- White incidence is preserved. -/
  map_whiteEnd : ∀ e, Δ.whiteEnd (edge e) = white (Γ.whiteEnd e)
  /-- The black rotations are intertwined. -/
  map_rotB : Function.Semiconj edge Γ.rotB Δ.rotB
  /-- The white rotations are intertwined. -/
  map_rotW : Function.Semiconj edge Γ.rotW Δ.rotW

attribute [simp] Hom.map_blackEnd Hom.map_whiteEnd Hom.map_rotB Hom.map_rotW

namespace Hom

variable {Γ Δ Θ Ξ : BipartiteRibbonGraph}

/-- The identity morphism of a bipartite ribbon graph. -/
@[refl]
def id (Γ : BipartiteRibbonGraph) : Γ.Hom Γ where
  edge := fun e ↦ e
  black := fun b ↦ b
  white := fun w ↦ w
  map_blackEnd _ := rfl
  map_whiteEnd _ := rfl
  map_rotB _ := rfl
  map_rotW _ := rfl

/-- Composition of morphisms of bipartite ribbon graphs. -/
def comp (g : Δ.Hom Θ) (f : Γ.Hom Δ) : Γ.Hom Θ where
  edge := g.edge ∘ f.edge
  black := g.black ∘ f.black
  white := g.white ∘ f.white
  map_blackEnd x := by rw [Function.comp_apply, g.map_blackEnd, f.map_blackEnd,
    Function.comp_apply]
  map_whiteEnd x := by rw [Function.comp_apply, g.map_whiteEnd, f.map_whiteEnd,
    Function.comp_apply]
  map_rotB x := by rw [Function.comp_apply, f.map_rotB, g.map_rotB, Function.comp_apply]
  map_rotW x := by rw [Function.comp_apply, f.map_rotW, g.map_rotW, Function.comp_apply]

@[simp] theorem id_edge_apply (e : Γ.E) : (id Γ).edge e = e := (rfl)

@[simp] theorem id_black_apply (b : Γ.B) : (id Γ).black b = b := (rfl)

@[simp] theorem id_white_apply (w : Γ.W) : (id Γ).white w = w := (rfl)

@[simp] theorem comp_edge_apply (g : Δ.Hom Θ) (f : Γ.Hom Δ) (e : Γ.E) :
    (comp g f).edge e = g.edge (f.edge e) := (rfl)

@[simp] theorem comp_black_apply (g : Δ.Hom Θ) (f : Γ.Hom Δ) (b : Γ.B) :
    (comp g f).black b = g.black (f.black b) := (rfl)

@[simp] theorem comp_white_apply (g : Δ.Hom Θ) (f : Γ.Hom Δ) (w : Γ.W) :
    (comp g f).white w = g.white (f.white w) := (rfl)

@[ext]
theorem ext {f g : Γ.Hom Δ} (hedge : f.edge = g.edge) : f = g := by
  have hblack : f.black = g.black := by
    funext b
    obtain ⟨e, rfl⟩ := Γ.blackEnd_surjective b
    rw [← f.map_blackEnd, ← g.map_blackEnd, hedge]
  have hwhite : f.white = g.white := by
    funext w
    obtain ⟨e, rfl⟩ := Γ.whiteEnd_surjective w
    rw [← f.map_whiteEnd, ← g.map_whiteEnd, hedge]
  cases f
  cases g
  simp_all

@[simp] theorem id_comp (f : Γ.Hom Δ) : comp (id Δ) f = f := by
  apply ext
  rfl

@[simp] theorem comp_id (f : Γ.Hom Δ) : comp f (id Γ) = f := by
  apply ext
  rfl

theorem comp_assoc (h : Θ.Hom Ξ) (g : Δ.Hom Θ) (f : Γ.Hom Δ) :
    comp h (comp g f) = comp (comp h g) f := by
  ext
  rfl

end Hom

/-- An isomorphism of bipartite ribbon graphs is an equivalence on edges and on each colour of
vertices that preserves incidences and intertwines both rotations. -/
structure Iso (Δ : BipartiteRibbonGraph) where
  /-- The equivalence on edges. -/
  edge : Γ.E ≃ Δ.E
  /-- The equivalence on black vertices. -/
  black : Γ.B ≃ Δ.B
  /-- The equivalence on white vertices. -/
  white : Γ.W ≃ Δ.W
  /-- Black incidence is preserved. -/
  map_blackEnd : ∀ e, Δ.blackEnd (edge e) = black (Γ.blackEnd e)
  /-- White incidence is preserved. -/
  map_whiteEnd : ∀ e, Δ.whiteEnd (edge e) = white (Γ.whiteEnd e)
  /-- The black rotations are intertwined. -/
  map_rotB : Function.Semiconj edge Γ.rotB Δ.rotB
  /-- The white rotations are intertwined. -/
  map_rotW : Function.Semiconj edge Γ.rotW Δ.rotW

attribute [simp] Iso.map_blackEnd Iso.map_whiteEnd Iso.map_rotB Iso.map_rotW

/-- The morphism underlying an isomorphism of bipartite ribbon graphs. -/
def Iso.toHom {Γ Δ : BipartiteRibbonGraph} (f : Γ.Iso Δ) : Γ.Hom Δ where
  edge := f.edge
  black := f.black
  white := f.white
  map_blackEnd := f.map_blackEnd
  map_whiteEnd := f.map_whiteEnd
  map_rotB := f.map_rotB
  map_rotW := f.map_rotW

@[simp] theorem Iso.toHom_edge_apply {Γ Δ : BipartiteRibbonGraph} (f : Γ.Iso Δ)
    (e : Γ.E) : f.toHom.edge e = f.edge e := (rfl)

@[simp] theorem Iso.toHom_black_apply {Γ Δ : BipartiteRibbonGraph} (f : Γ.Iso Δ)
    (b : Γ.B) : f.toHom.black b = f.black b := (rfl)

@[simp] theorem Iso.toHom_white_apply {Γ Δ : BipartiteRibbonGraph} (f : Γ.Iso Δ)
    (w : Γ.W) : f.toHom.white w = f.white w := (rfl)

namespace Iso

variable {Γ Δ Θ Ξ : BipartiteRibbonGraph}

/-- The identity isomorphism. -/
@[refl]
def refl (Γ : BipartiteRibbonGraph) : Γ.Iso Γ where
  edge := Equiv.refl _
  black := Equiv.refl _
  white := Equiv.refl _
  map_blackEnd _ := rfl
  map_whiteEnd _ := rfl
  map_rotB _ := rfl
  map_rotW _ := rfl

/-- The inverse of a ribbon-graph isomorphism. -/
@[symm]
def symm (f : Γ.Iso Δ) : Δ.Iso Γ where
  edge := f.edge.symm
  black := f.black.symm
  white := f.white.symm
  map_blackEnd x := f.black.injective <| by
    rw [← f.map_blackEnd, f.edge.apply_symm_apply, f.black.apply_symm_apply]
  map_whiteEnd x := f.white.injective <| by
    rw [← f.map_whiteEnd, f.edge.apply_symm_apply, f.white.apply_symm_apply]
  map_rotB x := f.edge.injective <| by
    rw [f.map_rotB, f.edge.apply_symm_apply, f.edge.apply_symm_apply]
  map_rotW x := f.edge.injective <| by
    rw [f.map_rotW, f.edge.apply_symm_apply, f.edge.apply_symm_apply]

/-- Composition of ribbon-graph isomorphisms. -/
@[trans]
def trans (f : Γ.Iso Δ) (g : Δ.Iso Θ) : Γ.Iso Θ where
  edge := f.edge.trans g.edge
  black := f.black.trans g.black
  white := f.white.trans g.white
  map_blackEnd x := by rw [Equiv.trans_apply, g.map_blackEnd, f.map_blackEnd, Equiv.trans_apply]
  map_whiteEnd x := by rw [Equiv.trans_apply, g.map_whiteEnd, f.map_whiteEnd, Equiv.trans_apply]
  map_rotB x := by rw [Equiv.trans_apply, f.map_rotB, g.map_rotB, Equiv.trans_apply]
  map_rotW x := by rw [Equiv.trans_apply, f.map_rotW, g.map_rotW, Equiv.trans_apply]

@[simp] theorem refl_edge_apply (e : Γ.E) : (refl Γ).edge e = e := (rfl)

@[simp] theorem refl_black_apply (b : Γ.B) : (refl Γ).black b = b := (rfl)

@[simp] theorem refl_white_apply (w : Γ.W) : (refl Γ).white w = w := (rfl)

@[simp] theorem symm_edge_apply (f : Γ.Iso Δ) (e : Δ.E) :
    f.symm.edge e = f.edge.symm e := (rfl)

@[simp] theorem symm_black_apply (f : Γ.Iso Δ) (b : Δ.B) :
    f.symm.black b = f.black.symm b := (rfl)

@[simp] theorem symm_white_apply (f : Γ.Iso Δ) (w : Δ.W) :
    f.symm.white w = f.white.symm w := (rfl)

@[simp] theorem trans_edge_apply (f : Γ.Iso Δ) (g : Δ.Iso Θ) (e : Γ.E) :
    (f.trans g).edge e = g.edge (f.edge e) := (rfl)

@[simp] theorem trans_black_apply (f : Γ.Iso Δ) (g : Δ.Iso Θ) (b : Γ.B) :
    (f.trans g).black b = g.black (f.black b) := (rfl)

@[simp] theorem trans_white_apply (f : Γ.Iso Δ) (g : Δ.Iso Θ) (w : Γ.W) :
    (f.trans g).white w = g.white (f.white w) := (rfl)

/-- Relabeling by a ribbon-graph isomorphism conjugates the black rotation to the target's. -/
@[simp]
theorem permCongr_rotB (f : Γ.Iso Δ) : f.edge.permCongr Γ.rotB = Δ.rotB := by
  ext e
  simp only [Equiv.permCongr_apply]
  rw [f.map_rotB, f.edge.apply_symm_apply]

/-- Relabeling by a ribbon-graph isomorphism conjugates the white rotation to the target's. -/
@[simp]
theorem permCongr_rotW (f : Γ.Iso Δ) : f.edge.permCongr Γ.rotW = Δ.rotW := by
  ext e
  simp only [Equiv.permCongr_apply]
  rw [f.map_rotW, f.edge.apply_symm_apply]

/-- Relabeling by a ribbon-graph isomorphism conjugates the face permutation to the target's. -/
@[simp]
theorem permCongr_facePerm (f : Γ.Iso Δ) : f.edge.permCongr Γ.facePerm = Δ.facePerm := by
  rw [facePerm, facePerm]
  calc
    _ = (f.edge.permCongr (Γ.rotW * Γ.rotB))⁻¹ := f.edge.permCongrHom.map_inv _
    _ = _ := by rw [f.edge.permCongr_mul, f.permCongr_rotW, f.permCongr_rotB]

/-- Conjugating by an isomorphism carries the source rotation group onto the target one. -/
@[simp]
theorem map_rotationGroup (f : Γ.Iso Δ) :
    Γ.rotationGroup.map f.edge.permCongrHom = Δ.rotationGroup := by
  rw [rotationGroup, rotationGroup, MonoidHom.map_closure]
  simp

/-- An isomorphism conjugates the groups generated by the two vertex rotations. -/
def rotationGroupEquiv (f : Γ.Iso Δ) : Γ.rotationGroup ≃* Δ.rotationGroup :=
  Subgroup.congrOfMapEq f.edge.permCongrHom f.map_rotationGroup

/-- The edge equivalence is equivariant for the induced equivalence of rotation groups. -/
private def edgeActionHom (f : Γ.Iso Δ) : Γ.E →ₑ[f.rotationGroupEquiv] Δ.E where
  toFun := f.edge
  map_smul' g e := by
    have hgroup : (f.rotationGroupEquiv g : Equiv.Perm Δ.E) =
        f.edge.permCongr (g : Equiv.Perm Γ.E) := by
      calc
        _ = f.edge.permCongrHom (g : Equiv.Perm Γ.E) := by
          rw [rotationGroupEquiv, Subgroup.coe_congrOfMapEq_apply]
        _ = _ := congrFun (Equiv.permCongrHom_coe f.edge) g
    calc
      f.edge (g • e) = f.edge ((g : Equiv.Perm Γ.E) e) := rfl
      _ = f.edge.permCongr (g : Equiv.Perm Γ.E) (f.edge e) := by
        rw [Equiv.permCongr_apply, f.edge.symm_apply_apply]
      _ = f.rotationGroupEquiv g • f.edge e := by
        simpa only [MulAction.subgroup_smul_def, Equiv.Perm.smul_def] using
          congrArg (fun p : Equiv.Perm Δ.E ↦ p (f.edge e)) hgroup.symm

/-- Two edges share a connected component exactly when their images do. -/
private theorem orbitRel_iff (f : Γ.Iso Δ) (x y : Γ.E) :
    MulAction.orbitRel Γ.rotationGroup Γ.E x y ↔
      MulAction.orbitRel Δ.rotationGroup Δ.E (f.edge x) (f.edge y) := by
  rw [MulAction.orbitRel_apply, MulAction.orbitRel_apply,
    MulAction.mem_orbit_iff, MulAction.mem_orbit_iff]
  constructor
  · rintro ⟨g, hg⟩
    refine ⟨f.rotationGroupEquiv g, ?_⟩
    exact (f.edgeActionHom.map_smul' g y).symm.trans (congr_arg f.edge hg)
  · rintro ⟨h, hh⟩
    obtain ⟨g, rfl⟩ := f.rotationGroupEquiv.surjective h
    refine ⟨g, f.edge.injective ?_⟩
    exact (f.edgeActionHom.map_smul' g y).trans hh

/-- An isomorphism relabels the connected components of a bipartite ribbon graph. -/
def connectedComponentEquiv (f : Γ.Iso Δ) : Γ.ConnectedComponent ≃ Δ.ConnectedComponent :=
  Quotient.congr f.edge fun x y ↦ f.orbitRel_iff x y

@[simp]
theorem connectedComponentEquiv_mk (f : Γ.Iso Δ) (e : Γ.E) :
    f.connectedComponentEquiv (Quotient.mk'' e) = Quotient.mk'' (f.edge e) := by
  simp only [connectedComponentEquiv, Quotient.congr_mk]

/-- Connectedness is invariant under isomorphism. -/
theorem isConnected_iff (f : Γ.Iso Δ) : Γ.IsConnected ↔ Δ.IsConnected := by
  exact and_congr f.edge.nonempty_congr
    (MulAction.isPretransitive_congr (f := f.edgeActionHom)
      f.rotationGroupEquiv.surjective f.edge.bijective)

/-- An isomorphism relabels the faces of a bipartite ribbon graph. -/
def faceEquiv (f : Γ.Iso Δ) : Γ.Face ≃ Δ.Face :=
  Quotient.congr f.edge fun x y ↦ by
    rw [← f.permCongr_facePerm]
    constructor
    · rintro ⟨i, hi⟩
      refine ⟨i, ?_⟩
      calc
        ((f.edge.permCongr Γ.facePerm) ^ i) (f.edge x) =
            (f.edge.permCongr (Γ.facePerm ^ i)) (f.edge x) :=
          congrArg (fun p : Equiv.Perm Δ.E ↦ p (f.edge x))
            (f.edge.permCongrHom.toMonoidHom.map_zpow Γ.facePerm i).symm
        _ = f.edge ((Γ.facePerm ^ i) x) := by
          rw [Equiv.permCongr_apply, f.edge.symm_apply_apply]
        _ = f.edge y := congr_arg f.edge hi
    · rintro ⟨i, hi⟩
      refine ⟨i, f.edge.injective ?_⟩
      calc
        f.edge ((Γ.facePerm ^ i) x) =
            (f.edge.permCongr (Γ.facePerm ^ i)) (f.edge x) := by
          rw [Equiv.permCongr_apply, f.edge.symm_apply_apply]
        _ = ((f.edge.permCongr Γ.facePerm) ^ i) (f.edge x) :=
          congrArg (fun p : Equiv.Perm Δ.E ↦ p (f.edge x))
            (f.edge.permCongrHom.toMonoidHom.map_zpow Γ.facePerm i)
        _ = f.edge y := hi

@[simp]
theorem faceEquiv_mk (f : Γ.Iso Δ) (e : Γ.E) :
    f.faceEquiv (Quotient.mk'' e) = Quotient.mk'' (f.edge e) := by
  simp only [faceEquiv, Quotient.congr_mk]

/-- An isomorphism preserves the degree of each black vertex. -/
@[simp]
theorem blackDegree_eq (f : Γ.Iso Δ) (b : Γ.B) :
    Δ.blackDegree (f.black b) = Γ.blackDegree b := by
  symm
  exact Fintype.card_congr <| f.edge.subtypeEquiv fun e ↦ by
    rw [f.map_blackEnd, f.black.injective.eq_iff]

/-- An isomorphism preserves the degree of each white vertex. -/
@[simp]
theorem whiteDegree_eq (f : Γ.Iso Δ) (w : Γ.W) :
    Δ.whiteDegree (f.white w) = Γ.whiteDegree w := by
  symm
  exact Fintype.card_congr <| f.edge.subtypeEquiv fun e ↦ by
    rw [f.map_whiteEnd, f.white.injective.eq_iff]

/-- Isomorphic bipartite ribbon graphs have the same number of faces. -/
theorem faceCount_eq (f : Γ.Iso Δ) : Γ.faceCount = Δ.faceCount := by
  exact Fintype.card_congr f.faceEquiv

/-- Isomorphic bipartite ribbon graphs have the same Euler characteristic. -/
theorem eulerChar_eq (f : Γ.Iso Δ) : Γ.eulerChar = Δ.eulerChar := by
  rw [eulerChar, eulerChar, Fintype.card_congr f.black, Fintype.card_congr f.white,
    Fintype.card_congr f.edge, f.faceCount_eq]

@[ext]
theorem ext {f g : Γ.Iso Δ} (hedge : f.edge = g.edge) : f = g := by
  have hblack : f.black = g.black := by
    apply Equiv.ext
    intro b
    obtain ⟨e, rfl⟩ := Γ.blackEnd_surjective b
    rw [← f.map_blackEnd, ← g.map_blackEnd, hedge]
  have hwhite : f.white = g.white := by
    apply Equiv.ext
    intro w
    obtain ⟨e, rfl⟩ := Γ.whiteEnd_surjective w
    rw [← f.map_whiteEnd, ← g.map_whiteEnd, hedge]
  cases f
  cases g
  simp_all

@[simp] theorem refl_trans (f : Γ.Iso Δ) : (refl Γ).trans f = f := by ext; rfl

@[simp] theorem trans_refl (f : Γ.Iso Δ) : f.trans (refl Δ) = f := by ext; rfl

@[simp] theorem symm_trans_self (f : Γ.Iso Δ) : f.symm.trans f = refl Δ := by
  apply ext
  simpa only [symm, trans, refl] using Equiv.symm_trans_self f.edge

@[simp] theorem trans_symm_self (f : Γ.Iso Δ) : f.trans f.symm = refl Γ := by
  apply ext
  simpa only [symm, trans, refl] using Equiv.self_trans_symm f.edge

theorem trans_assoc (f : Γ.Iso Δ) (g : Δ.Iso Θ) (h : Θ.Iso Ξ) :
    (f.trans g).trans h = f.trans (g.trans h) := by
  ext
  rfl

end Iso

/-- The group of automorphisms of a bipartite ribbon graph. -/
abbrev Aut := Γ.Iso Γ

instance : Group Γ.Aut where
  one := Iso.refl Γ
  mul f g := g.trans f
  inv f := f.symm
  one_mul := Iso.trans_refl
  mul_one := Iso.refl_trans
  mul_assoc _ _ _ := Iso.trans_assoc _ _ _ |>.symm
  inv_mul_cancel := Iso.trans_symm_self

end BipartiteRibbonGraph

end TauCeti
