/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import Mathlib.Data.ZMod.Basic
public import Mathlib.LinearAlgebra.Span.Basic

/-!
# Lines and cyclic subgroups in a `ZMod n`-module

In a module over `ZMod n` the `ZMod n`-multiples of a vector `z` are exactly its `ℤ`-multiples,
since an integer multiple only depends on the residue of the integer. Consequently the line
`ZMod n ∙ z` and the cyclic subgroup generated by `z` inside the multiplicative copy of the
module have the same underlying set, which is what lets a span computation be read as a
membership in `Subgroup.zpowers` and back.

## Main results

* `TauCeti.toAddSubgroup'_zpowers_ofAdd_eq_span`: the cyclic subgroup generated by
  `Multiplicative.ofAdd z`, read back as an additive subgroup, is the line `ZMod n ∙ z`.
-/

public section

namespace TauCeti

/-- **A cyclic subgroup of a `ZMod n`-module is a line.** Read through `Multiplicative`, the
subgroup generated by `z` consists of the `ZMod n`-multiples of `z`. -/
theorem toAddSubgroup'_zpowers_ofAdd_eq_span {n : ℕ} {V : Type*} [AddCommGroup V]
    [Module (ZMod n) V] (z : V) :
    (Subgroup.zpowers (Multiplicative.ofAdd z)).toAddSubgroup' = (ZMod n ∙ z).toAddSubgroup := by
  ext v
  simp only [Subgroup.mem_toAddSubgroup', Subgroup.mem_zpowers_iff,
    Submodule.mem_toAddSubgroup, Submodule.mem_span_singleton]
  constructor
  · rintro ⟨m, hm⟩
    refine ⟨(m : ZMod n), ?_⟩
    apply Multiplicative.ofAdd.injective
    rw [Int.cast_smul_eq_zsmul, ofAdd_zsmul, hm]
  · rintro ⟨a, rfl⟩
    refine ⟨ZMod.cast a, ?_⟩
    rw [← ofAdd_zsmul, ← Int.cast_smul_eq_zsmul (ZMod n), ZMod.intCast_zmod_cast]

end TauCeti
