/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.GenusField
public import TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.Basic
public import TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.Examples
import TauCeti.FieldTheory.IntermediateField.Adjoin.Square

/-!
# The genus field of `ℚ(√-21)`

The fundamental discriminant of `ℚ(√-21)` is `-84 = (-4) · (-3) · (-7)`. Its
prime-discriminant radicands are therefore `-1`, `-3`, and `-7`. This file identifies the
canonical prime-discriminant compositum with the explicit field

`ℚ(i, i√3, i√7) = ℚ(√-1, √-3, √-7)`.

It then proves that the explicit compositum is the genus field of `ℚ(√-21)`.
The relative degree over the quadratic subfield generated by the product of the three roots is
computed in
`TauCeti.NumberTheory.Multiquadratic.MinusTwentyOne.RelativeDegree`.

The prime-discriminant description follows D. A. Cox, *Primes of the Form x² + ny²*, Section
6.A, and F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, Section 2.2.

## Main results

* `TauCeti.Multiquadratic.genusPrimeDiscriminants_neg_twenty_one`: the canonical factors of
  the discriminant are `{-4, -3, -7}`.
* `TauCeti.Multiquadratic.candidateGenusField_neg_twenty_one_eq`: the canonical candidate genus
  field is the explicit compositum `ℚ(i, i√3, i√7)`.
* `TauCeti.Multiquadratic.exists_isGenusField_adjoin_I_sqrt_neg_three_sqrt_neg_seven`:
  the explicit compositum, with a suitable square root of `-21`, is a genus field.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

universe v

/-- The canonical prime-discriminant factorization of the fundamental discriminant of
`ℚ(√-21)` is `-84 = (-4) · (-3) · (-7)`. -/
@[simp] theorem genusPrimeDiscriminants_neg_twenty_one :
    genusPrimeDiscriminants (d := -21) squarefree_neg_twenty_one = {-4, -3, -7} := by
  apply genusPrimeDiscriminants_eq squarefree_neg_twenty_one
  · intro P hP
    fin_cases hP
    · exact isPrimeDiscriminant_neg_four
    · simpa [oddPrimeDiscriminant_of_mod_four_eq_three (by norm_num : 3 % 4 = 3)]
        using isPrimeDiscriminant_oddPrimeDiscriminant (p := 3) (by decide) (by decide)
    · simpa [oddPrimeDiscriminant_of_mod_four_eq_three (by norm_num : 7 % 4 = 3)]
        using isPrimeDiscriminant_oddPrimeDiscriminant (p := 7) (by decide) (by decide)
  · rw [Finset.prod_insert (by decide : (-4 : ℤ) ∉ ({-3, -7} : Finset ℤ)),
      Finset.prod_insert (by decide : (-3 : ℤ) ∉ ({-7} : Finset ℤ)),
      Finset.prod_singleton,
      fundamentalDiscriminant_of_mod_four_ne_one (by decide : (-21 : ℤ) % 4 ≠ 1)]
    ring

/-- **The genus-field compositum for `ℚ(√-21)`.** The canonical compositum of the square
roots of the prime-discriminant radicands is exactly
`ℚ(i, i√3, i√7) = ℚ(√-1, √-3, √-7)`.

Together with `isGenusField_candidateGenusField`, this identifies the genus field of
`ℚ(√-21)`. -/
@[simp] theorem candidateGenusField_neg_twenty_one_eq :
    candidateGenusField (d := -21) squarefree_neg_twenty_one =
      (adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ) : IntermediateField ℚ ℂ) := by
  let hd := squarefree_neg_twenty_one
  have hfac : genusPrimeDiscriminants hd = {-4, -3, -7} :=
    genusPrimeDiscriminants_neg_twenty_one
  -- The canonical roots and the displayed roots need not be definitionally equal, because the
  -- former are chosen using algebraic closure. Their squares agree, so each differs from the
  -- corresponding displayed root by at most a sign; adjoining either family therefore gives the
  -- same field.
  rw [candidateGenusField_def]
  apply TauCeti.IntermediateField.adjoin_eq_adjoin_of_forall_sq_eq
  · rintro _ ⟨P, rfl⟩
    have hP : P.val ∈ ({-4, -3, -7} : Finset ℤ) := by
      rw [← hfac]
      exact P.property
    simp only [Finset.mem_insert, Finset.mem_singleton] at hP
    rcases hP with hP | hP | hP
    · refine ⟨Complex.I, by simp, ?_⟩
      rw [genusFieldRoot_sq, hP]
      norm_num [primeDiscriminantRadicand, Complex.I_sq]
    · refine ⟨sqrtNegThree, by simp, ?_⟩
      rw [genusFieldRoot_sq, hP, sqrtNegThree_sq]
      norm_num [primeDiscriminantRadicand]
    · refine ⟨sqrtNegSeven, by simp, ?_⟩
      rw [genusFieldRoot_sq, hP, sqrtNegSeven_sq]
      norm_num [primeDiscriminantRadicand]
  · intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl
    · let P : {P // P ∈ genusPrimeDiscriminants hd} :=
        ⟨-4, by rw [hfac]; simp⟩
      refine ⟨genusFieldRoot hd P, ⟨P, rfl⟩, ?_⟩
      rw [genusFieldRoot_sq]
      norm_num [P, primeDiscriminantRadicand, Complex.I_sq]
    · let P : {P // P ∈ genusPrimeDiscriminants hd} :=
        ⟨-3, by rw [hfac]; simp⟩
      refine ⟨genusFieldRoot hd P, ⟨P, rfl⟩, ?_⟩
      rw [sqrtNegThree_sq, genusFieldRoot_sq]
      norm_num [P, primeDiscriminantRadicand]
    · let P : {P // P ∈ genusPrimeDiscriminants hd} :=
        ⟨-7, by rw [hfac]; simp⟩
      refine ⟨genusFieldRoot hd P, ⟨P, rfl⟩, ?_⟩
      rw [sqrtNegSeven_sq, genusFieldRoot_sq]
      norm_num [P, primeDiscriminantRadicand]

/-- The explicit degree-eight compositum `ℚ(i, i√3, i√7)` is a number field. -/
instance : NumberField (adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ)) where
  to_finiteDimensional := FiniteDimensional.of_finrank_pos (by
    rw [finrank_adjoin_I_sqrt_neg_three_sqrt_neg_seven]
    norm_num)

/-- The explicit compositum `ℚ(i, i√3, i√7)`, with a suitable square root of `-21`, is the
all-places genus field of `ℚ(√-21)`. -/
theorem exists_isGenusField_adjoin_I_sqrt_neg_three_sqrt_neg_seven :
    ∃ y : adjoin ℚ ({Complex.I, sqrtNegThree, sqrtNegSeven} : Set ℂ),
      IsGenusField.{0, v} (-21) _ y := by
  let hd := squarefree_neg_twenty_one
  -- Generalize the field together with its dependent number-field instance before transporting.
  suffices h : ∀ (F : IntermediateField ℚ ℂ) [NumberField F],
      candidateGenusField hd = F → ∃ y : F, IsGenusField.{0, v} (-21) F y by
    exact h _ candidateGenusField_neg_twenty_one_eq
  intro F _ hF
  subst F
  exact ⟨candidateGenusFieldBaseRoot hd, isGenusField_candidateGenusField hd (by norm_num)⟩

end TauCeti.Multiquadratic
