/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

-- `TauCeti.GL2Borel.mk` is the normal form `TauCeti.jordanGL` is built from.
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Borel
-- `TauCeti.transvectionHom` is the unipotent factor of `TauCeti.scalarUnipotentHom`.
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Transvection
-- `MonoidHom.noncommCoprod` assembles the two commuting factors into one homomorphism. The import
-- must be `public`: `TauCeti.scalarUnipotentHom` is compiled, and the code generator rejects a
-- non-public import of a module whose declarations the compiled body uses.
public import Mathlib.GroupTheory.NoncommCoprod
-- Non-public: the finite-field unit count, the order of `GL₂`, and cancellation in the
-- order-index formula compute the subgroup order and index.
import Mathlib.Algebra.GroupWithZero.Units.Fintype
import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Card
import TauCeti.GroupTheory.Index.Basic

/-!
# The Jordan normal form of `GL₂` and its centralizing subgroup

Alongside the scalars, the split torus and the non-split torus, the fourth family of conjugacy
classes of `GL₂(𝔽_q)` is the **non-semisimple** one, represented by a single Jordan block
`!![a, 1; 0, a]` with a repeated eigenvalue. This file names that normal form,

`TauCeti.jordanGL a b = !![a, b; 0, a]`,

and the subgroup of `GL (Fin 2) R` in which its centralizer will be found: the matrices
`!![x, y; 0, x]`, the invertible elements of the algebra `R[N]` generated by a single nilpotent
Jordan block `N`. That subgroup is the product of the scalar matrices with the unipotent radical
of the Borel subgroup, `Z U`, so it is presented as the image of the homomorphism

`TauCeti.scalarUnipotentHom : Rˣ × Multiplicative R →* GL (Fin 2) R`, `(x, t) ↦ x · (1 + t E₀₁)`,

built from `Matrix.GeneralLinearGroup.scalar` and the root subgroup
`TauCeti.transvectionHom`, whose images commute because scalar matrices are central. The
homomorphism is injective, so the subgroup is a faithful copy of `Rˣ × (R, +)` — the direct
product `Gₘ × Gₐ` — and over a field with `q` elements it has `(q - 1) q` elements.

Nothing here is specific to a finite field, or even to a field: the normal form is stated over an
arbitrary ring, the subgroup and the isomorphism `Rˣ × (R, +) ≃* Z U` over an arbitrary commutative
ring, and only the order count asks for a field, where the nonzero elements are exactly the units.

The parameter `b` is left free rather than fixed to `1`. That costs no generality: a Jordan block
with `b` a unit is conjugate to the standard representative `!![a, 1; 0, a]`
(`TauCeti.isConj_jordanGL`), by the diagonal matrix that rescales the off-diagonal entry. Leaving
it free also lets the degenerate case `b = 0`, the scalar matrix, be named by the same
construction; the results that need `b ≠ 0` say so.

The centralizer computation itself, and the resulting conjugacy class size, are in
`TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Centralizer`, next to the split and non-split
ones.

## Main definitions

* `TauCeti.jordanGL`: the invertible matrix `!![a, b; 0, a]` with a repeated diagonal unit.
* `TauCeti.scalarUnipotentHom`: the homomorphism `(x, t) ↦ !![x, x t; 0, x]` from `Rˣ` times the
  additive group of `R`.
* `TauCeti.GL2ScalarUnipotent`: its range, the subgroup `Z U` of `GL (Fin 2) R`.
* `TauCeti.GL2ScalarUnipotent.mulEquiv`: the resulting isomorphism `Rˣ × Multiplicative R ≃* Z U`.

## Main results

* `TauCeti.jordanGL_eq_scalar_mul_transvectionUnit`: a Jordan block is a scalar matrix times a
  transvection, `M = a (1 + a⁻¹ b E₀₁)`.
* `TauCeti.mem_gl2ScalarUnipotent_iff`: an element of `GL₂` lies in `Z U` exactly when it is
  `!![x, y; 0, x]` for a unit `x`.
* `TauCeti.notMem_range_scalar_jordanGL`: a Jordan block with `b ≠ 0` is not a scalar matrix. Over
  a field that is exactly the hypothesis of `TauCeti.commute_fin_two_iff`, which is what makes such
  a block a regular element of `GL₂`.
* `TauCeti.isConj_jordanGL`: a Jordan block whose off-diagonal entry is a unit is conjugate to
  `!![a, 1; 0, a]`.
* `TauCeti.natCard_gl2ScalarUnipotent`: over a field with `q` elements, `|Z U| = (q - 1) q`.
* `TauCeti.index_gl2ScalarUnipotent`: over a finite field, `[GL₂(F) : Z U] = q² - 1`.

## References

* [Character theory roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/CharacterTheory/README.md),
  Layer 9, "The conjugacy classes (a build target)".
* C. Bonnafé, *Representations of `SL₂(𝔽_q)`* (2011), Chapter 1.
* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lecture 5.2.
-/

public section

open Matrix

namespace TauCeti

universe u

section Ring

variable {R : Type u} [Ring R]

/-- The **Jordan block** `!![a, b; 0, a]` in `GL (Fin 2) R`: the upper-triangular invertible matrix
whose two diagonal entries are the same unit `a`. It is `TauCeti.GL2Borel.mk` with its two diagonal
arguments made equal, so the whole Borel API — the diagonal projection, the determinant, the
splitting `B = T U` — applies to it; for `b = 0` it is the scalar matrix `a` (`jordanGL_zero`).

Over a field and for `b ≠ 0` this is the non-semisimple normal form of `GL₂`, a single Jordan block
with repeated eigenvalue `a`, and it is then one of the four conjugacy class representatives of
`GL₂(𝔽_q)`, alongside the scalars, `TauCeti.diagGL` and `TauCeti.GL2NonSplitTorusHom`. Over an
arbitrary ring no such claim is made: only the matrix shape is. -/
def jordanGL (a : Rˣ) (b : R) : GL (Fin 2) R := GL2Borel.mk a a b

@[simp]
theorem coe_jordanGL (a : Rˣ) (b : R) :
    (jordanGL a b : Matrix (Fin 2) (Fin 2) R) = !![(a : R), b; 0, (a : R)] :=
  GL2Borel.coe_mk a a b

/-- The trace of a Jordan block is twice its repeated eigenvalue. -/
theorem trace_jordanGL (a : Rˣ) (b : R) :
    Matrix.trace (jordanGL a b : Matrix (Fin 2) (Fin 2) R) = 2 * (a : R) := by
  rw [coe_jordanGL, Matrix.trace_fin_two_of, two_mul]

/-- A Jordan block with zero off-diagonal entry is the scalar matrix. -/
@[simp]
theorem jordanGL_zero (a : Rˣ) : jordanGL a (0 : R) = Matrix.GeneralLinearGroup.scalar (Fin 2) a :=
  Units.ext <| Matrix.ext fun i j => by
    fin_cases i <;> fin_cases j <;> simp [Matrix.scalar_apply]

/-- Two Jordan blocks are equal exactly when their parameters are: the diagonal entry and the
upper-right entry can both be read off the matrix. -/
theorem jordanGL_injective2 : Function.Injective2 (jordanGL (R := R)) := by
  intro a b c d h
  have h' : (jordanGL a c : Matrix (Fin 2) (Fin 2) R) = jordanGL b d := congrArg Units.val h
  refine ⟨Units.ext ?_, ?_⟩
  · simpa using congrFun₂ h' 0 0
  · simpa using congrFun₂ h' 0 1

/-- A Jordan block with a nonzero off-diagonal entry is **not** a scalar matrix. Over a field that
is exactly the hypothesis of `TauCeti.commute_fin_two_iff` — it is what makes the block a regular
(cyclic, nonderogatory) element of `GL₂`, with commutant the two-dimensional algebra `F[M]` — and it
is exactly the non-semisimple case, `b ≠ 0`. Over a general ring no such conclusion is claimed
here. -/
theorem notMem_range_scalar_jordanGL {a : Rˣ} {b : R} (hb : b ≠ 0) :
    (jordanGL a b : Matrix (Fin 2) (Fin 2) R) ∉ Set.range (Matrix.scalar (Fin 2)) := by
  rintro ⟨c, hc⟩
  exact hb (by simpa [Matrix.scalar_apply] using (congrFun₂ hc 0 1).symm)

end Ring

section CommRing

variable {R : Type u} [CommRing R]

/-- A Jordan block is upper triangular, so it lies in the Borel subgroup: it is
`TauCeti.GL2Borel.mk` with its two diagonal arguments made equal. -/
theorem jordanGL_mem_gl2Borel (a : Rˣ) (b : R) : jordanGL a b ∈ GL2Borel R :=
  GL2Borel.mk_mem a a b

/-- The determinant of a Jordan block is the square of its repeated eigenvalue. -/
@[simp]
theorem det_jordanGL (a : Rˣ) (b : R) : Matrix.GeneralLinearGroup.det (jordanGL a b) = a ^ 2 := by
  refine Units.ext ?_
  rw [Matrix.GeneralLinearGroup.val_det_apply, coe_jordanGL, Matrix.det_fin_two_of,
    Units.val_pow_eq_pow_val]
  ring

/-- Scalar matrices are central, so they commute with the transvections; this is what lets the two
factors of `TauCeti.scalarUnipotentHom` be coproduced. -/
private theorem commute_scalar_transvectionHom (x : Rˣ) (c : Multiplicative R) :
    Commute (Matrix.GeneralLinearGroup.scalar (Fin 2) x)
      (transvectionHom (A := R) (i := (0 : Fin 2)) (j := 1) zero_ne_one c) :=
  Matrix.GeneralLinearGroup.scalar_commute x _

variable (R) in
/-- The **scalar–unipotent subgroup homomorphism** of `GL₂`: a unit `x` and an element `t` of the
additive group of `R` are sent to `x · (1 + t E₀₁) = !![x, x t; 0, x]`.

It is the coproduct of the scalar matrices `Matrix.GeneralLinearGroup.scalar` and the root subgroup
`TauCeti.transvectionHom` of the root `ε₀ - ε₁`, which commute because scalar matrices are central;
so its image is the internal product `Z U` of the centre with the unipotent radical of the Borel
subgroup. The coordinate `t` is the *unipotent* one rather than the upper-right matrix entry, which
is what makes the assignment multiplicative: the upper-right entries of a product pick up the
diagonal factors, while the unipotent coordinates simply add. -/
def scalarUnipotentHom : Rˣ × Multiplicative R →* GL (Fin 2) R :=
  (Matrix.GeneralLinearGroup.scalar (Fin 2)).noncommCoprod (transvectionHom zero_ne_one)
    commute_scalar_transvectionHom

variable (R) in
/-- The scalar–unipotent homomorphism is the product of its two factors: the scalar matrix of the
first coordinate times the transvection of the second. -/
theorem scalarUnipotentHom_eq_mul (p : Rˣ × Multiplicative R) :
    scalarUnipotentHom R p =
      Matrix.GeneralLinearGroup.scalar (Fin 2) p.1 * transvectionHom zero_ne_one p.2 :=
  MonoidHom.noncommCoprod_apply _ _ _ p

@[simp]
theorem scalarUnipotentHom_apply (p : Rˣ × Multiplicative R) :
    scalarUnipotentHom R p = jordanGL p.1 ((p.1 : R) * Multiplicative.toAdd p.2) := by
  refine Matrix.GeneralLinearGroup.ext fun i j => ?_
  rw [scalarUnipotentHom_eq_mul, Units.val_mul, Matrix.GeneralLinearGroup.coe_scalar,
    transvectionHom_apply, coe_transvectionUnit]
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two, Matrix.transvection, Matrix.scalar_apply,
      Matrix.single_apply, Matrix.one_apply]

/-- **A Jordan block is a scalar matrix times a transvection**:
`!![a, b; 0, a] = a · (1 + a⁻¹ b E₀₁)` is the decomposition `M = a (1 + N)` into a central factor
and a unipotent one. It is `TauCeti.scalarUnipotentHom_eq_mul` read on the Jordan block, and it is
what lets the root subgroup API — conjugation by the diagonal torus, in particular — be applied to
`M`. Over a field it is the multiplicative Jordan decomposition of `M`, whose unipotent part is
trivial exactly when `b = 0`; so it exhibits `M` as non-semisimple precisely in the case
`b ≠ 0`. -/
theorem jordanGL_eq_scalar_mul_transvectionUnit (a : Rˣ) (b : R) :
    jordanGL a b = Matrix.GeneralLinearGroup.scalar (Fin 2) a *
      transvectionUnit (zero_ne_one : (0 : Fin 2) ≠ 1) ((a⁻¹ : Rˣ) * b) := by
  have h := scalarUnipotentHom_eq_mul R (a, Multiplicative.ofAdd ((a⁻¹ : Rˣ) * b))
  rwa [scalarUnipotentHom_apply, transvectionHom_apply, toAdd_ofAdd,
    Units.mul_inv_cancel_left] at h

/-- **Normalizing the off-diagonal entry.** A Jordan block whose off-diagonal entry is a unit is
conjugate, by the diagonal matrix `diag (1, b)`, to the standard representative `!![a, 1; 0, a]`.
The scalar factor of `TauCeti.jordanGL_eq_scalar_mul_transvectionUnit` is central, and conjugation
rescales the parameter of the remaining transvection by the value `1 · b⁻¹` of the root `ε₀ - ε₁`
(`TauCeti.diagGL_mul_transvectionUnit_mul_inv`). Over a field this applies to every `b ≠ 0` through
`Units.mk0`, so leaving `b` free below costs no generality. -/
theorem isConj_jordanGL (a b : Rˣ) : IsConj (jordanGL a (b : R)) (jordanGL a 1) := by
  have hcomm : Commute (diagGL ![1, b]) (Matrix.GeneralLinearGroup.scalar (Fin 2) a) :=
    (Matrix.GeneralLinearGroup.scalar_commute a _).symm
  -- The root `ε₀ - ε₁` takes the value `1 · b⁻¹` at `diag (1, b)`, which cancels the `b`.
  have hpar : ((![1, b] 0 : Rˣ) : R) * ((a⁻¹ : Rˣ) * b) * (((![1, b] 1)⁻¹ : Rˣ) : R)
      = ((a⁻¹ : Rˣ) : R) * 1 := by simp
  refine isConj_iff.mpr ⟨diagGL ![1, b], ?_⟩
  rw [jordanGL_eq_scalar_mul_transvectionUnit, jordanGL_eq_scalar_mul_transvectionUnit,
    hcomm.left_comm, mul_assoc, diagGL_mul_transvectionUnit_mul_inv, hpar]

/-- The scalar–unipotent homomorphism is injective: the pair `(x, t)` is read back off the matrix
`!![x, x t; 0, x]` as its upper-left entry and the quotient of its two top entries. So `Z U` is a
faithful copy of `Rˣ × (R, +)`, not a quotient of it. -/
theorem scalarUnipotentHom_injective : Function.Injective (scalarUnipotentHom R) := by
  rintro ⟨x, s⟩ ⟨y, t⟩ h
  rw [scalarUnipotentHom_apply, scalarUnipotentHom_apply] at h
  obtain ⟨rfl, hst⟩ := jordanGL_injective2 h
  exact Prod.ext rfl (Multiplicative.toAdd.injective ((Units.mul_right_inj x).mp hst))

variable (R) in
/-- The **scalar–unipotent subgroup** `Z U` of `GL (Fin 2) R`: the invertible matrices
`!![x, y; 0, x]`, that is, the units of the commutative subalgebra `R[N]` generated by a nilpotent
Jordan block. It is the product of the centre with the unipotent radical of the Borel subgroup, and
it is the centralizer of every Jordan block `!![a, b; 0, a]` whose off-diagonal entry `b` is
left-regular — over a field, every `b ≠ 0` (`TauCeti.centralizer_jordanGL`). -/
def GL2ScalarUnipotent : Subgroup (GL (Fin 2) R) := (scalarUnipotentHom R).range

/-- The scalar–unipotent subgroup is **abelian**: it is the image of the commutative group
`Rˣ × Multiplicative R`. -/
instance : IsMulCommutative (GL2ScalarUnipotent R) :=
  Subgroup.range_isMulCommutative (scalarUnipotentHom R)

/-- **Normal form for the scalar–unipotent subgroup**: its elements are exactly the invertible
matrices `!![x, y; 0, x]` with equal diagonal entries. The upper-right entry `y` is unconstrained;
it is the product of the diagonal unit with the unipotent coordinate. -/
@[simp]
theorem mem_gl2ScalarUnipotent_iff {g : GL (Fin 2) R} :
    g ∈ GL2ScalarUnipotent R ↔ ∃ (x : Rˣ) (y : R), g = jordanGL x y := by
  constructor
  · rintro ⟨p, rfl⟩
    exact ⟨p.1, _, scalarUnipotentHom_apply p⟩
  · rintro ⟨x, y, rfl⟩
    refine ⟨(x, Multiplicative.ofAdd ((x⁻¹ : Rˣ) * y)), ?_⟩
    rw [scalarUnipotentHom_apply, toAdd_ofAdd, Units.mul_inv_cancel_left]

/-- Every Jordan block lies in the scalar–unipotent subgroup, the degenerate case `b = 0` — the
scalar matrix — included. -/
theorem jordanGL_mem_gl2ScalarUnipotent (x : Rˣ) (y : R) :
    jordanGL x y ∈ GL2ScalarUnipotent R :=
  mem_gl2ScalarUnipotent_iff.mpr ⟨x, y, rfl⟩

variable (R) in
/-- **The scalar–unipotent subgroup is `Gₘ × Gₐ`**: the multiplicative group of `R` times its
additive group, the scalar and unipotent coordinates. This is the isomorphism the order count runs
on. -/
noncomputable def GL2ScalarUnipotent.mulEquiv :
    Rˣ × Multiplicative R ≃* GL2ScalarUnipotent R :=
  MonoidHom.ofInjective scalarUnipotentHom_injective

/-- The isomorphism `Rˣ × (R, +) ≃* Z U` is `TauCeti.scalarUnipotentHom` with its codomain cut
down, so no unfolding of `MonoidHom.ofInjective` is needed to compute with it. This is not a `simp`
lemma because its right-hand side is not in `simp`-normal form: `simp` rewrites it further by
`TauCeti.scalarUnipotentHom_apply`, which is what the companion
`TauCeti.GL2ScalarUnipotent.coe_mulEquiv_apply_eq_jordanGL` states. -/
theorem GL2ScalarUnipotent.coe_mulEquiv_apply (p : Rˣ × Multiplicative R) :
    (mulEquiv R p : GL (Fin 2) R) = scalarUnipotentHom R p :=
  MonoidHom.ofInjective_apply scalarUnipotentHom_injective

/-- The matrix underlying `TauCeti.GL2ScalarUnipotent.mulEquiv R p` is the Jordan block
`!![x, x t; 0, x]` read off the pair `p = (x, t)`. -/
@[simp, grind =]
theorem GL2ScalarUnipotent.coe_mulEquiv_apply_eq_jordanGL (p : Rˣ × Multiplicative R) :
    (mulEquiv R p : GL (Fin 2) R) = jordanGL p.1 ((p.1 : R) * Multiplicative.toAdd p.2) := by
  rw [coe_mulEquiv_apply, scalarUnipotentHom_apply]

end CommRing

/-- **The order of the scalar–unipotent subgroup**: over a field with `q` elements it has
`(q - 1) q` elements, one invertible scalar and one free unipotent coordinate. No finiteness is
assumed: over an infinite field both sides vanish. -/
theorem natCard_gl2ScalarUnipotent (F : Type u) [Field F] :
    Nat.card (GL2ScalarUnipotent F) = (Nat.card F - 1) * Nat.card F := by
  rw [← Nat.card_congr (GL2ScalarUnipotent.mulEquiv F).toEquiv, Nat.card_prod, Nat.card_units,
    Nat.card_congr Multiplicative.toAdd]

/-- **The index of the scalar–unipotent subgroup** in `GL₂(F)` is `q² - 1` over a finite
field with `q` elements. -/
theorem index_gl2ScalarUnipotent (F : Type u) [Field F] [Fintype F] :
    (GL2ScalarUnipotent F).index = Fintype.card F ^ 2 - 1 := by
  have hpos : 0 < (Fintype.card F - 1) * Fintype.card F :=
    Nat.mul_pos (Nat.sub_pos_of_lt (Fintype.one_lt_card (α := F))) Fintype.card_pos
  refine index_eq_of_natCard_eq_mul hpos ?_ ?_
  · rw [natCard_gl2ScalarUnipotent, Nat.card_eq_fintype_card]
  · rw [natCard_GL_fin_two_eq_sq_sub_one_mul]
    ac_rfl

end TauCeti
