/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Nonarchimedean.Completion.Basic
public import TauCeti.Topology.Algebra.Ring.Ideal

/-!
# Closed proper ideals survive completion

For a closed proper ideal `J` of a topological commutative ring `A`, the ideal generated by its
image in the separated completion `Â` remains proper. No separation or completeness assumption
on `A` is needed.

The map `A → (A / J)̂` extends through `Â`, yielding `Â → (A / J)̂`. This map kills the
extended ideal, while closedness and properness of `J` ensure that the target is nonzero.

## Main results

* `TauCeti.map_completion_ne_top_of_isClosed`: a closed proper ideal stays proper in the completion.

This supplies the completion lemma for the proper-ideal criterion in rational covers
(Wedhorn's Corollary 8.32).

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Corollary 8.32.

## Provenance

AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0), branch `dev/adic-spaces` at commit
`37bbdaeb9ad9e3bc9f0d660feadc2779e455a91c`, file
`projects/AdicSpaces/Adic spaces/IdealLocalizationCompletion.lean`, was consulted to compare
completion prerequisites. The closed-ideal argument here is independent; no code is ported.
-/

public section

namespace TauCeti

open Set Topology UniformSpace

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [IsTopologicalRing A]

/-- A closed proper ideal remains proper after extension to the separated completion.

The ideal need not be prime, and the original ring need not be Hausdorff or complete. -/
theorem map_completion_ne_top_of_isClosed {J : Ideal A} (hclosed : IsClosed (J : Set A))
    (hJ : J ≠ ⊤) : Ideal.map (Completion.coeRingHom : A →+* Completion A) J ≠ ⊤ := by
  -- Extend the quotient map to the completion of the quotient, where `1` remains nonzero.
  let q : A →+* A ⧸ J := Ideal.Quotient.mk J
  let _ : UniformSpace (A ⧸ J) := IsTopologicalAddGroup.rightUniformSpace _
  have _ : IsUniformAddGroup (A ⧸ J) := isUniformAddGroup_of_addCommGroup
  let f : A →+* Completion (A ⧸ J) := Completion.coeRingHom.comp q
  let F : Completion A →+* Completion (A ⧸ J) :=
    Completion.extensionHom f (Completion.continuous_coeRingHom.comp continuous_quotient_mk')
  have : T1Space (A ⧸ J) := (Ideal.Quotient.t1Space_iff J).mpr hclosed
  have : Nontrivial (A ⧸ J) := Ideal.Quotient.nontrivial_iff.mpr hJ
  have honeCompletion : (1 : Completion (A ⧸ J)) ≠ 0 := by
    simpa only [Completion.coe_one, Completion.coe_zero] using
      (Completion.coe_inj (α := A ⧸ J)).not.mpr one_ne_zero
  have hle : Ideal.map (Completion.coeRingHom : A →+* Completion A) J ≤
      RingHom.ker F := by
    rw [Ideal.map_le_iff_le_comap]
    intro a ha
    rw [Ideal.mem_comap, RingHom.mem_ker]
    -- Present the completion map as a coercion so `extensionHom_coe` matches; rewriting
    -- `coe_coeRingHom` here also rewrites inside the dependent continuity proof.
    change Completion.extensionHom f
      (Completion.continuous_coeRingHom.comp continuous_quotient_mk')
        (a : Completion A) = 0
    rw [Completion.extensionHom_coe]
    simp [f, q, Ideal.Quotient.eq_zero_iff_mem, ha]
  intro htop
  have honeKer : (1 : Completion A) ∈ RingHom.ker F := by
    apply hle
    rw [htop]
    exact Submodule.mem_top
  rw [RingHom.mem_ker] at honeKer
  exact honeCompletion (by simpa using honeKer)

end TauCeti

end
