/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.Surjective
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Support
public import TauCeti.RingTheory.Valuation.Continuous.Completion
public import TauCeti.RingTheory.Huber.LocalizationTopology.Pi

/-!
# Proper ideals on rational localisations

For a point `v` of the rational subset `R(T/s)`, the extension of `v` to the algebraic
localisation at `s` has support containing the extension of `supp v`. The extended valuation is
continuous for the localisation topology, so its support remains proper after passing to the
separated completion `A⟨T/s⟩`. Consequently the ideal generated by `supp v` in the completed
rational localisation is proper.

For a standard rational cover `(R(T/t))_{t ∈ T}`, this supplies the faithfulness step in
Wedhorn's Corollary 8.32. Given a proper ideal `J` of `A`, choose a point of
`Spa(A,A⁺)` whose support contains it, and choose a chart of the cover containing the point.
Then `J` remains proper in that chart. Combined with the flatness of
the chart maps and finite-product flatness, this is exactly the proper-ideal criterion for the
comparison map to be faithfully flat.

## Main results

* `TauCeti.ValuationSpectrum.map_supp_toCompletionLoc_ne_top`: a point in `R(T/s)` has proper
  extended support in `A⟨T/s⟩`.
* `TauCeti.ValuationSpectrum.exists_map_toCompletionLoc_ne_top_of_span_eq_top`: every proper ideal
  remains proper on some member of a standard rational cover.
* `TauCeti.ValuationSpectrum.map_rationalLocalizationPiHom_ne_top_of_span_eq_top`: every proper
  ideal remains proper under the comparison map to the product of the completed localisations.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Corollary 8.32.

## Provenance

AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0), branch `dev/adic-spaces` at commit
`37bbdaeb9ad9e3bc9f0d660feadc2779e455a91c`, file
`projects/AdicSpaces/Adic spaces/Cor832.lean`, was consulted. That file assumes a prime-lifting
hypothesis for each chart; the continuous-support proof discharging properness here is independent,
and no code is ported.
-/

public section

namespace TauCeti.ValuationSpectrum

open Set Topology
open TauCeti.Huber TauCeti.Huber.PairOfDefinition TauCeti.Localization

section RationalLocalization

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **The support of a point in `R(T/s)` remains proper in `A⟨T/s⟩`.**

Here `S` is an algebraic localisation at `s`, equipped with the topology specified by `P`, `T`,
and `hden`. The ring of definition must lie in `Aplus`; membership in `R(T/s)` supplies
continuity, the sub-unit condition `v a ≤ 1` for `a ∈ A⁺`, and the inequalities
`v(t) ≤ v(s) ≠ 0` for `t ∈ T`. -/
theorem map_supp_toCompletionLoc_ne_top (P : PairOfDefinition A) (Aplus : Subring A)
    (hP : P.ringOfDefinition ≤ Aplus) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {v : Spv A}
    (hv : v ∈ rationalSubset Aplus T s) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Ideal.map (toCompletionLoc P T s S hden) v.supp ≠ ⊤ := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  have hs : v.valuation s ≠ 0 := valuation_ne_zero_of_mem_rationalSubset hv
  -- Extend the point continuously to the algebraic localisation and use its closed support.
  let w := v.valuation.extendToLocalization
    (Valuation.powers_le_supp_primeCompl hs) S
  have hwContinuousLoc :
      @Valuation.IsContinuous S _ (locTopology P T s S hden) _ _ w :=
    isContinuous_extendToLocalization_of_mem_rationalSubset P Aplus hP T s S hden hv
  have hwContinuous : w.IsContinuous := by
    rwa [← locUniformSpace_toTopologicalSpace P T s S hden] at hwContinuousLoc
  have hwProper :
      Ideal.map (UniformSpace.Completion.coeRingHom : S →+* UniformSpace.Completion S)
        w.supp ≠ ⊤ :=
    map_supp_completion_ne_top_of_isContinuous hwContinuous
  have hsuppMap : Ideal.map (algebraMap A S) v.supp ≤ w.supp := by
    rw [Ideal.map_le_iff_le_comap]
    intro a ha
    rw [Ideal.mem_comap, Valuation.mem_supp_iff]
    dsimp only [w]
    rw [Valuation.extendToLocalization_apply_map_apply]
    exact (v.valuation.mem_supp_iff a).mp (v.supp_eq_valuation_supp ▸ ha)
  have hle : Ideal.map (toCompletionLoc P T s S hden) v.supp ≤
      Ideal.map (UniformSpace.Completion.coeRingHom : S →+* UniformSpace.Completion S)
        w.supp := by
    rw [Ideal.map_le_iff_le_comap]
    intro a ha
    rw [Ideal.mem_comap, toCompletionLoc_apply]
    exact Ideal.mem_map_of_mem _ (hsuppMap (Ideal.mem_map_of_mem _ ha))
  exact ne_top_of_le_ne_top hwProper hle

end RationalLocalization

section StandardCover

variable {A : Type*} [CommRing A] [UniformSpace A] [T2Space A] [CompleteSpace A]
  [IsTopologicalRing A] [IsUniformAddGroup A] [IsHuberRing A]

/-- **Every proper ideal remains proper on some chart of a standard rational cover.**

The ring is a complete Hausdorff Huber ring, and `Aplus` is a ring of integral elements
containing the chosen ring of definition. The condition that `T` generates the unit ideal makes
the rational subsets `R(T/t)` a cover of `Spa(A,A⁺)`; `hden` supplies each localisation topology.
The ideal `J` need only be proper, with no closedness assumption. This is the faithfulness
half of Wedhorn's Corollary 8.32, before finite-product flatness is combined with it. -/
theorem exists_map_toCompletionLoc_ne_top_of_span_eq_top (P : PairOfDefinition A)
    (Aplus : Subring A) (hplus : IsRingOfIntegralElements Aplus)
    (hP : P.ringOfDefinition ≤ Aplus) (T : Finset A)
    (S : ∀ _ : T, Type*) [∀ t : T, CommRing (S t)] [∀ t : T, Algebra A (S t)]
    [∀ t : T, IsLocalization.Away (t : A) (S t)]
    (hden : ∀ t : T, HasDenominatorPower P T (t : A) (S t))
    (hspan : Ideal.span (T : Set A) = ⊤) {J : Ideal A} (hJ : J ≠ ⊤) :
    ∃ t : T,
      letI := locUniformSpace P T (t : A) (S t) (hden t)
      letI := isUniformAddGroup_locUniformSpace P T (t : A) (S t) (hden t)
      letI := isTopologicalRing_locUniformSpace P T (t : A) (S t) (hden t)
      Ideal.map (toCompletionLoc P T (t : A) (S t) (hden t)) J ≠ ⊤ := by
  obtain ⟨v, hvSpa, hJv⟩ := exists_mem_spa_le_supp_of_ne_top Aplus hplus hJ
  have hvCover : v ∈ ⋃ t ∈ T, rationalSubset Aplus T t := by
    rw [← spa_eq_biUnion_rationalSubset_of_span_eq_top Aplus hspan]
    exact hvSpa
  obtain ⟨t, ht, hvt⟩ := Set.mem_iUnion₂.mp hvCover
  let t' : T := ⟨t, ht⟩
  refine ⟨t', ?_⟩
  let _ := locUniformSpace P T (t' : A) (S t') (hden t')
  have _ := isUniformAddGroup_locUniformSpace P T (t' : A) (S t') (hden t')
  have _ := isTopologicalRing_locUniformSpace P T (t' : A) (S t') (hden t')
  exact ne_top_of_le_ne_top
    (map_supp_toCompletionLoc_ne_top P Aplus hP T (t' : A) (S t') (hden t') hvt)
    (Ideal.map_mono hJv)

/-- A proper ideal stays proper under the comparison map for a standard rational cover.
Together with flatness of the product, this is the ideal criterion for faithful flatness
in Wedhorn's Corollary 8.32. No closedness assumption on the ideal is required. -/
theorem map_rationalLocalizationPiHom_ne_top_of_span_eq_top (P : PairOfDefinition A)
    (Aplus : Subring A) (hplus : IsRingOfIntegralElements Aplus)
    (hP : P.ringOfDefinition ≤ Aplus) (T : Finset A)
    (S : ∀ _ : T, Type*) [∀ t : T, CommRing (S t)] [∀ t : T, Algebra A (S t)]
    [∀ t : T, IsLocalization.Away (t : A) (S t)]
    (hden : ∀ t : T, HasDenominatorPower P T (t : A) (S t))
    (hspan : Ideal.span (T : Set A) = ⊤) {J : Ideal A} (hJ : J ≠ ⊤) :
    letI : ∀ t : T, UniformSpace (S t) := fun t ↦ locUniformSpace P T (t : A) (S t) (hden t)
    letI : ∀ t : T, IsUniformAddGroup (S t) := fun t ↦
      isUniformAddGroup_locUniformSpace P T (t : A) (S t) (hden t)
    letI : ∀ t : T, IsTopologicalRing (S t) := fun t ↦
      isTopologicalRing_locUniformSpace P T (t : A) (S t) (hden t)
    Ideal.map (rationalLocalizationPiHom P T S hden) J ≠ ⊤ := by
  let : ∀ t : T, UniformSpace (S t) := fun t ↦ locUniformSpace P T (t : A) (S t) (hden t)
  have : ∀ t : T, IsUniformAddGroup (S t) := fun t ↦
    isUniformAddGroup_locUniformSpace P T (t : A) (S t) (hden t)
  have : ∀ t : T, IsTopologicalRing (S t) := fun t ↦
    isTopologicalRing_locUniformSpace P T (t : A) (S t) (hden t)
  obtain ⟨t, ht⟩ := exists_map_toCompletionLoc_ne_top_of_span_eq_top
    P Aplus hplus hP T S hden hspan hJ
  have hcomp : (Pi.evalRingHom (fun t : T ↦ UniformSpace.Completion (S t)) t).comp
      (rationalLocalizationPiHom P T S hden) = toCompletionLoc P T (t : A) (S t) (hden t) := by
    ext a
    exact rationalLocalizationPiHom_apply P T S hden a t
  intro htop
  apply ht
  rw [← hcomp, ← Ideal.map_map, htop, Ideal.map_top]

end StandardCover

end TauCeti.ValuationSpectrum

end
