/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.HopfIdealPoints.Presentation
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.GroupScheme

/-!
# Presented points of the pinned Geck carrier

`TauCeti.DynkinType.geckPointsPresentation` presents the matrix points of the pinned Geck
carrier by its integral defining Hopf ideal. The shared
`GeneralLinear.IntegralPointsPresentation` API supplies maps of value rings, their functoriality,
and the representing equivalence with quotient-algebra points. This file proves that those maps
preserve the pinned root subgroups and weight torus.

The Geck weights span the root lattice rather than, in general, the full character lattice.
This presentation does not identify the carrier with the simply connected group or its points
with the elementary subgroup generated by its root subgroups.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

namespace TauCeti.DynkinType

universe v v'

noncomputable section

-- Matrices form a Lie ring through their commutator, which is how Geck's construction reads them.
attribute [local instance 100] LieRing.ofAssociativeRing

attribute [local instance] TauCeti.moduleNNRat

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable (t : DynkinType) (ht : t.Valid)

/-- The matrix points of the pinned Geck carrier, presented by its integral defining Hopf ideal. -/
abbrev geckPointsPresentation (A : Type v) [CommRing A] :
    GeneralLinear.IntegralPointsPresentation (t.geckDim ht) (t.geckDefiningIdeal ht) A :=
  ⟨t.geckPoints ht A, t.geckPoints_def ht A⟩

variable {A : Type v} {B : Type v'} [CommRing A] [CommRing B]

/-- **The induced map carries a numbered root-subgroup point along the homomorphism of value
rings.** -/
@[simp]
theorem map_geckRootSubgroupPoints (f : A →+* B)
    (i : Fin t.rank ⊕ Fin t.rank) (u : Multiplicative A) :
    (t.geckPointsPresentation ht A).map (t.geckPointsPresentation ht B) f
      (t.geckRootSubgroupPoints ht i A u) =
      t.geckRootSubgroupPoints ht i B
        (Multiplicative.ofAdd (f (Multiplicative.toAdd u))) := by
  refine Subtype.ext ?_
  rw [GeneralLinear.IntegralPointsPresentation.coe_map,
    coe_geckRootSubgroupPoints, coe_geckRootSubgroupPoints,
    TauCeti.UniversalEnvelopingAlgebra.map_kostantRootSubgroupMatrix,
    AdditiveGroup.mapValue_gaPointsMulEquiv_symm_apply, RingHom.toIntAlgHom_apply]

/-- **The induced map carries a point of the pinned Geck weight torus along the homomorphism of
value rings**, parameter by parameter. -/
@[simp]
theorem map_geckWeightTorusPoints (f : A →+* B) (s : Fin t.rank → Aˣ) :
    (t.geckPointsPresentation ht A).map (t.geckPointsPresentation ht B) f
      (t.geckWeightTorusPoints ht A s) =
      t.geckWeightTorusPoints ht B (fun j => Units.map (f : A →* B) (s j)) := by
  refine Subtype.ext ?_
  rw [GeneralLinear.IntegralPointsPresentation.coe_map,
    coe_geckWeightTorusPoints, coe_geckWeightTorusPoints]
  exact TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusMatrix
    (M := (t.geckCoordinateLattice ht).toAddSubgroup) (b := t.geckCoordinateBasisFin ht)
    (wt := t.geckWeightFin ht) f s

end

end TauCeti.DynkinType
