/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.Frobenius
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.GraphAutomorphism

/-!
# The graph-twisted Frobenius of the pinned Geck carrier

For a valid Dynkin type `t` and a symmetry `σ` of its Bourbaki-numbered Dynkin diagram, the points
of `TauCeti.DynkinType.geckGroupScheme` over a value ring of exponential characteristic `p` carry
two commuting endomorphisms: the `q`-power Frobenius `TauCeti.DynkinType.geckFrobenius`, with
`q = p ^ k`, and the graph automorphism `TauCeti.DynkinType.geckGraphAutPoints`. This file records
that they commute and composes them.

The composite `TauCeti.DynkinType.geckTwistedFrobenius` acts on the pinned generating families by

```text
F (xᵢ(u)) = x_{σ i}(u ^ q),        F (t(s)) = t(s ^ q ∘ σ⁻¹),
```

with `i` ranging over the numbered raising and lowering generators. The first equation is the
defining relation of a graph-twisted Steinberg endomorphism on the simple root subgroups: the
parameter is raised to the `q`-th power and the numbering is permuted by the diagram symmetry,
with no sign or scaling attached, which is what a pinning normalizes away.

Commutation is a special case of naturality: the Frobenius endomorphism is the map on points
induced by the iterated Frobenius of the value ring, and the graph automorphism is natural in that
ring because it is conjugation by a permutation matrix whose entries are `0` and `1`, and which is
therefore fixed entrywise by any ring map. So the commutation is
`TauCeti.DynkinType.map_comp_geckGraphAutPoints`, read at the iterated Frobenius.

Because the two factors commute, the powers of the composite separate: the `m`-th power is
`γ ^ m ∘ Frob_(q ^ m)`, so a symmetry of order dividing `m` makes it the plain `q ^ m`-power
Frobenius, the Frobenius at exponent `k * m`. Reading that on fixed subgroups gives the containment

```text
G(A)^(γ ∘ Frob_q) ≤ G(A)^(Frob_(q ^ m)) = G(frobeniusFixedSubring A p (k * m)),
```

over any value ring `A` of exponential characteristic `p` and any `m` annihilating the symmetry.
At the permitted value `m = 0` the iterate is the identity and its fixed subring is all of `A`, so
the containment is vacuous; for `p` prime, `0 < k`, `0 < m` and `A` an algebraic closure of
`ZMod p`, the subring is the field of `q ^ m` elements, the right-hand side reads `G(𝔽_(q ^ m))`,
and the containment is the carrier-level form of the classical statement that a graph-twisted group
of Lie type sits inside the untwisted group over the degree-`m` extension of its field of
definition, with `m = 2` for `²Aₙ`, `²Dₙ` and `²E₆` and `m = 3` for `³D₄`.
The reverse containment is false: the twisted fixed points are not in general fixed by
either factor, and only the easy half, that a point fixed by both factors is fixed by the
composite, holds.

Two limitations carry over from the two factors. This is the twisted Frobenius of the *carrier*,
not of the elementary subgroup its root subgroups generate, and the Geck weights span the root
lattice rather than, in general, the full character lattice, so this carrier is not yet the simply
connected one a finite group of Lie type is built from. Nothing below asserts that any subgroup
appearing here is finite, is simple, or is a named finite group.

The first of those limitations is why the results below are proved here rather than transported.
`TauCeti.UniversalEnvelopingAlgebra.kostantElementarySteinberg` is the same composite on the
elementary subgroup generated by the Kostant root subgroups, and carries the same power and
fixed-subgroup statements; but the elementary subgroup is not known to exhaust the points of the
carrier, that being the generation theorem
`TauCeti/Algebra/Lie/UniversalEnveloping/Kostant/RootSubgroup/Scheme/Points.lean` records as
missing, so neither family of statements implies the other. What the two share is the group-level
input, `TauCeti.fixedSubgroup_le_fixedSubgroup_pow` and
`TauCeti.fixedSubgroup_inf_fixedSubgroup_le_fixedSubgroup_comp`, which is used here rather than
reproved.

## Main definitions

* `TauCeti.DynkinType.geckTwistedFrobenius`: the graph-twisted `p ^ k`-power Frobenius on the
  points of the pinned Geck carrier.

## Main results

* `TauCeti.DynkinType.geckGraphAutPoints_comp_geckFrobenius`: the graph automorphism commutes with
  the Frobenius.
* `TauCeti.DynkinType.geckTwistedFrobenius_eq_geckFrobenius_comp`: the twisted Frobenius is that
  composite in either order.
* `TauCeti.DynkinType.coe_geckTwistedFrobenius`: the twisted Frobenius conjugates the entrywise
  Frobenius by the pinned symmetry matrix.
* `TauCeti.DynkinType.geckTwistedFrobenius_geckRootSubgroupMatrix`: the defining equation on the
  pinned numbered root subgroups.
* `TauCeti.DynkinType.geckTwistedFrobenius_geckWeightTorusPoints` and
  `TauCeti.DynkinType.geckTwistedFrobenius_geckTorusMatrix`: the equation on the pinned weight
  torus, on the represented torus homomorphism and on the matrix that homomorphism produces.
* `TauCeti.DynkinType.geckFrobenius_pow` and `TauCeti.DynkinType.geckTwistedFrobenius_pow`: the
  powers of the two endomorphisms, the second separating into `γ ^ m ∘ Frob_(q ^ m)`.
* `TauCeti.DynkinType.geckTwistedFrobenius_pow_eq_geckFrobenius`: a symmetry of order dividing `m`
  makes the `m`-th power the plain Frobenius `Frob_(q ^ m)`, the order relation a graph-twisted
  Steinberg map is required to satisfy, read at the group layer.
* `TauCeti.DynkinType.geckTwistedFrobenius_eq_self_iff`: a point is fixed exactly when its
  entrywise Frobenius image is its conjugate by the pinned symmetry matrix.
* `TauCeti.DynkinType.map_subtype_fixedSubgroup_geckTwistedFrobenius_le`: the twisted fixed points
  lie among the points of the same carrier over the Frobenius-fixed subring at exponent `k * m`.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* R. Steinberg, *Endomorphisms of linear algebraic groups*, Memoirs Amer. Math. Soc. **80** (1968),
  §11.
* R. W. Carter, *Finite Groups of Lie Type: Conjugacy Classes and Complex Characters*, §§1.15 and
  1.17.

This composes the graph-automorphism and Frobenius halves of the pinning and points targets of
Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`, and reads the two halves' own relations at
the composite. The powers separate because the points are functorial in the value ring, which is
the points target, and the graph factor collapses because a pinned diagram symmetry has finite
order, which is the pinning target; the fixed subgroup is then the one the points target already
carries for the untwisted factor, in `TauCeti.DynkinType.map_subtype_fixedSubgroup_geckFrobenius_eq`
on the carrier and in `TauCeti.Bialgebra.fixedSubgroup_iterateFrobeniusPoints_le_of_dvd` in general.
The consumers are milestone L1, ordinary and graph-twisted Steinberg maps, of
`TauCetiRoadmap/CFSGStatement/README.md`, whose `²A`, `²D`, `²E₆` and `³D₄` branches are
`γ ∘ Frob_q` and whose required relations are that `γ` commutes with `Frob_q` and that `γ` is
annihilated by `2` or by `3`, and milestone L3, which sets `H_d = fixedSubgroup d.steinberg`.
Instantiating either at a `ValidLieTypeIndex` needs this carrier to be identified with the simply
connected form, which is separate Layer 9 work that no statement below anticipates.
-/

public section

namespace TauCeti.DynkinType

universe v

noncomputable section

variable {t : DynkinType} (ht : t.Valid) {sigma : Equiv.Perm (Fin t.rank)}
variable (hsigma : sigma ∈ t.diagramSymmetry) (p k : ℕ) (A : Type v) [CommRing A] [ExpChar A p]

/-- **The graph automorphism of the points of the pinned Geck carrier commutes with its
Frobenius endomorphism.** This is the relation the graph-twisted Steinberg maps of a finite group
of Lie type are required to satisfy. -/
theorem geckGraphAutPoints_comp_geckFrobenius :
    (t.geckGraphAutPoints ht hsigma A).toMonoidHom.comp (t.geckFrobenius ht p k A) =
      (t.geckFrobenius ht p k A).comp (t.geckGraphAutPoints ht hsigma A).toMonoidHom := by
  have hF : t.geckFrobenius ht p k A =
      (t.geckPointsPresentation ht A).map (t.geckPointsPresentation ht A)
        (iterateFrobenius A p k) :=
    MonoidHom.ext fun g => Subtype.ext
      ((t.coe_geckFrobenius ht p k A g).trans
        ((t.geckPointsPresentation ht A).coe_map (t.geckPointsPresentation ht A) _ g).symm)
  rw [hF]
  exact (t.map_comp_geckGraphAutPoints ht hsigma (iterateFrobenius A p k)).symm

/-- **The graph-twisted `p ^ k`-power Frobenius on the points of the pinned Geck carrier**, the
graph automorphism attached to a diagram symmetry composed with the Frobenius endomorphism. The
two factors commute, so composing them in the other order gives the same map.

This is the composite on the carrier and nothing more: no finiteness is asserted of it or of the
fixed subgroup computed below. Its intended application is the twisted branches of a finite group
of Lie type, where `p` is prime, `0 < k`, `A` is an algebraic closure of `ZMod p` and `σ` is an
involution or a triality of the diagram; reading it as the Steinberg endomorphism of such a group
first requires identifying this carrier with the simply connected group, which is not done here. -/
def geckTwistedFrobenius : t.geckPoints ht A →* t.geckPoints ht A :=
  (t.geckGraphAutPoints ht hsigma A).toMonoidHom.comp (t.geckFrobenius ht p k A)

/-- The twisted Frobenius applies the Frobenius first and then the graph automorphism. -/
theorem geckTwistedFrobenius_apply (g : t.geckPoints ht A) :
    t.geckTwistedFrobenius ht hsigma p k A g =
      t.geckGraphAutPoints ht hsigma A (t.geckFrobenius ht p k A g) := (rfl)

/-- The twisted Frobenius is the composite in either order. -/
theorem geckTwistedFrobenius_eq_geckFrobenius_comp :
    t.geckTwistedFrobenius ht hsigma p k A =
      (t.geckFrobenius ht p k A).comp (t.geckGraphAutPoints ht hsigma A).toMonoidHom := by
  rw [geckTwistedFrobenius, geckGraphAutPoints_comp_geckFrobenius]

/-- The twisted Frobenius conjugates the entrywise Frobenius by the matrix of the pinned
coordinate permutation. -/
@[simp]
theorem coe_geckTwistedFrobenius (g : t.geckPoints ht A) :
    (t.geckTwistedFrobenius ht hsigma p k A g :
        Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) A) =
      t.geckGraphAutMatrix ht hsigma A *
          Matrix.GeneralLinearGroup.map (iterateFrobenius A p k) g *
        (t.geckGraphAutMatrix ht hsigma A)⁻¹ := by
  rw [geckTwistedFrobenius_apply, coe_geckGraphAutPoints, coe_geckFrobenius]

/-- **The twisted Frobenius raises the parameter of a numbered Geck root subgroup to its
`p ^ k`-th power and renumbers it by the diagram symmetry.** This is the defining equation of a
graph-twisted Steinberg map on the pinned simple root subgroups. -/
@[simp]
theorem geckTwistedFrobenius_geckRootSubgroupMatrix (i : Fin t.rank ⊕ Fin t.rank)
    (u : Multiplicative A) :
    t.geckTwistedFrobenius ht hsigma p k A
        ⟨t.geckRootSubgroupMatrix ht i
            ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm u),
          t.geckRootSubgroupMatrix_mem_geckPoints ht A i _⟩ =
      ⟨t.geckRootSubgroupMatrix ht (diagramRootGeneratorPerm sigma i)
          ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm
            (Multiplicative.ofAdd (Multiplicative.toAdd u ^ p ^ k))),
        t.geckRootSubgroupMatrix_mem_geckPoints ht A _ _⟩ := by
  have hroot (j : Fin t.rank ⊕ Fin t.rank) (v : Multiplicative A) :
      (⟨t.geckRootSubgroupMatrix ht j
          ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm v),
        t.geckRootSubgroupMatrix_mem_geckPoints ht A j _⟩ : t.geckPoints ht A) =
        t.geckRootSubgroupPoints ht j A v := by
    apply Subtype.ext
    exact (t.coe_geckRootSubgroupPoints ht j A v).symm
  rw [geckTwistedFrobenius_apply, hroot, geckFrobenius_geckRootSubgroupPoints,
    geckGraphAutPoints_geckRootSubgroupPoints, ← hroot]

/-- **The twisted Frobenius raises a point of the represented Geck weight torus to its `p ^ k`-th
power and relabels its coordinates** by the inverse of the diagram symmetry. -/
@[simp]
theorem geckTwistedFrobenius_geckWeightTorusPoints (s : Fin t.rank → Aˣ) :
    t.geckTwistedFrobenius ht hsigma p k A (t.geckWeightTorusPoints ht A s) =
      t.geckWeightTorusPoints ht A fun j => s (sigma⁻¹ j) ^ p ^ k := by
  rw [geckTwistedFrobenius_apply, geckFrobenius_geckWeightTorusPoints,
    geckGraphAutPoints_geckWeightTorusPoints]
  exact congrArg _ (funext fun j => Pi.pow_apply s (p ^ k) _)

/-- **The twisted Frobenius on the pinned Geck weight torus**, written on the matrix that the
represented torus produces. -/
@[simp]
theorem geckTwistedFrobenius_geckTorusMatrix (s : Fin t.rank → Aˣ) :
    t.geckTwistedFrobenius ht hsigma p k A
        ⟨diagGL fun i => torusCharacter s (t.geckWeightFin ht i), by
          simpa only [TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix_apply] using
            t.geckTorusMatrix_mem_geckPoints ht A s⟩ =
      ⟨t.geckTorusMatrix ht fun j => (s (sigma⁻¹ j)) ^ p ^ k,
        t.geckTorusMatrix_mem_geckPoints ht A _⟩ := by
  have htorus (r : Fin t.rank → Aˣ) :
      (⟨t.geckTorusMatrix ht r, t.geckTorusMatrix_mem_geckPoints ht A r⟩ :
          t.geckPoints ht A) = t.geckWeightTorusPoints ht A r :=
    Subtype.ext (t.coe_geckWeightTorusPoints ht A r).symm
  rw [← geckPoints_mk_geckTorusMatrix, htorus, geckTwistedFrobenius_geckWeightTorusPoints,
    ← htorus]

/-! ## The degenerate parameters

At `k = 0` the Frobenius factor is the identity and the composite is the graph automorphism, and at
the identity symmetry the graph factor is the identity and the composite is the Frobenius. The nine
untwisted families of the classification list are therefore the second of these cases of the same
construction rather than a second construction. -/

/-- At exponent zero the twisted Frobenius is the graph automorphism alone. -/
@[simp]
theorem geckTwistedFrobenius_zero :
    t.geckTwistedFrobenius ht hsigma p 0 A = (t.geckGraphAutPoints ht hsigma A).toMonoidHom := by
  rw [geckTwistedFrobenius, geckFrobenius_zero]
  exact MonoidHom.comp_id _

/-- At the identity symmetry the twisted Frobenius is the plain Frobenius. -/
@[simp]
theorem geckTwistedFrobenius_one :
    t.geckTwistedFrobenius ht t.diagramSymmetry.one_mem p k A = t.geckFrobenius ht p k A := by
  rw [geckTwistedFrobenius, geckGraphAutPoints_one]
  exact MonoidHom.id_comp _

/-! ## Powers -/

/-- The powers of an automorphism of a group, read in its endomorphism monoid. This is the only
place the two monoid structures on a bundled automorphism have to be compared, so it stays local to
this file. -/
private theorem toMonoidHom_pow {G : Type*} [Group G] (f : MulAut G) :
    ∀ m : ℕ, (show Monoid.End G from f.toMonoidHom) ^ m = (f ^ m).toMonoidHom
  | 0 => rfl
  | m + 1 => by rw [pow_succ, toMonoidHom_pow f m, pow_succ]; rfl

/-- **The powers of the twisted Frobenius separate into a power of the graph automorphism and a
Frobenius**: the `m`-th power of `γ ∘ Frob_q` is `γ ^ m ∘ Frob_(q ^ m)`.

The separation is exactly the commutation of the two factors; without it a power would only be an
alternating word in them. -/
-- As above, the `show` selects the composition monoid structure before the power is elaborated.
theorem geckTwistedFrobenius_pow (m : ℕ) :
    (show Monoid.End _ from t.geckTwistedFrobenius ht hsigma p k A) ^ m =
      (t.geckGraphAutPoints ht hsigma A ^ m).toMonoidHom.comp (t.geckFrobenius ht p (k * m) A) := by
  -- Multiplication in `Monoid.End` is composition, so commuting is the equation already proved
  -- and the composite is the product of its two factors.
  have hcomm : Commute (show Monoid.End _ from (t.geckGraphAutPoints ht hsigma A).toMonoidHom)
      (show Monoid.End _ from t.geckFrobenius ht p k A) :=
    geckGraphAutPoints_comp_geckFrobenius ht hsigma p k A
  have hmul : (show Monoid.End _ from t.geckTwistedFrobenius ht hsigma p k A) =
      (show Monoid.End _ from (t.geckGraphAutPoints ht hsigma A).toMonoidHom) *
        (show Monoid.End _ from t.geckFrobenius ht p k A) := rfl
  rw [hmul, hcomm.mul_pow, toMonoidHom_pow, geckFrobenius_pow]
  -- The remaining goal is the same product read as a composition.
  rfl

/-- **A diagram symmetry of order dividing `m` makes the `m`-th power of the twisted Frobenius the
plain Frobenius `Frob_(q ^ m)`.** This is the order relation a graph-twisted Steinberg map is
required to satisfy, read at the group layer: `m = 2` for `²Aₙ`, `²Dₙ` and `²E₆`, and `m = 3` for
`³D₄`. -/
-- As above, the `show` selects the composition monoid structure before the power is elaborated.
theorem geckTwistedFrobenius_pow_eq_geckFrobenius {m : ℕ} (hm : sigma ^ m = 1) :
    (show Monoid.End _ from t.geckTwistedFrobenius ht hsigma p k A) ^ m =
      t.geckFrobenius ht p (k * m) A := by
  rw [geckTwistedFrobenius_pow, geckGraphAutPoints_pow_eq_one ht hsigma A hm]
  exact MonoidHom.id_comp _

/-! ## Fixed points -/

/-- **A point of the pinned Geck carrier is fixed by the twisted Frobenius exactly when its
entrywise Frobenius image is its conjugate by the matrix of the pinned coordinate permutation.**
This is the twisted form of the descent condition that
`TauCeti.DynkinType.geckFrobenius_eq_self_iff` records in the untwisted case, where the matrix is
the identity and the condition is that every entry lies in the Frobenius-fixed subring. -/
@[simp]
theorem geckTwistedFrobenius_eq_self_iff (g : t.geckPoints ht A) :
    t.geckTwistedFrobenius ht hsigma p k A g = g ↔
      Matrix.GeneralLinearGroup.map (iterateFrobenius A p k)
          (g : Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) A) =
        (t.geckGraphAutMatrix ht hsigma A)⁻¹ *
          (g : Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) A) *
            t.geckGraphAutMatrix ht hsigma A := by
  rw [← SetLike.coe_eq_coe, coe_geckTwistedFrobenius]
  refine ⟨fun h => ?_, fun h => ?_⟩
  -- The hypothesis rewrites the bare point, which also occurs inside its own Frobenius image, so
  -- the rewrite is confined to the right-hand side.
  · conv_rhs => rw [← h]
    group
  · rw [h]
    group

/-- **The points fixed by the twisted Frobenius are fixed by the Frobenius at exponent `k * m`**,
for `m` any exponent annihilating the diagram symmetry. In the intended application, where `p` is
prime, `0 < k`, `0 < m` and `A` is an algebraic closure of `ZMod p`, that is the Frobenius of the
degree-`m` extension of the field of `q` elements; at the permitted value `m = 0` it is the
identity and the statement is vacuous. -/
theorem fixedSubgroup_geckTwistedFrobenius_le_fixedSubgroup_geckFrobenius {m : ℕ}
    (hm : sigma ^ m = 1) :
    fixedSubgroup (t.geckTwistedFrobenius ht hsigma p k A) ≤
      fixedSubgroup (t.geckFrobenius ht p (k * m) A) := by
  have h := fixedSubgroup_le_fixedSubgroup_pow
    (show Monoid.End _ from t.geckTwistedFrobenius ht hsigma p k A) m
  rwa [geckTwistedFrobenius_pow_eq_geckFrobenius ht hsigma p k A hm] at h

/-- **The twisted fixed points, read inside `GLₙ(A)`, are points of the same carrier over the
Frobenius-fixed subring at exponent `k * m`.** For `p` prime, `0 < k`, `0 < m`, `A` an algebraic
closure of `ZMod p` and `q = p ^ k` that subring is the field of `q ^ m` elements, so this is the
containment of a graph-twisted group of Lie type in the untwisted group over the degree-`m`
extension of its field of definition; at the permitted value `m = 0` the subring is all of `A` and
the containment is vacuous. The containment is strict in general, so no reverse inequality is
stated. -/
theorem map_subtype_fixedSubgroup_geckTwistedFrobenius_le {m : ℕ} (hm : sigma ^ m = 1) :
    (fixedSubgroup (t.geckTwistedFrobenius ht hsigma p k A)).map (t.geckPoints ht A).subtype ≤
      (t.geckPoints ht ↥(frobeniusFixedSubring A p (k * m))).map
        (Matrix.GeneralLinearGroup.map (frobeniusFixedSubring A p (k * m)).subtype) := by
  rw [← DynkinType.map_subtype_fixedSubgroup_geckFrobenius_eq t ht p (k * m) A]
  exact Subgroup.map_mono
    (fixedSubgroup_geckTwistedFrobenius_le_fixedSubgroup_geckFrobenius ht hsigma p k A hm)

/-- **A point fixed by both the Frobenius and the graph automorphism is fixed by the twisted
Frobenius.** The converse fails: the fixed points of the composite are not in general fixed by
either factor, which is what makes a graph-twisted group of Lie type larger than the untwisted
group over its own field of definition. -/
theorem fixedSubgroup_inf_fixedSubgroup_le_fixedSubgroup_geckTwistedFrobenius :
    fixedSubgroup (t.geckFrobenius ht p k A) ⊓
        fixedSubgroup (t.geckGraphAutPoints ht hsigma A).toMonoidHom ≤
      fixedSubgroup (t.geckTwistedFrobenius ht hsigma p k A) := by
  rw [geckTwistedFrobenius]
  exact fixedSubgroup_inf_fixedSubgroup_le_fixedSubgroup_comp _ _

end

end TauCeti.DynkinType
