/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Presentation.MinusculeWeightTable.Rational
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.CoordinateLattice
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Serre
import TauCeti.LinearAlgebra.Matrix.MulVec

/-!
# The admissible lattice of a minuscule weight table

The rational representation of a minuscule weight table acts on the rational coordinate space of
its index type, and the Kostant form of its Serre generators carries the integral lattice of that
space into itself.

Two properties of the table make that so. Each root generator is square-zero: the raising
operator at a node carries a weight of coordinate `-1` to its reflection, whose coordinate is
`1`, and kills every weight of coordinate `1`. And each root generator has integer entries, so it
carries integral coordinate vectors to integral coordinate vectors. The Cartan generators are
diagonal with the table's weights on the diagonal, so every standard coordinate vector is a
weight vector with an integral weight. Divided powers of a square-zero operator and binomial
coefficients of an operator with integral eigenvalues are what the Kostant form is generated by.

## Main declarations

* `TauCeti.MinusculeWeightTable.rep`: the rational representation extended to the universal
  enveloping algebra.

## Main results

* `TauCeti.MinusculeWeightTable.rep_serreRootGenerator_pow_two` and
  `isNilpotent_rep_serreRootGenerator`: the represented root generators are square-zero.
* `TauCeti.MinusculeWeightTable.isCartanWeightVector_single`: each standard coordinate vector is a
  Cartan weight vector with its weight in the table.
* `TauCeti.MinusculeWeightTable.rep_serreKostantForm_mem_lattice`: the Serre Kostant form carries
  `TauCeti.coordinateLattice` into itself.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1--2.
-/

public section

open scoped Matrix

namespace TauCeti.MinusculeWeightTable

attribute [local instance 100] LieRing.ofAssociativeRing

variable {B ι : Type*} [Fintype ι] [DecidableEq ι] (T : MinusculeWeightTable B ι)
variable [DecidableEq B]

/-! ## The enveloping-algebra representation -/

/-- The rational representation extended to the universal enveloping algebra. -/
noncomputable def rep :
    _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ T.cartanMatrix) →ₐ[ℚ]
      Module.End ℚ (ι → ℚ) :=
  _root_.UniversalEnvelopingAlgebra.lift ℚ
    ((Matrix.toLinAlgEquiv (Pi.basisFun ℚ ι)).toAlgHom.toLieHom.comp
      T.rationalSerreRepresentation)

/-- The enveloping-algebra representation acts on an included Lie element by matrix-vector
multiplication. -/
theorem rep_ι_apply (x : Matrix.ToLieAlgebra ℚ T.cartanMatrix) (v : ι → ℚ) :
    T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ x) v = T.rationalSerreRepresentation x *ᵥ v := by
  rw [rep, _root_.UniversalEnvelopingAlgebra.lift_ι_apply, LieHom.comp_apply,
    AlgHom.toLieHom_apply, AlgEquiv.toAlgHom_apply, Matrix.toLinAlgEquiv_apply]
  exact (Pi.basisFun ℚ ι).sum_repr (T.rationalSerreRepresentation x *ᵥ v)

/-- Every represented positive or negative Serre root generator is square-zero. -/
theorem rep_serreRootGenerator_pow_two (k : B ⊕ B) :
    T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
      (TauCeti.serreRootGenerator T.cartanMatrix k)) ^ 2 = 0 := by
  apply LinearMap.ext
  intro v
  rw [pow_two, Module.End.mul_apply]
  cases k with
  | inl i =>
      simpa only [TauCeti.serreRootGenerator_inl, T.rep_ι_apply,
        T.rationalSerreRepresentation_serreE, LinearMap.zero_apply] using
        mulVec_mulVec_eq_zero_of_pow_two_eq_zero (T.raisingMatrixQ_pow_two i) v
  | inr i =>
      simpa only [TauCeti.serreRootGenerator_inr, T.rep_ι_apply,
        T.rationalSerreRepresentation_serreF, LinearMap.zero_apply] using
        mulVec_mulVec_eq_zero_of_pow_two_eq_zero (T.loweringMatrixQ_pow_two i) v

/-- Every represented positive or negative Serre root generator acts nilpotently. -/
theorem isNilpotent_rep_serreRootGenerator (k : B ⊕ B) :
    IsNilpotent (T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
      (TauCeti.serreRootGenerator T.cartanMatrix k))) :=
  ⟨2, T.rep_serreRootGenerator_pow_two k⟩

/-! ## Stability of the coordinate lattice -/

/-- Every represented Serre root generator preserves the coordinate lattice. -/
theorem rep_serreRootGenerator_mem_lattice (k : B ⊕ B) {v : ι → ℚ}
    (hv : v ∈ TauCeti.coordinateLattice ι) :
    T.rep (_root_.UniversalEnvelopingAlgebra.ι ℚ
      (TauCeti.serreRootGenerator T.cartanMatrix k)) v ∈ TauCeti.coordinateLattice ι := by
  rw [T.rep_ι_apply]
  cases k with
  | inl i =>
      rw [TauCeti.serreRootGenerator_inl, T.rationalSerreRepresentation_serreE]
      have hmatrix : T.raisingMatrixQ i = TauCeti.matrixIntCastLieHom ℚ (T.raisingMatrix i) := by
        ext a b
        rw [T.raisingMatrixQ_apply, TauCeti.matrixIntCastLieHom_apply, T.raisingMatrix_apply]
        split_ifs <;> norm_num
      rw [hmatrix]
      exact Matrix.intCastLieHom_mulVec_mem_coordinateLattice (T.raisingMatrix i) hv
  | inr i =>
      rw [TauCeti.serreRootGenerator_inr, T.rationalSerreRepresentation_serreF]
      have hmatrix : T.loweringMatrixQ i = TauCeti.matrixIntCastLieHom ℚ (T.loweringMatrix i) := by
        ext a b
        rw [T.loweringMatrixQ_apply, TauCeti.matrixIntCastLieHom_apply, T.loweringMatrix_apply]
        split_ifs <;> norm_num
      rw [hmatrix]
      exact Matrix.intCastLieHom_mulVec_mem_coordinateLattice (T.loweringMatrix i) hv

/-- Each standard coordinate vector is a Cartan weight vector with its weight in the table. -/
theorem isCartanWeightVector_single (a : ι) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector
      (TauCeti.serreH ℚ T.cartanMatrix) T.rep (T.weight a) (Pi.single a 1) := by
  refine (TauCeti.UniversalEnvelopingAlgebra.isCartanWeightVector_iff
    (TauCeti.serreH ℚ T.cartanMatrix) T.rep).mpr fun i ↦ ?_
  rw [T.rep_ι_apply, T.rationalSerreRepresentation_serreH]
  ext b
  simp [Matrix.mulVec, dotProduct, Pi.single_apply]

/-- Every coordinate-lattice basis vector is a Cartan weight vector with its weight in the
table. -/
theorem isCartanWeightVector_coordinateLatticeBasis (a : ι) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector
      (TauCeti.serreH ℚ T.cartanMatrix) T.rep (T.weight a)
      ((TauCeti.coordinateLatticeBasis ι a : TauCeti.coordinateLattice ι) : ι → ℚ) := by
  rw [TauCeti.coe_coordinateLatticeBasis, Pi.basisFun_apply]
  exact T.isCartanWeightVector_single a

/-- **The coordinate lattice is admissible for the Serre Kostant form of a minuscule weight
table.** -/
theorem rep_serreKostantForm_mem_lattice
    {u : _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ T.cartanMatrix)}
    (hu : u ∈ TauCeti.serreKostantForm T.cartanMatrix) {v : ι → ℚ}
    (hv : v ∈ TauCeti.coordinateLattice ι) :
    T.rep u v ∈ TauCeti.coordinateLattice ι := by
  rw [TauCeti.serreKostantForm_def] at hu
  exact TauCeti.UniversalEnvelopingAlgebra.kostantForm_apply_mem_coordinateLattice
    (TauCeti.serreRootGenerator T.cartanMatrix) (TauCeti.serreH ℚ T.cartanMatrix) T.rep
    (wt := T.weight) T.rep_serreRootGenerator_pow_two
    (fun k _ hw ↦ T.rep_serreRootGenerator_mem_lattice k hw) T.isCartanWeightVector_single hu hv

/-- The coordinate lattice is stable under the generic Kostant form built from the Serre
generators. This is the form consumed by the carrier and base-change APIs. -/
theorem rep_kostantForm_mem_lattice
    (u : _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ T.cartanMatrix))
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm
      (TauCeti.serreRootGenerator T.cartanMatrix) (TauCeti.serreH ℚ T.cartanMatrix))
    (v : ι → ℚ) (hv : v ∈ TauCeti.coordinateLattice ι) :
    T.rep u v ∈ TauCeti.coordinateLattice ι :=
  T.rep_serreKostantForm_mem_lattice (by
    rw [TauCeti.serreKostantForm_def]
    exact hu) hv

end TauCeti.MinusculeWeightTable
