/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import TauCeti.Algebra.Order.Group.ConvexSubgroup

/-!
# Cofinal elements of an ordered group

Cofinality following Wedhorn, *Adic Spaces* (arXiv:1910.05934v1), §1.4: an element is
cofinal for a subgroup if its powers eventually fall below every member. The definition
needs only a group with a strict order; the results relating cofinality to convex
subgroups are stated for linearly ordered commutative groups. This is the order-theoretic
input to the continuity criterion for valuations (Wedhorn §7.2) and the retraction
`r_I : Spv A → Spv(A, I)` of §7.1.2.

## Main definitions

* `TauCeti.IsCofinalElement H γ` : Powers of `γ` fall below every member
  of `H` (Wedhorn Definition 1.16). Unlike Mathlib's `IsCofinal`, which describes a
  *set* that is cofinal for the ambient order with respect to `≤`, this is a property of
  an *element* with respect to the strict order, following Wedhorn.

## Main results

* `TauCeti.IsCofinalElement.comap` : Cofinality transports backwards through an ordered
  monoid isomorphism.
* `TauCeti.isCofinalElement_iff_subset_closure` : For `γ < 1`, `γ` is
  cofinal for `H` iff the convex subgroup generated by `γ` contains `H`
  (Wedhorn Remark 1.19).
* `TauCeti.IsCofinalElement.mul_of_lt_of_mem` : Cofinal elements may be
  perturbed by members of any strictly smaller convex subgroup (Wedhorn
  Proposition 1.20).
* `TauCeti.isGreatest_convexSubgroup_isCofinalElement` : If a set of elements
  below `1` has a greatest element `h`, the convex subgroup generated by `h` is the
  greatest one for which every member of the set is cofinal (the order-theoretic
  content of Wedhorn Lemma 7.2).
* `TauCeti.IsCofinalElement.quotientMk` : A cofinal element stays cofinal in the
  quotient by a proper convex subgroup (Wedhorn Corollary 1.21).

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Definition 1.16, Remark 1.19,
  Proposition 1.20, Corollary 1.21, Lemma 7.2

Adapted from the AINTLIB development (Apache 2.0), file
`projects/AdicSpaces/Adic spaces/OrderedGroupConvex.lean` (the cofinality half; its
convex-subgroup half is the parent module), with the predicate restated over subgroups
as in Wedhorn's Definition 1.16.
-/

public section

namespace TauCeti

open ConvexSubgroup

/-! ### Cofinal elements -/

section Definition

variable {Γ : Type*} [Group Γ] [LT Γ]

/-- An element `γ` is **cofinal** for the subgroup `H` if every member of `H`
eventually dominates the powers of `γ`: `∀ h ∈ H, ∃ n, γ ^ n < h`. This is the
`γ ∈ Γ` case of Wedhorn Definition 1.16, which takes `H` to be any subgroup and
lets the base range over `Γ ∪ {0}`; the adjoined base `0` is cofinal for every
subgroup trivially, and the vanishing-base case belongs with the valuation-side
theory, over a value group with zero, rather than here. Membership of `γ` in `H`
is not required. Distinct from Mathlib's `IsCofinal`,
a property of sets with respect to `≤`. -/
def IsCofinalElement (H : Subgroup Γ) (γ : Γ) : Prop :=
  ∀ h ∈ H, ∃ n : ℕ, γ ^ n < h

/-- The defining property of a cofinal element.

Deliberately not `@[simp]`: the right-hand side is the unfolded bounded quantifier, so tagging
it rewrites uses of the named predicate into raw `∀ … ∃ …` form. This mirrors
`Valuation.cofinalValueFor_def`, which is not `@[simp]` for the same reason. -/
theorem isCofinalElement_def {H : Subgroup Γ} {γ : Γ} :
    IsCofinalElement H γ ↔ ∀ h ∈ H, ∃ n : ℕ, γ ^ n < h :=
  Iff.rfl

end Definition

section Transport

variable {Γ' : Type*} [Group Γ] [Preorder Γ] [Group Γ'] [Preorder Γ']

/-- Cofinality transports backwards through an ordered monoid isomorphism, with the subgroup
pulled back along the same isomorphism. -/
theorem IsCofinalElement.comap {H : Subgroup Γ'} {γ : Γ} {e : Γ ≃*o Γ'}
    (hγ : IsCofinalElement H (e γ)) : IsCofinalElement (H.comap e.toMonoidHom) γ := by
  rw [isCofinalElement_def] at hγ ⊢
  intro x hx
  obtain ⟨n, hn⟩ := hγ (e x) hx
  have hmap : e (γ ^ n) < e x := by
    rw [map_pow]
    exact hn
  exact ⟨n, (OrderIso.lt_iff_lt e.toOrderIso).mp hmap⟩

end Transport

section LtOne

variable {Γ : Type*} [Group Γ] [LinearOrder Γ] [MulLeftMono Γ]

/-- No element `≥ 1` is cofinal for any subgroup (Wedhorn's remark after
Definition 1.16): a cofinal element lies strictly below `1`. -/
theorem IsCofinalElement.lt_one {H : Subgroup Γ} {γ : Γ}
    (hγ : IsCofinalElement H γ) : γ < 1 := by
  obtain ⟨n, hn⟩ := hγ 1 (one_mem H)
  by_contra h
  push Not at h
  exact absurd hn (not_lt.mpr (one_le_pow_of_one_le' h n))

end LtOne

variable {Γ : Type*} [CommGroup Γ] [LinearOrder Γ] [IsOrderedMonoid Γ]

/-- **Wedhorn Remark 1.19.** For `γ < 1`, the element `γ` is cofinal for `H` iff the
convex subgroup generated by `γ` contains `H`. -/
theorem isCofinalElement_iff_subset_closure {H : Subgroup Γ} {γ : Γ} (hγ1 : γ < 1) :
    IsCofinalElement H γ ↔ (H : Set Γ) ⊆ closure {γ} := by
  constructor
  · intro hγ h hh
    obtain ⟨n, hn⟩ := hγ h hh
    obtain ⟨m, hm⟩ := hγ h⁻¹ (inv_mem hh)
    rw [SetLike.mem_coe, mem_closure_singleton, mabs_eq_inv_self.mpr hγ1.le]
    refine ⟨max n m, mabs_le.mpr ⟨?_, ?_⟩⟩
    · rw [inv_pow, inv_inv]
      exact (pow_le_pow_right_of_le_one' hγ1.le (le_max_left n m)).trans hn.le
    · have h1 : h < (γ ^ m)⁻¹ := by
        have h2 := inv_lt_inv' hm
        rwa [inv_inv] at h2
      refine h1.le.trans ?_
      rw [inv_pow]
      exact inv_le_inv' (pow_le_pow_right_of_le_one' hγ1.le (le_max_right n m))
  · intro hsub h hh
    obtain ⟨n, hbd⟩ := mem_closure_singleton.mp (hsub hh)
    rw [mabs_eq_inv_self.mpr hγ1.le, inv_pow] at hbd
    have hle : γ ^ n ≤ h := by
      have := (mabs_le.mp hbd).1
      rwa [inv_inv] at this
    have hstep : γ ^ (n + 1) < γ ^ n := by
      calc γ ^ (n + 1) = γ * γ ^ n := by rw [pow_succ, mul_comm]
        _ < 1 * γ ^ n := mul_lt_mul_left hγ1 (γ ^ n)
        _ = γ ^ n := one_mul _
    exact ⟨n + 1, hstep.trans_le hle⟩

/-- **Wedhorn Proposition 1.20.** If `γ` is cofinal for the convex subgroup `Γ'` and
`Δ < Γ'` is a strictly smaller convex subgroup, then `δ * γ` is cofinal for `Γ'` for
every `δ ∈ Δ`. -/
theorem IsCofinalElement.mul_of_lt_of_mem {Γ' Δ : ConvexSubgroup Γ}
    {γ : Γ} (hγ : IsCofinalElement Γ'.toSubgroup γ) (hlt : Δ < Γ') {δ : Γ}
    (hδ : δ ∈ Δ) : IsCofinalElement Γ'.toSubgroup (δ * γ) := by
  intro h hh
  obtain ⟨z, hzQ, hzD, hz_gt⟩ := Subgroup.exists_one_lt_of_lt (ConvexSubgroup.toSubgroup_lt.mpr hlt)
  obtain ⟨n, hn⟩ := hγ z⁻¹ (inv_mem hzQ)
  have hzi_lt : z⁻¹ < 1 := inv_lt_one'.mpr hz_gt
  have hγ_lt : γ < 1 := hγ.lt_one
  have hn1 : 1 ≤ n := by
    rcases Nat.eq_zero_or_pos n with rfl | hp
    · simp only [pow_zero] at hn
      exact absurd (hn.trans hzi_lt) (lt_irrefl _)
    · exact hp
  have hz_gt_D : ∀ d ∈ Δ, d < z := fun d hd ↦ by
    by_contra hge
    rw [not_lt] at hge
    exact hzD (Δ.convex (one_mem Δ) hd hz_gt.le hge)
  have hzγn : z * γ ^ n < 1 := by
    have h2 : γ ^ n * z < z⁻¹ * z := mul_lt_mul_left hn z
    rw [inv_mul_cancel] at h2
    rwa [mul_comm] at h2
  have hkey : (δ * γ) ^ (2 * n) < γ ^ n := by
    have hδ2n : δ ^ (2 * n) < z := hz_gt_D _ (Δ.toSubgroup.pow_mem hδ (2 * n))
    calc (δ * γ) ^ (2 * n) = δ ^ (2 * n) * γ ^ (2 * n) := mul_pow δ γ (2 * n)
      _ < z * γ ^ (2 * n) := mul_lt_mul_left hδ2n _
      _ = (z * γ ^ n) * γ ^ n := by rw [two_mul, pow_add, ← mul_assoc]
      _ < 1 * γ ^ n := mul_lt_mul_left hzγn _
      _ = γ ^ n := one_mul _
  obtain ⟨m, hm1, hm⟩ : ∃ m, 1 ≤ m ∧ γ ^ m < h := by
    obtain ⟨m0, hm0⟩ := hγ h hh
    rcases Nat.eq_zero_or_pos m0 with rfl | hp
    · refine ⟨1, le_refl _, ?_⟩
      rw [pow_one]
      rw [pow_zero] at hm0
      exact lt_trans hγ_lt hm0
    · exact ⟨m0, hp, hm0⟩
  refine ⟨2 * n * m, ?_⟩
  calc (δ * γ) ^ (2 * n * m) = ((δ * γ) ^ (2 * n)) ^ m := by rw [← pow_mul]
    _ < (γ ^ n) ^ m := pow_lt_pow_left' (Nat.one_le_iff_ne_zero.mp hm1) hkey
    _ = γ ^ (n * m) := by rw [← pow_mul]
    _ ≤ γ ^ m := pow_le_pow_right_of_le_one' hγ_lt.le (Nat.le_mul_of_pos_left m hn1)
    _ < h := hm

/-- **The greatest convex subgroup with a prescribed cofinal set.** If a set `S` of
elements below `1` has a greatest element `h`, then the convex subgroups for which
*every* member of `S` is cofinal are exactly those contained in the one generated by
`h`, so that subgroup is the greatest of them.

Note the inversion: below `1` a *smaller* element generates a *larger* convex subgroup,
so the greatest element of `S` yields the smallest of the generated subgroups, and it is
that one which every member of `S` is cofinal for. This is the order-theoretic content of
Wedhorn Lemma 7.2, where `S` is the set of values of a finite generating set of an ideal
and `h` is the largest of them. -/
theorem isGreatest_convexSubgroup_isCofinalElement {S : Set Γ} {h : Γ}
    (hh : IsGreatest S h) (hlt : h < 1) :
    IsGreatest {K : ConvexSubgroup Γ | ∀ γ ∈ S, IsCofinalElement K.toSubgroup γ}
      (closure {h}) := by
  constructor
  · intro γ hγ
    refine (isCofinalElement_iff_subset_closure
      (lt_of_le_of_lt (hh.2 hγ) hlt)).mpr (SetLike.coe_subset_coe.mpr ?_)
    refine closure_le.mpr fun x hx ↦ ?_
    rw [Set.mem_singleton_iff] at hx
    subst hx
    rw [SetLike.mem_coe, mem_closure_singleton]
    exact ⟨1, by
      rw [pow_one, mabs_eq_inv_self.mpr hlt.le,
        mabs_eq_inv_self.mpr ((hh.2 hγ).trans hlt.le)]
      exact inv_le_inv' (hh.2 hγ)⟩
  · exact fun K hK ↦ SetLike.coe_subset_coe.mp
      ((isCofinalElement_iff_subset_closure hlt).mp (hK h hh.1))

/-! ### Cofinality in a quotient -/

/-- **Wedhorn Corollary 1.21.** A cofinal element stays cofinal in the quotient by a
*proper* convex subgroup: if `γ` is cofinal for `Γ` and `Δ ≠ ⊤`, the class of `γ` is cofinal
for `Γ ⧸ Δ`.

Properness is not a convenience hypothesis. For `Δ = ⊤` the quotient is trivial, and the
only element of a trivial group is `1`, which is cofinal for nothing.

This is the order-theoretic core of Wedhorn Remark 7.11(2), which reads it as saying that a
vertical generization `v / H` of a continuous valuation is again continuous. -/
theorem IsCofinalElement.quotientMk {Δ : ConvexSubgroup Γ} (hΔ : Δ ≠ ⊤) {γ : Γ}
    (hγ : IsCofinalElement (⊤ : Subgroup Γ) γ) :
    IsCofinalElement (⊤ : Subgroup (Γ ⧸ Δ.toSubgroup)) (QuotientGroup.mk' Δ.toSubgroup γ) := by
  obtain ⟨d, -, hdΔ, hd1⟩ := Subgroup.exists_one_lt_of_lt
    (by simpa using ConvexSubgroup.toSubgroup_lt.mpr (lt_top_iff_ne_top.mpr hΔ))
  intro q _
  induction q using Quotient.inductionOn with | _ h =>
  obtain ⟨n, hn⟩ := hγ (d⁻¹ * h) trivial
  -- `γ ^ n` is pushed below `d⁻¹ * h`, which is what makes its class land *strictly* below
  -- that of `h`: monotonicity of the quotient map alone would give only `≤`.
  have hkey : d < (γ ^ n)⁻¹ * h := by
    rw [lt_inv_mul_iff_mul_lt]
    calc γ ^ n * d < (d⁻¹ * h) * d := mul_lt_mul_left hn d
      _ = h := by rw [mul_comm d⁻¹ h, mul_assoc, inv_mul_cancel, mul_one]
  refine ⟨n, not_le.mp ?_⟩
  rw [← map_pow]
  simp only [QuotientGroup.mk'_apply, quotient_le_iff, not_or]
  exact ⟨not_le.mpr (hd1.trans hkey), Δ.notMem_of_notMem_of_one_le_le hdΔ hd1.le hkey.le⟩


end TauCeti
