/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Complex.Fuchsian.ProperAction
public import TauCeti.Analysis.Complex.UpperHalfPlane.Stabilizer
import TauCeti.Topology.Algebra.ConstMulAction

/-!
# Point stabilizers of Fuchsian groups

A discrete subgroup `Γ ≤ PSL(2, ℝ)` acts properly discontinuously on the upper half-plane, so its
point stabilizers are finite, and a finite point stabilizer of a subgroup of `PSL(2, ℝ)` is
cyclic (`Subgroup.isCyclic_stabilizer`). Hence the point stabilizers of a Fuchsian
group are finite cyclic: these are its elliptic stabilizers, generated by a transformation whose
derivative at the fixed point is a primitive root of unity of the stabilizer's order
(`Subgroup.exists_isPrimitiveRoot_stabilizerDeriv`).

## Main declarations

* `Subgroup.instIsCyclicStabilizer`: the point stabilizers of a discrete subgroup
  of `PSL(2, ℝ)` are cyclic.

## References

* Alan Beardon, *The Geometry of Discrete Groups*, Graduate Texts in Mathematics 91,
  Springer, 1983, Chapter 8.
* Svetlana Katok, *Fuchsian Groups*, Chicago Lectures in Mathematics, University of
  Chicago Press, 1992, §2.4.
-/

public section

open MulAction UpperHalfPlane

open scoped MatrixGroups

namespace Subgroup

/-- **The point stabilizers of a Fuchsian group are cyclic**: for a discrete subgroup
`Γ ≤ PSL(2, ℝ)`, the stabilizer of every point of `ℍ` is cyclic. -/
instance instIsCyclicStabilizer (Γ : Subgroup PSL(2, ℝ)) [DiscreteTopology Γ] (z : ℍ) :
    IsCyclic (stabilizer Γ z) :=
  isCyclic_stabilizer Γ z

end Subgroup
