/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CMField.Basic
public import TauCeti.NumberTheory.Multiquadratic.Subfield.Classification
import TauCeti.NumberTheory.Multiquadratic.RelativeDegree

/-!
# The candidate genus field over `ℚ(√-5)`

The multiquadratic roadmap's first genus-field example uses the prime discriminants `-4` and `5`,
with radicands `-1` and `5` and roots `i` and `√5`. Since `ℚ(√-5)` has genus field
`ℚ(√-1, √5) = ℚ(i, √5)`, its candidate genus field is exactly the multiquadratic CM field for the
single prime `5`, so we present it through the existing CM family
`TauCeti.Multiquadratic.cmRoot ![5]` (indexed by `Option (Fin 1)`) rather than a bespoke generator
list. The ambient compositum `ℚ(i, √5)` has degree four over `ℚ`
(`finrank_adjoin_I_sqrt_five`); this file identifies the quadratic subfield generated by the
product of its two roots and computes that the compositum has degree two over it.

The product root squares to `-5`, so its simple extension is the copy of `ℚ(√-5)` inside the
candidate genus field. The relative-degree calculation then specializes
`TauCeti.Multiquadratic.finrank_top_over_intermediateField_of_finrank_eq_two`. This supplies the
field-degree part of the roadmap's `ℚ(√-5)` acceptance example (`[K_gen : ℚ(√-5)] = 2 = 2 ^ (t - 1)`
with `t = 2` ramified primes). Maximality is available in general for the canonical
`candidateGenusField hd` through `isGenusField_candidateGenusField`; the identification of the
explicit compositum with that canonical field is proved in `MinusFive/GenusField`. This is the
CM-presented companion of
the `ℚ(√-21)` example
`finrank_candidateGenusField_over_sqrtNegTwentyOneSubfield`, whose generators `i√3, i√7` are not
real square roots of primes and so are not captured by the `cmRoot` family, so that example uses a
bespoke generator list instead.

The prime-discriminant description follows D. A. Cox, *Primes of the Form x² + ny²*, and
F. Lemmermeyer's *Reciprocity Laws*.

## Main results

* `TauCeti.Multiquadratic.sqrtNegFiveSubfield`: the quadratic subfield of `ℚ(i, √5)` generated by
  the product `i · √5`.
* `TauCeti.Multiquadratic.prodRootMem_univ_sq_minusFive`: that product squares to `-5`.
* `TauCeti.Multiquadratic.finrank_candidateGenusField_over_sqrtNegFiveSubfield`: the candidate
  genus field has degree two over this copy of `ℚ(√-5)`.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The square-class independence of the CM radicands `-1, 5` of `ℚ(√-5)`, in the form the subfield
constructions consume. -/
private theorem not_isSquare_prod_cmRadicand_five (S : Finset (Option (Fin 1))) (hS : S.Nonempty) :
    ¬ IsSquare (∏ x ∈ S, cmRadicand ![5] x) :=
  not_isSquare_prod_cmRadicand ![5] (by decide) (by decide) S hS

/-- The copy of `ℚ(√-5)` inside the candidate genus field `ℚ(i, √5)`, generated by the product of
its two chosen roots `i` and `√5`. -/
noncomputable def sqrtNegFiveSubfield :
    IntermediateField ℚ (adjoin ℚ (Set.range (cmRoot ![5]))) :=
  (quadraticSubfieldOfFinset (cmRoot_sq ![5]) not_isSquare_prod_cmRadicand_five
    ⟨Finset.univ, Finset.univ_nonempty⟩).1

/-- The named quadratic subfield is generated by the product of both chosen roots. -/
@[simp] theorem sqrtNegFiveSubfield_def :
    sqrtNegFiveSubfield =
      adjoin ℚ {prodRootMem (K := ℚ) (cmRoot ![5]) (Finset.univ : Finset (Option (Fin 1)))} :=
  quadraticSubfieldOfFinset_val (cmRoot_sq ![5]) not_isSquare_prod_cmRadicand_five
    ⟨Finset.univ, Finset.univ_nonempty⟩

/-- The generator of `sqrtNegFiveSubfield` squares to `-5`. -/
@[simp] theorem prodRootMem_univ_sq_minusFive :
    (prodRootMem (K := ℚ) (cmRoot ![5]) (Finset.univ : Finset (Option (Fin 1)))) ^ 2
      = algebraMap ℚ (adjoin ℚ (Set.range (cmRoot ![5]))) (-5) := by
  have hprod : ∏ x : Option (Fin 1), cmRadicand ![5] x = -5 := by
    rw [Fintype.prod_option, Fin.prod_univ_one]
    norm_num [cmRadicand_none, cmRadicand_some]
  rw [prodRootMem_sq (cmRoot_sq ![5])]
  exact congrArg _ hprod

/-- The subfield generated by the product root of `-5` is quadratic over `ℚ`. -/
theorem finrank_sqrtNegFiveSubfield :
    Module.finrank ℚ sqrtNegFiveSubfield = 2 :=
  (quadraticSubfieldOfFinset (cmRoot_sq ![5]) not_isSquare_prod_cmRadicand_five
    ⟨Finset.univ, Finset.univ_nonempty⟩).2

/-- **The candidate genus field for `ℚ(√-5)` has relative degree two.**
The degree-four compositum `ℚ(i, √5)` has degree `2` over its quadratic subfield generated by the
product root, which squares to `-5`. -/
theorem finrank_candidateGenusField_over_sqrtNegFiveSubfield :
    Module.finrank sqrtNegFiveSubfield
      (adjoin ℚ (Set.range (cmRoot ![5]))) = 2 := by
  have h := finrank_top_over_intermediateField_of_finrank_eq_two
    (cmRoot_sq ![5]) not_isSquare_prod_cmRadicand_five
    sqrtNegFiveSubfield finrank_sqrtNegFiveSubfield
  norm_num [Nat.card_eq_fintype_card, Fintype.card_option, Fintype.card_fin] at h ⊢
  exact h

end TauCeti.Multiquadratic
